src/objects/Account_Plan__c.object
<CustomObject>
    <description>Account planning is the process of mapping out important details about your customer, including information about their decision-making process, the companies you&apos;re competing with to close them, and the overall strategy to win them over, retain and grow them.

An Account plan is yearly-based as it&apos;s typically something you create at the beginning of the year and you keep track of your progress throughout the months.

This account plan is based on the &quot;OGSM&quot; strategic planning methodology: an OGSM is a written and easily communicated statement of an organization’s Objective, Goals, Strategies and Measures. OGSM brings alignment, transparency of priorities and metrics that define success.</description>
    <fields>
        <fullName>AccountPlanOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Plan Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <defaultValue>TEXT(YEAR(Today()))</defaultValue>
        <label>Calendar Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>TEXT(Year(22 November 2021))</fullName>
                    <isActive>false</isActive>
                    <label>TEXT(Year(22 November 2021))</label>
                </value>
                <value>
                    <fullName>Year(22 November 2021)</fullName>
                    <isActive>false</isActive>
                    <label>Year(22 November 2021)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Objective__c.object
<CustomObject>
    <description>This account plan is based on the &quot;OGSM&quot; strategic planning methodology: an OGSM is a written and easily communicated statement of an organization’s Objective, Goals, Strategies and Measures. OGSM brings alignment, transparency of priorities and metrics that define success.</description>
    <fields>
        <fullName>AccountPlan__c</fullName>
        <inlineHelpText>Account planning is the process of mapping out important details about your customer, including information about their decision-making process, the companies you&apos;re competing with to close them, and the overall strategy to win them over, retain and grow them.</inlineHelpText>
        <label>Account Plan</label>
        <referenceTo>Account_Plan__c</referenceTo>
        <relationshipLabel>Account Plan Objectives</relationshipLabel>
        <relationshipName>Account_Plan_Objectives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Goals__c</fullName>
        <inlineHelpText>“what must we accomplish financially?”
Goals are numbers that define what success looks like, usually financial and/or operational, it makes the Objective visible in measurable terms.</inlineHelpText>
        <label>Goals</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IndicatedActions__c</fullName>
        <label>Action Plan</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Initiatives__c</fullName>
        <inlineHelpText>&quot;What are the choices that we have ?&quot;
Strategies are words that provide explanations and descriptions of specific choices that focus an organization’s plans toward accomplishing the desired Objective and Goals</inlineHelpText>
        <label>Strategies &amp; Initiatives</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Measures__c</fullName>
        <inlineHelpText>&quot;Are these Strategies working?&quot;
Measures are numbers that define an organization’s progress toward delivering a Strategy. Each Strategy should have no more than two or three Measures that define whether the Strategy is effective and is having the desired impact. Each Measure is tracked to determine the progress of a Strategy, and used to make decisions regarding any necessary adjustments.</inlineHelpText>
        <label>Measures</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Objective__c</fullName>
        <inlineHelpText>&quot;What are we trying to achieve?&quot;
 The Objective should define the playing field and the rules for winning. An Objective is a constant and meaningful reminder to the organization about what success looks like in the future. An effective Objective statement is not generic; it is a customized, business-specific view of where the business is headed.</inlineHelpText>
        <label>Objective</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>StatusNotes__c</fullName>
        <label>Status Notes</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <color>#FF99FF</color>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Green</fullName>
                    <color>#78C953</color>
                    <label>Green</label>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                    <color>#F3D904</color>
                    <label>Yellow</label>
                </value>
                <value>
                    <fullName>Red</fullName>
                    <color>#8F6429</color>
                    <label>Red</label>
                </value>
                <value>
                    <fullName>Achieved</fullName>
                    <color>#57F17C</color>
                    <label>Achieved</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Plan Objective</label>
    <nameField>
        <displayFormat>OB-{000}</displayFormat>
        <label>Objective #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ObjectivesController_OGSM.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Nihad Aoussar (Salesforce) 20211020
Description:    OGSM objectives Controller Class
Test Class:     Test_ObjectivesController_OGSM
History:        
20211020        create fetchObjectives, updateObjectives, deleteObjective
20220926        create cloneObjective
----------------------------------------------------------------------------------------*/
public with sharing class ObjectivesController_OGSM {
   /*------------------------------------------------------------  
    Description:    Method to fetch objectives related to an accountPlan record
    Inputs:         Id of the account plan 
    ------------------------------------------------------------*/
    @AuraEnabled(cacheable=true)
    public static List<Objective__c> fetchObjectives(Id accountPlanId){
        try {
            return [ SELECT Id, Name , Objective__c, Goals__c , Initiatives__c, Measures__c, Status__c, IndicatedActions__c,StatusNotes__c ,CreatedDate 
                        from Objective__c 
                        where AccountPlan__c=:accountPlanId 
                         ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
   /*------------------------------------------------------------  
    Description:    Method to update objective record
    Inputs:         Object to update  
    ------------------------------------------------------------*/
    @AuraEnabled(cacheable=false)
    public static void updateObjectives(Object data){
        List < Objective__c > objectivesForUpdate = ( List < Objective__c > ) JSON.deserialize(
            JSON.serialize( data ),
            List < Objective__c >.class);
        try {
            update objectivesForUpdate;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
   /*------------------------------------------------------------  
    Description:    Method to delete objective record
    Inputs:         Id of the record to update  
    ------------------------------------------------------------*/
    @AuraEnabled
    public static void deleteObjective(Id objectiveId){
        try {
            Objective__c obj = new Objective__c(Id = objectiveId);
            delete obj;
          
        }
        catch(Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    /*------------------------------------------------------------  
    Description:    Method to clone objective record when not completed in the current calendar year 
    Inputs:         Id of the record to update  
    ------------------------------------------------------------*/
    @AuraEnabled
    public static String cloneObjective(Id objectiveId, Id currentAccPlan ){
        try {
            Id userId = UserInfo.getUserId();
            Account_Plan__c newAccountPlan;
            String nextYear = ''+((system.today().year())+1);
            Objective__c objectiveToClone = [SELECT Id, Name , Objective__c, Goals__c , Initiatives__c, Measures__c, Status__c, IndicatedActions__c,StatusNotes__c 
                                             FROM Objective__c WHERE Id =:objectiveId LIMIT 1];
            Objective__c clonedObjective = objectiveToClone.clone(false, true, false, false);
            Account_Plan__c currentAccountPlan = [SELECT Account__c,Year__c From Account_Plan__c WHERE Id=:currentAccPlan LIMIT 1];
            Id accountId = currentAccountPlan.Account__c;
            List<Account_Plan__c> nextYearAccPlan = [SELECT Id,Year__c,Account__c From Account_Plan__c WHERE Account__c=: accountId AND Year__c =:nextYear ];
            if(!nextYearAccPlan.isEmpty()){
                clonedObjective.AccountPlan__c = nextYearAccPlan[0].Id;
            }else{
                newAccountPlan = new Account_Plan__c (AccountPlanOwner__c = userId,
                                                    Year__c  = nextYear,
                                                    Account__c = accountId);
                insert  newAccountPlan;
                clonedObjective.AccountPlan__c = newAccountPlan.Id;
    		}
            insert clonedObjective;
            return clonedObjective.id;
        }
        catch(Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
}