src/objects/ActionOverride__mdt.object
<CustomObject>
    <fields>
        <fullName>ActionName__c</fullName>
        <defaultValue>&quot;new&quot;</defaultValue>
        <label>Action name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlowName__c</fullName>
        <label>Flow name (API)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <referenceTo>EntityDefinition</referenceTo>
        <relationshipLabel>Action_Override_Settings</relationshipLabel>
        <relationshipName>Action_Override_Settings</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <label>Action Override Setting</label>
    <pluralLabel>Action Override Settings</pluralLabel>
</CustomObject>

src/classes/flowOverrideController.cls
/*------------------------------------------------------------
Author: 		Richard Trum (Glimt) 2023-12-01
Description:   	AuraEnabled class to get action override settings when overriding standard actions with a screen flow
Test class:     Test_flowOverrideController
History
<Date>      <Authors Name>     <Brief Description of Change>
20231201 	Richard Trum		TFUS-000006257

------------------------------------------------------------*/

public with sharing class flowOverrideController {
    
    @AuraEnabled(cacheable=false)
    public static ActionOverride__mdt getFlowOverride(String objname, String actionname) {

        List<ActionOverride__mdt> actionSettings = new List<ActionOverride__mdt>();
        try{
            actionSettings = [SELECT DeveloperName, Object__r.QualifiedApiName, FlowName__c, ActionName__c FROM ActionOverride__mdt WHERE Object__r.QualifiedApiName =: objname AND ActionName__c =: actionname LIMIT 1];
        }
        catch(DmlException e){
            DebugLog.addException(e, 'flowOverrideController.getFlowOverride');
        }

        ActionOverride__mdt actionSetting = new ActionOverride__mdt();

        if(actionSettings.size()>0){
            actionSetting = actionSettings[0];
        }

        return actionSetting;
    }
}