src/objects/Address__c.object
<CustomObject>
    <description>Used to store and track addresses related to an account coming from back end systems, mainly ERPs</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Account the addresses belong to - e..g the account in ERP where you can find the addresses</description>
        <inlineHelpText>The Account the addresses belong to - e..g the account in ERP where you can find the addresses</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompanyCode__c</fullName>
        <description>Company Code or other relevant source system description</description>
        <inlineHelpText>Company Code or other relevant source system description</inlineHelpText>
        <label>CompanyCode</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_Code_2_digit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CustomerNumber__c</fullName>
        <description>The customer number identifier - e.g. ERP number in ERP</description>
        <inlineHelpText>The customer number identifier - e.g. ERP number in ERP</inlineHelpText>
        <label>Customer Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <label>Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceId__c</fullName>
        <description>SourceId of the system the address comes from</description>
        <inlineHelpText>SourceId of the system the address comes from</inlineHelpText>
        <label>SourceId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StateProvince__c</fullName>
        <label>State/Province</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Implants</fullName>
                    <label>Global DPG</label>
                </value>
                <value>
                    <fullName>All Ortho</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ATF</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
                <value>
                    <fullName>BHR</fullName>
                </value>
                <value>
                    <fullName>BHS</fullName>
                </value>
                <value>
                    <fullName>BIH</fullName>
                </value>
                <value>
                    <fullName>BLM</fullName>
                </value>
                <value>
                    <fullName>BLR</fullName>
                </value>
                <value>
                    <fullName>BLZ</fullName>
                </value>
                <value>
                    <fullName>BMU</fullName>
                </value>
                <value>
                    <fullName>BOL</fullName>
                </value>
                <value>
                    <fullName>BRA</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Discount_model__c.object
<CustomObject>
    <description>Used for storing discount models related to Contracts</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Discount Model</label>
    <nameField>
        <label>Discount Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discount Model</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Discount_row__c.object
<CustomObject>
    <fields>
        <fullName>Allowed_discount__c</fullName>
        <label>Allowed discount</label>
        <precision>4</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Discount_Model__c</fullName>
        <label>Discount Model</label>
        <referenceTo>Discount_model__c</referenceTo>
        <relationshipLabel>Discount row</relationshipLabel>
        <relationshipName>Discount_row</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OrdersOwned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Allowed_discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Allowed discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Allowed_payment_terms_months__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Allowed payment terms (months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Communication_to_Customer_Service__c</fullName>
        <label>Communication to Customer Service</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <description>Order Type for DNA</description>
        <label>Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Free Goods Order</fullName>
                </value>
                <value>
                    <fullName>Prosthetics</fullName>
                </value>
                <value>
                    <fullName>Telesales</fullName>
                </value>
                <value>
                    <fullName>Implants</fullName>
                </value>
                <value>
                    <fullName>Discount on Demand</fullName>
                </value>
                <value>
                    <fullName>PREP</fullName>
                </value>
                <value>
                    <fullName>Endodontics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_type__c</fullName>
        <inlineHelpText>Please choose the payment type by which the customer would like to pay</inlineHelpText>
        <label>Payment type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DS credit card</fullName>
                </value>
                <value>
                    <fullName>Credit card</fullName>
                </value>
                <value>
                    <fullName>Bank transfer</fullName>
                </value>
                <value>
                    <fullName>Promissory note</fullName>
                </value>
                <value>
                    <fullName>Cheque</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_type_discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Payment type discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <recordTypes>
        <fullName>Direct_global_order</fullName>
        <active>true</active>
        <label>Direct global order</label>
    </recordTypes>
    <recordTypes>
        <fullName>Free_Good_Order</fullName>
        <active>true</active>
        <label>Free Good Order</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>CompanyCode__c</fullName>
        <label>Company Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Discount Model</label>
        <referenceTo>Discount_model__c</referenceTo>
        <relationshipLabel>Price Books</relationshipLabel>
        <relationshipName>Price_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricebook_Channel__c</fullName>
        <label>Pricebook Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
                <value>
                    <fullName>Generic</fullName>
                </value>
                <value>
                    <fullName>Free Good Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ShowPricingfromMicroServiceOM__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show Pricing from Micro-Service (OM)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SourceId__c</fullName>
        <label>Source Id</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>M3</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>AX</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>BPCS</label>
                </value>
                <value>
                    <fullName>31</fullName>
                    <label>SAP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Country_Code_2_digit.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AN</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AQ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AS</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AX</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BF</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BJ</fullName>
    </customValue>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>SV</fullName>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
    </customValue>
    <customValue>
        <fullName>US</fullName>
    </customValue>
    <masterLabel>Country Code (2-digit)</masterLabel>
</GlobalValueSet>

src/classes/Test_OrderTrigger.cls
/*-------------------------------------------------------------------------------------------------------
Author: 		Ahmed LOUDRASSI (Salesforce) 20191113
Description:   	Event Trigger Helper Class
History	
20191113 	Ahmed LOUDRASSI			OrderSetAccountOwner triggers. (#)
12092019	Miguel					Added GDW Integration User creation into the setup method
18102020    Miguel                  Added testSetDiscountAllowedforTurkey User Story: #1833
12072024    Roberto                 Added Turkey support
07112024    Omar HANAFI             Fixing the test failures as part of the clean-up project
29012025    Omar HANAFI             Created test method for setShippingAndBillingAddress CPQ-117

--------------------------------------------------------------------------------------------------------*/

@isTest(seeAllData=false)
public with sharing class Test_OrderTrigger {
	/*-------------------------------------------------------------------------------------------------------
    Company: Salesforce
    Description: Setup one user for the test class
    History :
    --------------------------------------------------------------------------------------------------------*/
    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.createUsers(1, '#System: System Administrator'); 
        TestDataFactory.createGlobalIntegrationSettings(userList);
        TestDataFactory.createDefaultOrgLevelBypassPB();        
    }

    @isTest
    private static void testSetup() {
        Test.startTest();
        List<User> testUserList = [SELECT Id FROM User WHERE Alias = 'test1'];
        Test.stopTest();
		
        System.assertEquals(1, testUserList.size(), 'Expected one user');
    }

       
    @isTest
    public static void testGetAddressRecords() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' limit 1];
        List<Account> accounts = TestDataFactory.createAccounts(1, 'CIM_Account', testUser.Id);
        Address__c ad = new Address__c(Name = 'Test', Account__c= accounts.get(0).Id, CustomerNumber__c = '555', CompanyCode__c = '057',Country__c = 'SV', 
                                       Street__c = 'Street', City__c = 'City', PostalCode__c='9809', StateProvince__c = 'Province');

        insert ad;
        List<Order> orders = TestDataFactory.returnOrders(1, 'Direct_global_order', accounts);
		orders[0].ShippingAddress__c = ad.Id;
        Test.startTest();
        insert orders[0];
        Test.stopTest();
        system.assertEquals(ad.City__c ,[SELECT Id, ShippingCity FROM Order WHERE Id =: orders[0].Id LIMIT 1].ShippingCity);
        system.assertEquals(ad.Country__c ,[SELECT Id, ShippingCountry FROM Order WHERE Id =: orders[0].Id LIMIT 1].ShippingCountry);
        system.assertEquals(ad.Street__c ,[SELECT Id, ShippingStreet FROM Order WHERE Id =: orders[0].Id LIMIT 1].ShippingStreet);
        system.assertEquals(ad.PostalCode__c ,[SELECT Id, ShippingPostalCode FROM Order WHERE Id =: orders[0].Id LIMIT 1].ShippingPostalCode);
        system.assertEquals(ad.StateProvince__c ,[SELECT Id, ShippingState FROM Order WHERE Id =: orders[0].Id LIMIT 1].ShippingState);
    }

    @isTest
    public static void testSetShippingAndBillingAddressOnInsert() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        // Create test accounts
        List<Account> accounts = TestDataFactory.createAccounts(1, 'CIM_Account', testUser.Id);

        // Create initial address record
        Address__c shippingAd = new Address__c(
                Name = 'Shipping Address',
                Account__c = accounts[0].Id,
                CustomerNumber__c = '555',
                CompanyCode__c = '057',
                Country__c = 'US',
                Street__c = '123 Main St',
                City__c = 'New York',
                PostalCode__c = '10001',
                StateProvince__c = 'NY'
        );

        Address__c billingAd = new Address__c(
                Name = 'Billing Address',
                Account__c = accounts[0].Id,
                CustomerNumber__c = '555',
                CompanyCode__c = '057',
                Country__c = 'US',
                Street__c = '456 Elm St',
                City__c = 'Los Angeles',
                PostalCode__c = '90001',
                StateProvince__c = 'CA'
        );

        insert new List<Address__c>{ shippingAd, billingAd };

        // Create an Order with the shipping and billing addresses
        List<Order> orders = TestDataFactory.returnOrders(1, 'Advanced_Order', accounts);

        orders[0].RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Order' AND DeveloperName = 'Advanced_Order' LIMIT 1].Id;
        orders[0].ShippingAddress__c = shippingAd.Id;
        orders[0].BillingAddress__c = billingAd.Id;

        Test.startTest();
        insert orders[0];
        Test.stopTest();

        // Retrieve updated Order
        Order insertedOrder = [SELECT ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode, ShippingCountry,
                BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry
        FROM Order WHERE Id = :orders[0].Id LIMIT 1];

        // Assert Shipping Address fields
        system.assertEquals(shippingAd.Street__c, insertedOrder.ShippingStreet);
        system.assertEquals(shippingAd.City__c, insertedOrder.ShippingCity);
        system.assertEquals(shippingAd.StateProvince__c, insertedOrder.ShippingState);
        system.assertEquals(shippingAd.PostalCode__c, insertedOrder.ShippingPostalCode);
        system.assertEquals(shippingAd.Country__c, insertedOrder.ShippingCountry);

        // Assert Billing Address fields
        system.assertEquals(billingAd.Street__c, insertedOrder.BillingStreet);
        system.assertEquals(billingAd.City__c, insertedOrder.BillingCity);
        system.assertEquals(billingAd.StateProvince__c, insertedOrder.BillingState);
        system.assertEquals(billingAd.PostalCode__c, insertedOrder.BillingPostalCode);
        system.assertEquals(billingAd.Country__c, insertedOrder.BillingCountry);
    }

    @isTest
    public static void testSetShippingAndBillingAddressOnUpdate() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        // Create test accounts
        List<Account> accounts = TestDataFactory.createAccounts(1, 'CIM_Account', testUser.Id);

        // Create initial address record
        Address__c shippingAd = new Address__c(
                Name = 'Shipping Address',
                Account__c = accounts[0].Id,
                CustomerNumber__c = '555',
                CompanyCode__c = '057',
                Country__c = 'US',
                Street__c = '123 Main St',
                City__c = 'New York',
                PostalCode__c = '10001',
                StateProvince__c = 'NY'
        );

        Address__c billingAd = new Address__c(
                Name = 'Billing Address',
                Account__c = accounts[0].Id,
                CustomerNumber__c = '555',
                CompanyCode__c = '057',
                Country__c = 'US',
                Street__c = '456 Elm St',
                City__c = 'Los Angeles',
                PostalCode__c = '90001',
                StateProvince__c = 'CA'
        );

        insert new List<Address__c>{ shippingAd, billingAd };

        // Create an Order with the shipping and billing addresses
        List<Order> orders = TestDataFactory.returnOrders(1, 'Advanced_Order', accounts);

        orders[0].RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Order' AND DeveloperName = 'Advanced_Order' LIMIT 1].Id;
        orders[0].ShippingAddress__c = shippingAd.Id;
        orders[0].BillingAddress__c = billingAd.Id;

        insert orders[0];

        // Create a new address to simulate an update
        Address__c newShippingAd = new Address__c(
                Name = 'New Shipping Address',
                Account__c = accounts[0].Id,
                CustomerNumber__c = '555',
                CompanyCode__c = '057',
                Country__c = 'FR',
                Street__c = '789 New St',
                City__c = 'Paris',
                PostalCode__c = '75001',
                StateProvince__c = 'Île-de-France'
        );

        insert newShippingAd;

        // Update order with new shipping address
        orders[0].ShippingAddress__c = newShippingAd.Id;

        Test.startTest();
        update orders[0];
        Test.stopTest();

        // Retrieve updated order again
        Order updatedOrder = [SELECT ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode, ShippingCountry
        FROM Order WHERE Id = :orders[0].Id LIMIT 1];

        // Assert updated Shipping Address fields
        system.assertEquals(newShippingAd.Street__c, updatedOrder.ShippingStreet);
        system.assertEquals(newShippingAd.City__c, updatedOrder.ShippingCity);
        system.assertEquals(newShippingAd.StateProvince__c, updatedOrder.ShippingState);
        system.assertEquals(newShippingAd.PostalCode__c, updatedOrder.ShippingPostalCode);
        system.assertEquals(newShippingAd.Country__c, updatedOrder.ShippingCountry);
    }


    @isTest
    public static void setERPStopFlag1() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' limit 1];
        List<Account> accounts = TestDataFactory.returnAccounts(6, 'CIM_Account', testUser.Id);
        accounts[0].OneAccount_Type__c = 'Medical';
        accounts[0].Sub_Account_Type__c = 'Public Health';
        accounts[0].Country__c = 'FR';
        
        accounts[1].OneAccount_Type__c = 'Dental Support Organization';
        accounts[1].Sub_Account_Type__c = 'Large Group';
        accounts[1].Country__c = 'FR';

        accounts[2].OneAccount_Type__c = 'Education';
        accounts[2].Sub_Account_Type__c = 'Teaching Hospital';
        accounts[2].Country__c = 'FR';

        accounts[3].OneAccount_Type__c = 'Dental Clinic';
        accounts[3].Sub_Account_Type__c = 'Endodontics';
        accounts[3].Country__c = 'FR';

        accounts[4].OneAccount_Type__c = 'Dental Clinic';
        accounts[4].Sub_Account_Type__c = 'Endodontics';
        accounts[4].Country__c = 'MO';

        accounts[5].OneAccount_Type__c = 'Education';
        accounts[5].Sub_Account_Type__c = 'Teaching Hospital';
        accounts[5].Country__c = 'PL';
        insert accounts;
        List<Pricebook2> pricebooks = TestDataFactory.returnPricebooks(1, 'AAAAatest');
        pricebooks.get(0).ShowPricingfromMicroServiceOM__c = true;
        pricebooks.get(0).ShowShippingAddresses__c = true;
        pricebooks.get(0).StopOrdersinERP__c = true;
        pricebooks.get(0).SendToERPOM__c = true;
        pricebooks.get(0).SourceId__c = '2';
        pricebooks.get(0).CompanyCode__c = '116';
        pricebooks.get(0).Pricebook_Channel__c = 'Direct';
        insert pricebooks;
        
        List<Order> orders = TestDataFactory.returnOrders(7, 'Direct_global_order', accounts);
		orders[0].Pricebook2Id = pricebooks[0].Id;
        orders[0].Communication_to_Customer_Service__c= 'hello';

        orders[1].Pricebook2Id = pricebooks[0].Id;
        orders[1].AccountId = accounts[1].Id;

        orders[2].Pricebook2Id = pricebooks[0].Id;
        orders[2].AccountId = accounts[2].Id;

        orders[3].Pricebook2Id = pricebooks[0].Id;
        orders[3].AccountId = accounts[3].Id;
        orders[3].Communication_to_Customer_Service__c= 'hello';

        orders[4].Pricebook2Id = pricebooks[0].Id;
        orders[4].AccountId = accounts[3].Id;
        
        orders[5].Pricebook2Id = pricebooks[0].Id;
        orders[5].AccountId = accounts[4].Id;
        
        orders[6].Pricebook2Id = pricebooks[0].Id;
        orders[6].AccountId = accounts[5].Id;

        insert orders;
        Test.startTest();
        update orders;
        Test.stopTest();
        System.assertEquals(True, [SELECT Id, ERPStopFlag__c FROM Order WHERE Id =: orders[0].Id LIMIT 1].ERPStopFlag__c);
    }

    

    
    
    @isTest
    public static void testOrderSetAccountOwner() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' limit 1];
        List<Account> accounts1 = TestDataFactory.createAccounts(1, 'CIM_Account', testUser.Id);
        
        List<Order> orders = TestDataFactory.returnOrders(1, 'Free_Good_Order', accounts1);
        Test.startTest();
        insert orders;
        Test.stopTest();

        System.assertEquals(accounts1.get(0).OwnerId, [SELECT Id, Account_Owner__c FROM Order LIMIT 1].Account_Owner__c);
    }
    @isTest
    private static void testSetDiscountAllowedforTurkey() {      
		List<User> userList = TestDataFactory.createUsers(1, '#System: System Administrator');
        System.runAs(userList.get(0)){
        	User testUser = [SELECT Id FROM User WHERE Alias = 'test1' limit 1]; 
        	List<Pricebook2> pricebooksList = TestDataFactory.createPricebooks(1, 'TR Implants');
        	List<Product2> productsList = TestDataFactory.createProducts(1);
        	List<Discount_model__c> discountModelList = TestDataFactory.createDiscountModels(1, testUser.Id);
        	pricebooksList.get(0).Discount_Model__c = discountModelList.get(0).Id ; 
        	update pricebooksList ;   
        	List<PricebookEntry> pricebookEntriesList = TestDataFactory.createPricebookEntries(1, pricebooksList, productsList);
        	List<Discount_row__c> drs = TestDataFactory.createDiscountRows(discountModelList.get(0).Id);        
            List<Account> accountsList = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
            List<Order> ordersList = TestDataFactory.returnOrders(1, 'Free_Good_Order', accountsList);
            ordersList.get(0).Pricebook2Id = pricebooksList.get(0).Id;
            ordersList.get(0).Country__c = 'TR';
            ordersList.get(0).Order_Type__c = 'Implants';
            insert ordersList;
            List<OrderItem> orderItemsList = TestDataFactory.returnOrderItems(1, ordersList, pricebookEntriesList);        
            Test.startTest();
            insert orderItemsList;
            Order order= [SELECT Id, Allowed_Discount__c, Allowed_payment_terms_months__c, Payment_type_discount__c FROM Order WHERE Id = :ordersList.get(0).Id];
            System.assertEquals(1, order.Allowed_Discount__c); 
            order.Payment_Type__c = null ; 
            
            Test.stopTest();
            
        }
    }
    @isTest
    private static void testSetDiscountAllowedforTurkey1() {      
		List<User> userList = TestDataFactory.createUsers(1, '#System: System Administrator');
        System.runAs(userList.get(0)){
        	User testUser = [SELECT Id FROM User WHERE Alias = 'test1' limit 1]; 
        	List<Pricebook2> pricebooksList = TestDataFactory.createPricebooks(1, 'TR Implants');
        	List<Product2> productsList = TestDataFactory.createProducts(1);
        	List<Discount_model__c> discountModelList = TestDataFactory.createDiscountModels(1, testUser.Id);
        	pricebooksList.get(0).Discount_Model__c = discountModelList.get(0).Id ; 
        	update pricebooksList ;   
        	List<PricebookEntry> pricebookEntriesList = TestDataFactory.createPricebookEntries(1, pricebooksList, productsList);
        	List<Discount_row__c> drs = TestDataFactory.createDiscountRows(discountModelList.get(0).Id);        
            List<Account> accountsList = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
            List<Order> ordersList = TestDataFactory.returnOrders(1, 'Free_Good_Order', accountsList);
            ordersList.get(0).Pricebook2Id = pricebooksList.get(0).Id;
            ordersList.get(0).Country__c = 'TR';
            ordersList.get(0).Order_Type__c = 'Implants';
            insert ordersList;
            List<OrderItem> orderItemsList = TestDataFactory.returnOrderItems(1, ordersList, pricebookEntriesList);        
            Test.startTest();
            insert orderItemsList;
            
            List<Discount_row__c> drToUpdateList = new List<Discount_row__c>{};
            for (Discount_row__c dr: drs){
                dr.Discount_lever__c = 'Payment type'; 
                dr.equals__c = 'DS credit card' ;
                dr.Allowed_Discount__c = 20 ; 
                drToUpdateList.add(dr);
            }
            update drToUpdateList ;
            ordersList.get(0).User_CountryPL__c = 'Turkey' ; 
            ordersList.get(0).Payment_Type__c = 'DS credit card' ; 
            
            update ordersList[0] ;
            Test.stopTest();
            order order= [SELECT Id, Allowed_Discount__c, Allowed_payment_terms_months__c, Payment_type_discount__c FROM Order WHERE Id = :ordersList.get(0).Id];
            System.assertEquals(20, order.Payment_type_discount__c); 
        }
    }
}