src/objects/Article__c.object
<CustomObject>
    <description>Used to add multiple articles to a Case</description>
    <label>Article Number</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Article Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Implants</fullName>
                    <label>Global DPG</label>
                </value>
                <value>
                    <fullName>All Ortho</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ATF</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
                <value>
                    <fullName>BHR</fullName>
                </value>
                <value>
                    <fullName>BHS</fullName>
                </value>
                <value>
                    <fullName>BIH</fullName>
                </value>
                <value>
                    <fullName>BLM</fullName>
                </value>
                <value>
                    <fullName>BLR</fullName>
                </value>
                <value>
                    <fullName>BLZ</fullName>
                </value>
                <value>
                    <fullName>BMU</fullName>
                </value>
                <value>
                    <fullName>BOL</fullName>
                </value>
                <value>
                    <fullName>BRA</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MarginGuidance__c.object
<CustomObject>
    <description>TFUS-000005243
A Margin guidance record defines the different layers of margin thresholds per combination of product and Territory area.</description>
    <fields>
        <fullName>AreaCode__c</fullName>
        <description>Should be equaled to Account DC_ETM_Code__c (First 3 characters)</description>
        <inlineHelpText>Area Code to be matched with the account&apos;s territory area code available on the account&apos;s ETM Code (First 3 characters)</inlineHelpText>
        <label>Area Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LowerGuidance__c</fullName>
        <label>Lower Guidance</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Margin Guidances</relationshipLabel>
        <relationshipName>Margin_Guidances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UpperGuidance__c</fullName>
        <label>Upper Guidance</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Margin Guidance</label>
    <nameField>
        <displayFormat>MG#{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Margin Guidances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Direct_global_order</fullName>
        <active>true</active>
        <label>Direct global order</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LowerGuidance__c</fullName>
        <description>#5314 - Margin Guidance Calculation Process</description>
        <label>Lower Guidance (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MarginGuidance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Margin Guidance</label>
        <referenceTo>MarginGuidance__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <description>#5314 - Margin Guidance Calculation Process</description>
        <label>Margin</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UpperGuidance__c</fullName>
        <description>#5314 - Margin Guidance Calculation Process</description>
        <label>Upper Guidance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <description>#5314 - Margin Guidance Calculation Process</description>
        <label>Weight</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WeightedLowerGuidance__c</fullName>
        <description>#5314 - Margin Guidance Calculation Process</description>
        <label>Weighted Lower Guidance</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WeightedUpperGuidance__c</fullName>
        <description>#5314 - Margin Guidance Calculation Process</description>
        <label>Weighted Upper Guidance</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>MarginGuidanceCalculation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TFUS-000005314
If checked, it will enable the calculation of margin guidance upon submitting an order for approval.</description>
        <inlineHelpText>if checked, it will enable the calculation of margin guidance upon submitting an order for approval.</inlineHelpText>
        <label>Margin Guidance Calculation ?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Article__c</fullName>
        <externalId>true</externalId>
        <label>Article (SKU)</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_AssignMarginGuidanceHelper.cls
/**
 * @Author          Omar (ohanafi@salesforce.com)
 * @Description     Test class of AssignMarginGuidanceHelper
 *
 * @History
 * 20-02-2023   Omar     Created test class
 */

@isTest(seeAllData=false)
public without sharing class Test_AssignMarginGuidanceHelper {

    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.returnUsers(1, '#System: System Administrator');
        insert userList;
        TestDataFactory.createGlobalIntegrationSettings(userList);
        TestDataFactory.createDefaultOrgLevelBypassPB();

    }

    @isTest
    private static void testCalculateMargins() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        System.runAs(testUser) {

            // Create test account
            List<Account> testAccount = TestDataFactory.returnAccounts(1, 'CIM_Account', testUser.Id);
            testAccount[0].Name = 'Test Account';
            testAccount[0].DC_ETM_Code__c = 'D01';

            insert testAccount[0];

            // Create test product
            List<Product2> testProduct = TestDataFactory.returnProducts(1);
            testProduct[0].Name = 'Test Account';
            testProduct[0].Article__c = 'A1';
            testProduct[0].IsActive = true;

            insert testProduct[0];


            // Create test custom pricebook
            List<Pricebook2> testPricebook = TestDataFactory.returnPricebooks(1, 'Test Price Book');
            testPricebook[0].IsActive = true;
            testPricebook[0].MarginGuidanceCalculation__c = true;
            insert testPricebook[0];

            // Create test pricebook entry
            List<PricebookEntry> testPricebookEntry = TestDataFactory.returnPricebookEntries(1, testPricebook, testProduct);
            testPricebookEntry[0].UnitPrice = 100;
            testPricebookEntry[0].IsActive = true;

            insert testPricebookEntry[0];

            // Create test order
            List<Order> testOrder = TestDataFactory.returnOrders(1, 'Direct_global_order', testAccount);

            testOrder[0].AccountId = testAccount[0].Id;
            testOrder[0].Pricebook2Id = testPricebook[0].Id;
            testOrder[0].EffectiveDate = Date.today();
            testOrder[0].Status = 'Created';
            testOrder[0].Country__c = 'US';

            insert testOrder[0];

            // Create test order item
            List<OrderItem> testOrderItem = TestDataFactory.returnOrderItems(1, testOrder, testPricebookEntry);
            testOrderItem[0].Product2Id = testProduct[0].Id;
            testOrderItem[0].Quantity = 2;
            testOrderItem[0].UnitPrice = 100;
            testOrderItem[0].ListPrice = 100;

            insert testOrderItem[0];

            // Create test margin guidance
            MarginGuidance__c testMargin = new MarginGuidance__c(
                    Cost__c = 37,
                    AreaCode__c = 'D01',
                    Product__c = testProduct[0].Id,
                    LowerGuidance__c = 64,
                    UpperGuidance__c = 68
            );

            insert testMargin;

            Test.startTest();

            AssignMarginGuidanceHelper.calculateMargin(testOrder[0].Id);

            Test.stopTest();

            List<OrderItem> orderItems = [
                    SELECT Margin__c, Weight__c, MarginGuidance__c, WeightedMargin__c, UpperGuidance__c, LowerGuidance__c, WeightedLowerGuidance__c, WeightedUpperGuidance__c
                    FROM OrderItem
            ];

            System.assertEquals(1, orderItems.size());
            System.assertNotEquals(null, orderItems[0].MarginGuidance__c);
            System.assertEquals(1, orderItems[0].Weight__c);

        }
    }
}