src/objects/Article__c.object
<CustomObject>
    <description>Used to add multiple articles to a Case</description>
    <label>Article Number</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Article Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Location.object
<CustomObject>
    <fields>
        <fullName>ERPWarehouseId__c</fullName>
        <description>This field will be used as a reference to get Location names as what it exist in AX</description>
        <externalId>true</externalId>
        <label>ERP Warehouse Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>SourceRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>#1674</description>
        <label>Source Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Source_Record__c.CIM_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Source_Record__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Article__c</fullName>
        <externalId>true</externalId>
        <label>Article (SKU)</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <description>The Company Code as written in the GDW</description>
        <inlineHelpText>The Company Code as written in the GDW</inlineHelpText>
        <label>Company Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductItem.object
<CustomObject>
    <fields>
        <fullName>BatchNumber__c</fullName>
        <description>Batch number of the inventory item. Populated through AX/Field Service integration</description>
        <label>Batch Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERPWarehouse__c</fullName>
        <label>ERP Warehouse</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SerialNumber__c</fullName>
        <inlineHelpText>Custom Serial Number used by Field Service users</inlineHelpText>
        <label>Serial Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductRequest.object
<CustomObject>
    <fields>
        <fullName>ERPJSONVersion__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ERPJSON Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ERPOrderNumber__c</fullName>
        <description>The ERP Number from ERP - populated by integration based on Audit Logs in AX</description>
        <label>ERP Order Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERPOrderStatus__c</fullName>
        <description>Shows the status of the order in ERP - comes from the integration from Audit Logs in AX</description>
        <label>ERP Order Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERPReturnMessage__c</fullName>
        <description>Will show the return message from ERP from the integrations. Can show both success messages as well as Error messages. Info Comes from Audit Logs in AX.</description>
        <label>ERP Return Message</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SendToERPDate__c</fullName>
        <label>Send To ERP Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TF_CustomerRequestNumber__c</fullName>
        <description>Combination fields to be sent to AX. (InventTransferTable.CustomerReqNumber_DNT)

DON&apos;T ADD TO PAGE LAYOUT</description>
        <formula>WorkOrder.WorkOrderNumber&amp;&quot;|&quot;&amp;WorkOrder.SourceRecord__r.Customer_Id__c</formula>
        <label>Customer Request Number</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Source_Record__c.object
<CustomObject>
    <description>Includes Accounts from different sources mapped to one golden account. Fully integrated ( Read Only for all users)</description>
    <fields>
        <fullName>Company_Code__c</fullName>
        <label>Company Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <label>Customer Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Id__c</fullName>
        <label>Location Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Source Record</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>DescribeWhatHasBeenDone__c</fullName>
        <label>Describe what has been done</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ERPJSONVersion__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ERPJSON Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ERPOrderNumber__c</fullName>
        <description>The ERP Number from ERP - populated by integration based on Audit Logs in AX</description>
        <label>ERP Order Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERPOrderStatus__c</fullName>
        <description>Shows the status of the order in ERP - comes from the integration from Audit Logs in AX</description>
        <label>ERP Order Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERPReturnMessage__c</fullName>
        <description>Will show the return message from ERP from the integrations. Can show both success messages as well as Error messages. Info Comes from Audit Logs in AX.</description>
        <label>ERP Return Message</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SendToERPDate__c</fullName>
        <label>Send To ERP Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ServiceType__c</fullName>
        <description>Used to describe the service code based on AX Service Types</description>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ServiceType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SourceRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CIM Record updated through the Case</description>
        <label>Source Record</label>
        <referenceTo>Source_Record__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrderLineItem.object
<CustomObject>
    <fields>
        <fullName>ServiceType__c</fullName>
        <description>Used to describe the service code based on AX Service Types</description>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ServiceType</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/ServiceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2W</fullName>
        <label>Recall - Parts Charged</label>
    </customValue>
    <customValue>
        <fullName>3P</fullName>
        <label>3rd Party Tech</label>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
        <label>Chargeable call with call out</label>
    </customValue>
    <customValue>
        <fullName>CL</fullName>
        <label>Calibration – compliance</label>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
        <label>Contract</label>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
        <label>Do and Charge Call - No call out</label>
    </customValue>
    <customValue>
        <fullName>FS</fullName>
        <label>Free Service</label>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
        <label>Installation</label>
    </customValue>
    <customValue>
        <fullName>IR</fullName>
        <label>Intego Replacement</label>
    </customValue>
    <customValue>
        <fullName>IW</fullName>
        <label>Internal Work</label>
    </customValue>
    <customValue>
        <fullName>PH</fullName>
        <label>Phone or Remote Access Support</label>
    </customValue>
    <customValue>
        <fullName>PM</fullName>
        <label>Preventative Maintenance</label>
    </customValue>
    <customValue>
        <fullName>PW</fullName>
        <label>Parts Warranty Only</label>
    </customValue>
    <customValue>
        <fullName>TU</fullName>
        <label>Technical Unavailable (Not used after test)</label>
    </customValue>
    <customValue>
        <fullName>WA</fullName>
        <label>Warranty</label>
    </customValue>
    <customValue>
        <fullName>WS</fullName>
        <label>Workshop</label>
    </customValue>
    <customValue>
        <fullName>ZL</fullName>
        <label>SalesSupport</label>
    </customValue>
    <description>Custom Picklist value that will be used in Salesforce-AX integration for the field service</description>
    <masterLabel>Service Type</masterLabel>
</GlobalValueSet>

src/classes/FieldServiceCalloutERP.cls
/*-------------------------------------------------------------------------------------------------------
Author:             Roberto Narbona 20220824
Description:    This is a controller for Biztalk integration.
History         Tobas Nygren 20220905: Added LocationId, WorkOrderNumber and Discount (Products Consumed) to query for additional info sent to AX.
                Tobias Nygren 20220920: Added Service_Type__c on Work Order Header, and removed Service_Type__c on WorkOrderLineItem level.
                Tobias Nygren 20221014: Replaced Duration for Quantity on Work Order Line Item.
                Roberto Narbona 29221028: Added product name, Asset Serial number and order description in workOrdersToSend query.
--------------------------------------------------------------------------------------------------------*/

public with sharing class FieldServiceCalloutERP {

    @AuraEnabled
    public static String doFieldServiceCalloutERP( List<Id> recordIds ) {
        //This method is actually doing the callout. 
        String objectType = String.valueOf(recordIds[0].getSObjectType());
        String query = '';
        List< WorkOrder > workOrdersToSend = new List<WorkOrder>();
        List< ProductRequest > productRequestsToSend = new List<ProductRequest>();
        if(objectType == 'WorkOrder'){
            workOrdersToSend = [SELECT Id, ERPJSONVersion__c, WorkOrderNumber, ServiceType__c, SourceRecord__r.Company_Code__c , SourceRecord__r.Customer_Id__c, SourceRecord__r.Location_Id__c, CurrencyIsoCode, EndDate, Status, Describewhathasbeendone__c, WorkType.Name, Asset.Name, Asset.Product2.Article__c, Asset.Product2.Name, Asset.SerialNumber, Description, (SELECT Id, CurrencyIsoCode, Discount, Quantity,  WorkOrderId, Product2.Article__c, Product2.Company_Code__c FROM WorkOrderLineItems ), (SELECT Id, CurrencyIsoCode, QuantityConsumed, Discount, WorkOrderId, Product2.Article__c, Product2.Company_Code__c, ProductItem.SerialNumber__c, ProductItem.BatchNumber__c, ProductItem.Location.ERPWarehouseId__c, ProductItem.ERPWarehouse__c FROM ProductsConsumed) FROM WorkOrder WHERE id IN: recordIds];
        }
        if(objectType == 'ProductRequest'){
            productRequestsToSend = [ SELECT Id, ERPJSONVersion__c, ProductRequestNumber, TF_CustomerRequestNumber__c, DestinationLocation.ERPWarehouseId__c, SourceLocation.ERPWarehouseId__c, DestinationLocation.ParentLocation.ERPWarehouseId__c, (SELECT Id, ProductRequestLineItemNumber, ParentId, Product2.Article__c, Product2.Company_Code__c, QuantityRequested, Status FROM ProductRequestLineItems) FROM ProductRequest WHERE id IN: recordIds ];
        }

        
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        if(objectType == 'WorkOrder'){
            request.setEndpoint('callout:FSBiztalkIntegrationWorkOrder');
        }
        if(objectType == 'ProductRequest'){
            request.setEndpoint('callout:FSBiztalkIntegrationProductRequest');
        }
        
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json;charset=UTF-8');
        // Set the body as a JSON object
        if(objectType == 'WorkOrder'){
            Map<String, List<WorkOrder>> mapforERP = new Map<String, List<WorkOrder>> ();
            mapforERP.put('records', workOrdersToSend);
            request.setBody(JSON.serialize(mapforERP, false));
        }
        if(objectType == 'ProductRequest'){
            Map<String, List<ProductRequest>> mapforERP = new Map<String, List<ProductRequest>> ();
            mapforERP.put('records', productRequestsToSend);
            request.setBody(JSON.serializePretty(mapforERP, false));
        }

        if(!Test.isRunningTest()){
            HttpResponse response = http.send(request);
            return response.getBody();
        } else {
            String fakeResponse = 'FaekeResponse';
            return fakeResponse;
        }
        
    }

    @AuraEnabled
    public static Boolean updateRecord( List<Id> recordIds, string message) {
        //This method is actually updating a field in the object after callout happened.
        List< WorkOrder > workOrdersToSend = new List<WorkOrder>();
        List< ProductRequest > productRequestsToSend = new List<ProductRequest>();
        try {
            String objectType = String.valueOf(recordIds[0].getSObjectType());
            for(String recId : recordIds) {
                if(objectType == 'WorkOrder'){
                    WorkOrder workOrderToUpdate = new WorkOrder(ID = recId , ERPReturnMessage__c = message , SendToERPDate__C = Datetime.Parse(Datetime.now().format()));
                    workOrdersToSend.add(workOrderToUpdate);
                }
                if(objectType == 'ProductRequest'){
                    ProductRequest productRequestToUpdate = new ProductRequest(ID = recId , ERPReturnMessage__c = message , SendToERPDate__C = Datetime.Parse(Datetime.now().format()));
                    productRequestsToSend.add(productRequestToUpdate);
                }
            }
            if (workOrdersToSend.isempty() == false){
                update workOrdersToSend;
            }
            if (productRequestsToSend.isempty() == false){
                update productRequestsToSend;
            }            
            return(true);
        }
        catch (Exception e) {
            DebugLog.addException(e, 'FieldServiceCalloutERP.updateRecord');
            throw new AuraHandledException(e.getMessage());    
        }
    }


    @AuraEnabled
    public static Boolean updateJSONVersion( List<Id> recordIds) {
        List< WorkOrder > workOrdersToUpdate = new List<WorkOrder>();
        List< WorkOrder > updatedWorkOrders = new List<WorkOrder>();

        List< ProductRequest > productRequestsToUpdate = new List<ProductRequest>();
        List< ProductRequest > updatedProductRequests = new List<ProductRequest>();

        try {
            String objectType = String.valueOf(recordIds[0].getSObjectType());
            if(objectType == 'WorkOrder'){
                workOrdersToUpdate = [ SELECT Id, ERPJSONVersion__c FROM WorkOrder WHERE id IN: recordIds];
                for( WorkOrder wO : workOrdersToUpdate){
                    WorkOrder orderToAdd = new WorkOrder( Id = wO.Id, ERPJSONVersion__c = wO.ERPJSONVersion__c == null ? 1 : wO.ERPJSONVersion__c + 1, ERPReturnMessage__c = '' , ERPOrderStatus__c = '', ERPOrderNumber__c = '');
                    updatedWorkOrders.add(orderToAdd);
                }
                update updatedWorkOrders;

            }
            if(objectType == 'ProductRequest'){
                productRequestsToUpdate = [ SELECT Id, ERPJSONVersion__c FROM ProductRequest WHERE id IN: recordIds];
                for( ProductRequest pR : productRequestsToUpdate){
                    ProductRequest prodRequestToAdd = new ProductRequest( Id = pR.Id, ERPJSONVersion__c = pR.ERPJSONVersion__c == null ? 1 : pR.ERPJSONVersion__c + 1, ERPReturnMessage__c = '', ERPOrderStatus__c = '', ERPOrderNumber__c = '');
                    updatedProductRequests.add(prodRequestToAdd);
                }
                update updatedProductRequests;
            }

            return(true);
        }
        catch (Exception e) {
            DebugLog.addException(e, 'FieldServiceCalloutERP.updateRecord');
            throw new AuraHandledException(e.getMessage());    
        }
    }
}