src/objects/Article__c.object
<CustomObject>
    <description>Used to add multiple articles to a Case</description>
    <label>Article Number</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Article Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BOM__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Bill of Material</relationshipLabel>
        <relationshipName>Bill_of_Material</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_bundle__c</fullName>
        <label>Product bundle</label>
        <referenceTo>Product_bundle__c</referenceTo>
        <relationshipLabel>Bill of Material</relationshipLabel>
        <relationshipName>Bill_of_Material</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Bill of Material</label>
    <nameField>
        <label>Bill of Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill of Material</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/cadmus_core__Actionable__c.object
<CustomObject>
    <label>Actionable</label>
    <nameField>
        <label>Actionable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actionables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cadmus_core__Data_Source__c.object
<CustomObject>
    <fields>
        <fullName>cadmus_core__CustomerDataSourceId__c</fullName>
        <formula>IF( ISBLANK(cadmus_core__Migrated_Customer_Data_Source_Id__c)
,IF(
    ISBLANK(cadmus_core__Migrated_Customer_Data_Source_Id_2__c)
    , $Organization.Id + &apos;_&apos; + Id
    , cadmus_core__Migrated_Customer_Data_Source_Id_2__c 
  )
, cadmus_core__Migrated_Customer_Data_Source_Id__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Data Source Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cadmus_core__Image_Name__c</fullName>
        <inlineHelpText>The name of the image you want to include. This is dependent of the image source.
Attachment: Title (File Name)
Document: Unique name
Files: Name</inlineHelpText>
        <label>Image Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Data Source</label>
    <nameField>
        <label>Data Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Article__c</fullName>
        <externalId>true</externalId>
        <label>Article (SKU)</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_bundle__c.object
<CustomObject>
    <label>Product bundle</label>
    <nameField>
        <label>Product bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product bundle</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>QuoteProductBundle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Line Bundle</label>
        <referenceTo>QuoteProductBundle__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteProductBundle__c.object
<CustomObject>
    <description>TFUS-000004537 
Junction object to tie Quotes and Bundles/Promotions/Offers together. Used for Bundle and promotion selling - guided selling and structured pricing around promotions</description>
    <fields>
        <fullName>ProductBundle__c</fullName>
        <label>Product Bundle</label>
        <referenceTo>Product_bundle__c</referenceTo>
        <relationshipName>Quote_Product_Bundles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipName>Quote_Product_Bundles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line Bundle</label>
    <nameField>
        <displayFormat>QLB-{0000}</displayFormat>
        <label>Quote Line Bundle #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Bundles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PDFbutlerGetBomName.cls
/**
* This a class to match Story TFUS-000006924
*
* @author Roberto
*/
global inherited sharing class PDFbutlerGetBomName implements cadmus_core.AbstractBeforeActionable {
    /* This an APEX class to meet requirements for PDF format requested in story TFUS-000006924*/
	global void execute(cadmus_core__Actionable__c actionable,
                        Id docConfig,
                        Id objectId,
                        Map<String, Object> inputMap,
    cadmus_core.ConvertController.ConvertDataModel cdm) {
        /* This an APEX class to meet requirements for PDF format requested in story TFUS-000006924*/

        Map<String,Map<String,String>> periodValues=new Map<String, Map<String,String>>();
        List<Map<String, String>> rowsDataList = new List<Map<String, String>>();
        
        //Get DataSources
        final cadmus_core__Data_Source__c dss = [SELECT Id, Name, cadmus_core__CustomerDataSourceId__c,cadmus_core__Image_Name__c
                                                 From cadmus_core__Data_Source__c
                                                 WHERE Name = 'GetBomNameWithAPEX'
                                                 WITH USER_MODE
                                                 LIMIT 1                                                 
                                                ];

        rowsDataList = new List<Map<String, String>>();
		Quote quoteInfo = new Quote();
        quoteInfo = [SELECT id,  (SELECT Id,ProductBundle__r.Id FROM Quote_Product_Bundles__r), 
                     (SELECT Id, Product2Id, QuoteProductBundle__r.ProductBundle__c, Product2.Name, Product2.Article__c, Product2.Description, Quantity, UnitPrice, TotalPrice FROM QuoteLineItems)
					FROM quote
					WHERE Id =:objectId
                    WITH USER_MODE];
        final List<String> bundleIds = new List<String>();
        for(QuoteProductBundle__c bundle : quoteInfo.Quote_Product_Bundles__r){
            bundleIds.add(bundle.ProductBundle__r.Id);
        }
        List<BOM__c> materials = new List<BOM__c>();
        materials = [SELECT Id, Product_bundle__c, Product__c, Product__r.Article__c, Product__r.Name, Name FROM BOM__c WHERE Product_bundle__c IN: bundleIds WITH USER_MODE];
        periodValues=new Map<String, Map<String,String>>();
        Map<String, String> recordRow = new Map<String, String>();

        for(QuoteLineItem qli : quoteInfo.QuoteLineItems){
            recordRow=periodValues.get(qli.Id);
            if(recordRow==null) {
                recordRow=new Map<String,String>();
                recordRow.put('Id', qli.Id);
                rowsDataList.add(recordRow);
            }
            if(qli.QuoteProductBundle__r.ProductBundle__c != null){
                //get name
                final string matName = getMaterialName(qli, materials);
                recordRow.put('APEXBomName', matName);
            }
            

            recordRow.put('APEXProdSKU', qli.Product2.Article__c);
            recordRow.put('APEXProdName', qli.Product2.Name);
            recordRow.put('APEXProdDescription', qli.Product2.Description);
            recordRow.put('APEXProdQuantity', String.valueOf(qli.Quantity));
            recordRow.put('APEXProdSalesPrice', String.valueOf(qli.UnitPrice));
            recordRow.put('APEXProdTotalPrice', String.valueOf(qli.TotalPrice));
            periodValues.put(qli.Id,recordRow);
		}
        inputMap.put(dss.Id,rowsDataList);
    }

    /* this is a method to get bill material name */
    public static String getMaterialName(QuoteLineItem qli, List<BOM__c> materials) {
        string matName = '';
        for(BOM__c material : materials	){
            if(qli.QuoteProductBundle__r.ProductBundle__c == material.Product_bundle__c && qli.Product2Id == material.Product__c){
                matName = material.Name;
            } 
        }
        return matName;
    }
}