src/objects/BOM__c.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Discount</label>
        <precision>11</precision>
        <scale>8</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Bill of Material</relationshipLabel>
        <relationshipName>Bill_of_Material</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_bundle__c</fullName>
        <label>Product bundle</label>
        <referenceTo>Product_bundle__c</referenceTo>
        <relationshipLabel>Bill of Material</relationshipLabel>
        <relationshipName>Bill_of_Material</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Row_price__c</fullName>
        <formula>Quantity__c *  Unit_price__c *(1- Discount__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Row price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Bill of Material</label>
    <nameField>
        <label>Bill of Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill of Material</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Area__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Abutment Sales - Customized - GoldHue</fullName>
                </value>
                <value>
                    <fullName>Abutment Sales - Customized - Titanium</fullName>
                </value>
                <value>
                    <fullName>Abutment Sales - Customized - Zirconia</fullName>
                </value>
                <value>
                    <fullName>Abutment Sales - Stock</fullName>
                </value>
                <value>
                    <fullName>Bellovac ABT</fullName>
                </value>
                <value>
                    <fullName>Cresco</fullName>
                </value>
                <value>
                    <fullName>Facilitate</fullName>
                </value>
                <value>
                    <fullName>Fatcher</fullName>
                </value>
                <value>
                    <fullName>Implant Sales</fullName>
                </value>
                <value>
                    <fullName>KilRoid</fullName>
                </value>
                <value>
                    <fullName>Kits (Cath, Hydro, Ready)</fullName>
                </value>
                <value>
                    <fullName>LoFric</fullName>
                </value>
                <value>
                    <fullName>LoFric Primo</fullName>
                </value>
                <value>
                    <fullName>Medena</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Other Catheter Sales</fullName>
                </value>
                <value>
                    <fullName>Prosthetic Restorative Components</fullName>
                </value>
                <value>
                    <fullName>Prosthetic Restorative Instruments</fullName>
                </value>
                <value>
                    <fullName>Sangvia</fullName>
                </value>
                <value>
                    <fullName>Surgical Components &amp; Instruments</fullName>
                </value>
                <value>
                    <fullName>Vastrip</fullName>
                </value>
                <value>
                    <fullName>Wound Drains</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>GET</fullName>
        <active>true</active>
        <businessProcess>GET</businessProcess>
        <label>X DO NOT USE 2t</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>ObjectTypeUseOM__c</fullName>
        <label>Object Type Use(OM)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ShowPricingfromMicroServiceOM__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show Pricing from Micro-Service (OM)</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product_bundle__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Internal Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Product bundle</relationshipLabel>
        <relationshipName>Product_bundle</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_price__c</fullName>
        <label>Total price</label>
        <summarizedField>BOM__c.Row_price__c</summarizedField>
        <summaryForeignKey>BOM__c.Product_bundle__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Product bundle</label>
    <nameField>
        <label>Product bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product bundle</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QuoteProductBundle__c.object
<CustomObject>
    <description>TFUS-000004537 
Junction object to tie Quotes and Bundles/Promotions/Offers together. Used for Bundle and promotion selling - guided selling and structured pricing around promotions</description>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Quote Line Bundle</label>
    <nameField>
        <displayFormat>QLB-{0000}</displayFormat>
        <label>Quote Line Bundle #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Bundles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AddBundles.cls
/*-------------------------------------------------------------------------------------------------------
Author: 	    	Roberto Narbona 20220824
Description:   	This is a controller for addBundles LWC
History	

--------------------------------------------------------------------------------------------------------*/


public with sharing class AddBundles {


    @AuraEnabled
    public static List<Product_bundle__c> getPricebookBundles(String pricebookId) {
        
        List<Product_bundle__c> bundles = new List<Product_bundle__c>();
        bundles = [ SELECT Id, Total_price__c, Name, CurrencyIsoCode, Description__c, (SELECT Name, Quantity__c, Product__r.Name, Row_price__c, Id, Discount__c, CurrencyIsoCode FROM Bill_of_Material__r), (SELECT Id, ContentDocumentId FROM AttachedContentDocuments ORDER BY CreatedDate DESC NULLS FIRST)  FROM Product_bundle__c WHERE Price_Book__c =: pricebookId AND Active__c = true];
        return(bundles);
    }

    @AuraEnabled(cacheable=true)
    public static List<PriceBook2> getPriceBooks() {
        try {
            Map<Id, Pricebook2> pricebookMap = new Map<Id, Pricebook2>([
                SELECT Id, Name, ShowPricingfromMicroServiceOM__c  
                FROM Pricebook2 
                WHERE IsActive = true AND Name != 'Standard Price Book' AND Name != 'Sirona Products' AND (ObjectTypeUseOM__c = 'Opportunity' OR ObjectTypeUseOM__c = '')
                ORDER BY Name ASC
            ]);

            List<Pricebook2> pbWithReadAccessList = new List<Pricebook2>();
            for (UserRecordAccess recordAccess : [
                SELECT RecordId 
                FROM UserRecordAccess 
                WHERE UserId= :UserInfo.getUserId() AND HasReadAccess = true AND RecordId IN :pricebookMap.keySet() 
                LIMIT 200
            ]) {
                pbWithReadAccessList.add(pricebookMap.get(recordAccess.RecordId));
            }
            pbWithReadAccessList.sort();

            return pbWithReadAccessList;
        }
        catch (Exception e) {
            DebugLog.addException(e, 'AddBundles.getPriceBooks');
            throw new AuraHandledException(e.getMessage());    
        }
    }

    @AuraEnabled
    public static Boolean updateRecord(String quoteId, String pricebookId) {
        try {
            Quote quoteToUpdate = new Quote();
            quoteToUpdate.Id = quoteId;
            quoteToUpdate.Pricebook2Id = pricebookId;
            update quoteToUpdate;
            return(false);
        }
        catch (Exception e) {
            DebugLog.addException(e, 'AddBundles.updateRecord');
            throw new AuraHandledException(e.getMessage());    
        }
    }

    @AuraEnabled
    public static Boolean insertQuoteBundles(List<QuoteProductBundle__c> quoteBundlesToInsert) {
        try {
            insert quoteBundlesToInsert;
            return(true);
        }
        catch (Exception e) {
            DebugLog.addException(e, 'AddBundles.insertQuoteBundles');
            throw new AuraHandledException(e.getMessage());    
        }
    }
}