src/objects/BOM__c.object
<CustomObject>
    <fields>
        <fullName>Product_bundle__c</fullName>
        <label>Product bundle</label>
        <referenceTo>Product_bundle__c</referenceTo>
        <relationshipLabel>Bill of Material</relationshipLabel>
        <relationshipName>Bill_of_Material</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <description>Controls the sorting order of the quote line items during their generation for a quote</description>
        <inlineHelpText>Controls the sorting order of the quote line items during their generation for a quote</inlineHelpText>
        <label>Sort Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bill of Material</label>
    <nameField>
        <label>Bill of Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill of Material</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Lightning_Pipeline_Opportunity</fullName>
        <active>true</active>
        <businessProcess>Lightning Sales</businessProcess>
        <description>Lightning Pipeline Opportunity</description>
        <label>Lightning Pipeline Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product_bundle__c.object
<CustomObject>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Product bundle</relationshipLabel>
        <relationshipName>Product_bundle</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product bundle</label>
    <nameField>
        <label>Product bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product bundle</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QuoteProductBundle__c.object
<CustomObject>
    <description>TFUS-000004537 
Junction object to tie Quotes and Bundles/Promotions/Offers together. Used for Bundle and promotion selling - guided selling and structured pricing around promotions</description>
    <fields>
        <fullName>ProductBundle__c</fullName>
        <label>Product Bundle</label>
        <referenceTo>Product_bundle__c</referenceTo>
        <relationshipName>Quote_Product_Bundles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipName>Quote_Product_Bundles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line Bundle</label>
    <nameField>
        <displayFormat>QLB-{0000}</displayFormat>
        <label>Quote Line Bundle #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Bundles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_QuoteProductBundleTriggerHandler.cls
@isTest
/*-------------------------------------------------------------------------------------------------------
Author:         Houssam ADIB (Salesforce)
Description:    Test class covering
                QuoteProductBundleTrigger,QuoteProductBundleTriggerHandler,QuoteProductBundleTriggerHelper
History
2022-09-01      Houssam ADIB    Create New Test Class
----------------------------------------------------------------------------------------*/
public with sharing class Test_QuoteProductBundleTriggerHandler {

    /*------------------------------------------------------------
    Description:    Test setup
    ------------------------------------------------------------*/
    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.createUsers(1, '#System: System Administrator');
        TestDataFactory.createGlobalIntegrationSettings(userList);
        TestDataFactory.createDefaultOrgLevelBypassPB();
    }

    /*------------------------------------------------------------
    Description:    Test the Synchronization between a product bundle and related child quote line items
    ------------------------------------------------------------*/
    @isTest
    private static void testQuoteLinesBundlesSynchronization()
    {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {

            List<Account> acc = TestDataFactory.createAccounts(1, 'Non_ERP_Account' ,testUser.Id);
            List<Opportunity> opp = TestDataFactory.returnOpportunities(1, 'Lightning_Pipeline_Opportunity', testUser.Id);
            opp[0].CurrencyIsoCode = 'USD';
            opp[0].AccountId = acc[0].Id;
            insert opp;

            // Product Bundle
            List<Pricebook2> pricebook = TestDataFactory.createPricebooks(1,'test PB');
            List<Product_bundle__c> bundles = TestDataFactory.returnBundles(1);
            bundles[0].Price_Book__c = pricebook[0].Id;
            bundles[0].CurrencyIsoCode = 'USD';
            insert bundles;

            // Products
            List<Product2> products = TestDataFactory.createProducts(3);
            List<Bom__c> boms = TestDataFactory.returnBOMs(3,bundles[0].Id,products);
            Integer i=1;
            for (BOM__c bom : boms)
            {
                bom.SortOrder__c = i;
                i++;
            }
            insert boms;
            List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntries(3, pricebook, products);
            // Quote
            List<Quote> quote = TestDataFactory.returnQuotes(1);
            quote[0].OpportunityId = opp[0].Id;
            quote[0].Pricebook2Id = pricebook[0].Id;
            insert quote;

            // Quote Line Bundle
            List<QuoteProductBundle__c> quoteProductBundle = TestDataFactory.returnQuoteProductBundle(1);
            quoteProductBundle[0].Quote__c = quote[0].Id;
            quoteProductBundle[0].ProductBundle__c = bundles[0].Id;

            TestDataFactory.insertQuoteLineItems(products,quote[0],pricebookEntries);

            Quote quoteLinesBefore = [SELECT Id,(SELECT Id FROM QuoteLineItems) FROM Quote WHERE Id =:quote[0].Id];
            System.assertEquals(3, quoteLinesBefore.QuoteLineItems.size(), 'Wrong number of Quote has line items before starting the test');

            Test.startTest();
            insert quoteProductBundle;
            Test.stopTest();

            Quote quoteLinesAfterInsert = [SELECT Id,(SELECT Id,SortOrder FROM QuoteLineItems) FROM Quote WHERE Id =:quote[0].Id];
            System.assertEquals(12, quoteLinesAfterInsert.QuoteLineItems.size(), 'No quote line items has been generated after quote line insertion');

            delete quoteProductBundle;

            Quote quoteLinesAfterDelete = [SELECT Id,(SELECT Id FROM QuoteLineItems) FROM Quote WHERE Id =:quote[0].Id];
            System.assertEquals(3, quoteLinesAfterDelete.QuoteLineItems.size(), 'Quote lines items weren\'t deleted after quote line bundle deletion');

        }
    }

}