src/objects/BOM__c.object
<CustomObject>
    <fields>
        <fullName>Product_bundle__c</fullName>
        <label>Product bundle</label>
        <referenceTo>Product_bundle__c</referenceTo>
        <relationshipLabel>Bill of Material</relationshipLabel>
        <relationshipName>Bill_of_Material</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <description>Controls the sorting order of the quote line items during their generation for a quote</description>
        <inlineHelpText>Controls the sorting order of the quote line items during their generation for a quote</inlineHelpText>
        <label>Sort Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bill of Material</label>
    <nameField>
        <label>Bill of Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill of Material</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/cadmus_core__Actionable__c.object
<CustomObject>
    <fields>
        <fullName>cadmus_core__Doc_Config__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Doc Config</label>
        <referenceTo>cadmus_core__Doc_Config__c</referenceTo>
        <relationshipLabel>Actionables</relationshipLabel>
        <relationshipName>Actionables</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Actionable</label>
    <nameField>
        <label>Actionable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actionables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cadmus_core__Data_Source__c.object
<CustomObject>
    <fields>
        <fullName>cadmus_core__Type__c</fullName>
        <inlineHelpText>Select the correct type the SOQL will return. E.g. When using LIMIT 1 at the end of the SOQL it should always be &apos;Single sObject&apos;, otherwise select &apos;List of sObjects&apos;.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>List of sObjects</fullName>
                    <default>true</default>
                    <label>List of sObjects</label>
                </value>
                <value>
                    <fullName>Single sObject</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Data Source</label>
    <nameField>
        <label>Data Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cadmus_core__Doc_Config__c.object
<CustomObject>
    <fields>
        <fullName>cadmus_core__Document_Title__c</fullName>
        <inlineHelpText>Mergefields can be used to construct a dynamic document title</inlineHelpText>
        <label>Document Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Doc Config</label>
    <nameField>
        <label>Document Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doc Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>GET</fullName>
        <active>true</active>
        <businessProcess>GET</businessProcess>
        <label>X DO NOT USE 2t</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lightning_Pipeline_Opportunity</fullName>
        <active>true</active>
        <businessProcess>Lightning Sales</businessProcess>
        <description>Lightning Pipeline Opportunity</description>
        <label>Lightning Pipeline Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product_bundle__c.object
<CustomObject>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Product bundle</relationshipLabel>
        <relationshipName>Product_bundle</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product bundle</label>
    <nameField>
        <label>Product bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product bundle</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QuoteProductBundle__c.object
<CustomObject>
    <description>TFUS-000004537 
Junction object to tie Quotes and Bundles/Promotions/Offers together. Used for Bundle and promotion selling - guided selling and structured pricing around promotions</description>
    <fields>
        <fullName>ProductBundle__c</fullName>
        <label>Product Bundle</label>
        <referenceTo>Product_bundle__c</referenceTo>
        <relationshipName>Quote_Product_Bundles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipName>Quote_Product_Bundles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line Bundle</label>
    <nameField>
        <displayFormat>QLB-{0000}</displayFormat>
        <label>Quote Line Bundle #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Bundles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PDFbutlerGetBomNameTest.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Roberto
Description:    Test class covering
                PDFbutlerGetBomName
                
History
20240812     Roberto    Create New Test Class
----------------------------------------------------------------------------------------*/
@isTest
public with sharing class PDFbutlerGetBomNameTest {
    /*------------------------------------------------------------
    Description:    Test setup
    ------------------------------------------------------------*/
    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        final List<User> userList = TestDataFactory.createUsers(1, '#System: System Administrator');
        TestDataFactory.createGlobalIntegrationSettings(userList);
        TestDataFactory.createDefaultOrgLevelBypassPB();
    }
    /*------------------------------------------------------------
    Description:    Checking PDF butler actionable

    ------------------------------------------------------------*/
    @isTest
    private static void testGetBomNames()
    {
        final User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            final List<Account> acc = TestDataFactory.createAccounts(1, 'Non_ERP_Account' ,testUser.Id);
            final List<Opportunity> opp = TestDataFactory.returnOpportunities(1, 'Lightning_Pipeline_Opportunity', testUser.Id);
            opp[0].CurrencyIsoCode = 'USD';
            opp[0].AccountId = acc[0].Id;
            insert opp;

            // Product Bundle
            final List<Pricebook2> pricebook = TestDataFactory.createPricebooks(1,'test PB');
            final List<Product_bundle__c> bundles = TestDataFactory.returnBundles(1);
            bundles[0].Price_Book__c = pricebook[0].Id;
            bundles[0].CurrencyIsoCode = 'USD';
            insert bundles;

            // Products
            final List<Product2> products = TestDataFactory.createProducts(3);
            final List<Bom__c> boms = TestDataFactory.returnBOMs(3,bundles[0].Id,products);
            Integer ind=1;
            for (BOM__c bom : boms)
            {
                bom.SortOrder__c = ind;
                ind++;
            }
            insert boms;
            final List<PricebookEntry> pricebookEntries = TestDataFactory.createPricebookEntries(3, pricebook, products);
            // Quote
            final List<Quote> quote = TestDataFactory.returnQuotes(1);
            quote[0].OpportunityId = opp[0].Id;
            quote[0].Pricebook2Id = pricebook[0].Id;
            insert quote;

            // Quote Line Bundle
            final List<QuoteProductBundle__c> quoteProdBundle = TestDataFactory.returnQuoteProductBundle(1);
            quoteProdBundle[0].Quote__c = quote[0].Id;
            quoteProdBundle[0].ProductBundle__c = bundles[0].Id;

            TestDataFactory.insertQuoteLineItems(products,quote[0],pricebookEntries);
            insert quoteProdBundle;
            
            //2 Create docConfig
            final cadmus_core__Doc_Config__c doc_config = new cadmus_core__Doc_Config__c();
            doc_config.cadmus_core__Document_Title__c = 'TEST';
            doc_config.Name = 'TEST_DOC_CONFIG';
            doc_config.RecordTypeId = Schema.SObjectType.cadmus_core__Doc_Config__c.getRecordTypeInfosByName().get('Main Word Document').getRecordTypeId();
            insert doc_config;
            
            final cadmus_core__Data_Source__c dataSource = new cadmus_core__Data_Source__c();
            dataSource.Name = 'GetBomNameWithAPEX';
            dataSource.RecordTypeId = Schema.SObjectType.cadmus_core__Data_Source__c.getRecordTypeInfosByName().get('KEYVALUE').getRecordTypeId();
            dataSource.cadmus_core__Type__c = 'List of sObjects';
            insert dataSource;
            
            //3 Create Actionable
            final cadmus_core__Actionable__c actionable = new cadmus_core__Actionable__c();
            actionable.Name = 'TEST_ACTIONABLE';
            actionable.RecordTypeId = Schema.SObjectType.cadmus_core__Actionable__c.getRecordTypeInfosByName().get('Run Class').getRecordTypeId();
            insert actionable;
            //4 Create InputMap -> two vars recordId,userId
            final Map <String,Object> inputMap = new Map <String,Object> {
                'recordId' => quote[0].Id,
                'userId' => UserInfo.getUserId()
            }; 
            
                
            final cadmus_core.ConvertController.ConvertDataModel cdm = new cadmus_core.ConvertController.ConvertDataModel();
            cdm.docConfigId = doc_config.Id;
            cdm.objectId = quote[0].Id;
            
            Test.startTest();
            final PDFbutlerGetBomName instance = new PDFbutlerGetBomName();
            instance.execute(actionable, doc_config.Id, quote[0].Id, inputMap, cdm);
            Test.stopTest();
            System.assert(inputMap.containsKey(dataSource.Id), 'InputMap should contain the data source ID');

        }
    }

}