src/objects/CAHomeReportLink__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ReportURL__c</fullName>
        <label>Report URL</label>
        <type>Url</type>
    </fields>
    <label>Clinical Affairs Home Report Link</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Full_Name__c</fullName>
        <description>Used instead of having to add First and Last Name when grouping in report</description>
        <formula>FirstName &amp; &quot; &quot; &amp; LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Formula field</inlineHelpText>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CventEvents__Attendee__c.object
<CustomObject>
    <description>Represents the attendee of an event.</description>
    <fields>
        <fullName>CventEvents__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Events Participation</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CventEvents__Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Number</label>
        <referenceTo>CventEvents__Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CventEvents__RegistrationType__c</fullName>
        <label>Registration Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CventEvents__Event__c.object
<CustomObject>
    <description>Represents the event defined in Cvent.</description>
    <fields>
        <fullName>ActualCategory__c</fullName>
        <label>Actual Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractedSpeaker__c</fullName>
        <label>ContractedSpeaker</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CventEvents__pkg_EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CventEvents__pkg_PlanningStatus__c</fullName>
        <label>Planning Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CventEvents__pkg_StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CventEvents__pkg_StartTime__c</fullName>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>CventEvents__pkg_Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>No Registration Required</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CventEvents__pkg_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KOLManageremail__c</fullName>
        <label>KOL Manager email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cvent Event</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cvent Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Expert__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>KOL information</relationshipLabel>
        <relationshipName>KOL_information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>KOL information</label>
    <nameField>
        <label>KOL Information</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KOL information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/KOL_Contract__c.object
<CustomObject>
    <description>This object is used to manage Speaker/KOL Contracts. The standard Contract module is NOT used, due to security.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Use this field only when the Contract should be linked to a specific Contact instead of an Account</description>
        <inlineHelpText>Use this field only when the Contract should be linked to a specific Contact instead of an Account</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Speaker_KOL_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expert__c</fullName>
        <label>KOL information</label>
        <referenceTo>Expert__c</referenceTo>
        <relationshipLabel>KOL Contracts</relationshipLabel>
        <relationshipName>Expert_Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>KOL_Contract__c</fullName>
        <description>This is the number of the KOL Contracts. Used to populate KOL Contract Name</description>
        <displayFormat>KOL Contract # - {0}</displayFormat>
        <inlineHelpText>This is the number of the KOL Contracts. Used to populate KOL Contract Name</inlineHelpText>
        <label>KOL Contract #</label>
        <type>AutoNumber</type>
    </fields>
    <label>KOL Contract</label>
    <nameField>
        <label>KOL Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KOL Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/KOL_Contract_Deliverable__c.object
<CustomObject>
    <description>This object contains the deliverables connected to a KOL Contract</description>
    <fields>
        <fullName>CventEventUpd__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cvent Event</label>
        <referenceTo>CventEvents__Event__c</referenceTo>
        <relationshipLabel>KOL Contract Deliverables</relationshipLabel>
        <relationshipName>KOL_Contract_Deliverables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KOL_Contract__c</fullName>
        <description>The KOL Contract that the Deliverable is deducting from</description>
        <inlineHelpText>The KOL Contract that the Deliverable is deducting from</inlineHelpText>
        <label>KOL Contract</label>
        <referenceTo>KOL_Contract__c</referenceTo>
        <relationshipLabel>Deliverables</relationshipLabel>
        <relationshipName>Deliverables</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>KOL Contract Deliverable</label>
    <nameField>
        <label>Deliverable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KOL Contract Deliverables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/KOLInfoController.cls
/*------------------------------------------------------------	
Author: 		Richard Trum (Glimt) 2019-11-28	
Description:   	KOL Information (Expert__c) class to handle Apex related to components inside the Clinical Affairs app 
History	
<Date>      <Authors Name>     <Brief Description of Change>
20200921 	Richard Trum	 	Updated the getMyCventEvents method to loop records in reverse order due to delete action
20240126    Richard Trum        TFUS-000006420 (updated the method getMyCventEvents)
------------------------------------------------------------*/

public with sharing class KOLInfoController {

    @AuraEnabled
    public static Expert__c getKOLdata(String recordId) {
    Expert__c KOLinfo = [SELECT Id, Contact__c FROM Expert__c WHERE Id =: recordId];
    return KOLinfo;
    }
    
    @AuraEnabled
    public static List<Expert__c> getKOLlist() {    
    List<Expert__c> KOLinfo = [SELECT Id, Name, Contact__c FROM Expert__c];        
    return KOLinfo;
    } 
    
    @AuraEnabled
    public static List<KOL_Contract_Deliverable__c> getDeliverables(String recordId){
        List<KOL_Contract_Deliverable__c> delList = new List<KOL_Contract_Deliverable__c>();
        delList = [SELECT Id, CventEventUpd__c, CventEventUpd__r.Name, KOL_Contract__c, KOL_Contract__r.Name, KOL_Contract__r.Expert__c, CventEventUpd__r.ContractedSpeaker__c, CventEventUpd__r.CventEvents__pkg_StartDate__c, CventEventUpd__r.CventEvents__pkg_Title__c 
                   FROM KOL_Contract_Deliverable__c WHERE KOL_Contract__r.Expert__c =: recordId];
        return delList;
    }
    
    @AuraEnabled
    public static List<CventEvents__Event__c> getSpeakerEvents(String recordId){
        List<CventEvents__Event__c> eventList = new List<CventEvents__Event__c>();
        List<CventEvents__Attendee__c> attendeeList = new List<CventEvents__Attendee__c>();
        
        //Check contracted speaker field
        Expert__c KOL = [SELECT Name, Contact__r.Full_Name__c, Contact__c FROM Expert__c WHERE Id =:recordId];
        eventList = [SELECT Id, Name, ContractedSpeaker__c, CventEvents__pkg_StartDate__c, CventEvents__pkg_StartTime__c, CventEvents__pkg_EndDate__c, CventEvents__pkg_Title__c FROM CventEvents__Event__c WHERE ContractedSpeaker__c LIKE: KOL.Contact__r.Full_Name__c];
        
        Set<Id> eventIds = (new Map<Id, CventEvents__Event__c>(eventList)).keySet().clone();
        Map<Id, KOL_Contract_Deliverable__c> eventsWithDeliverables = new Map<Id, KOL_Contract_Deliverable__c>();
        
        //Check attendees
        attendeeList = [SELECT Id, Name, CventEvents__Contact__c, CventEvents__Event__c FROM CventEvents__Attendee__c WHERE CventEvents__Contact__c =: KOL.Contact__c AND CventEvents__RegistrationType__c =: 'Speaker'];
                
        if(!attendeeList.IsEmpty()){
             Integer attendeeListLen = attendeeList.size();
             for(Integer i=0;i<attendeeListLen;i++){
                
                String eventToCheck = attendeeList[i].CventEvents__Event__c;
                 
                 if(eventIds.contains(eventToCheck)==false){
                     eventIds.add(attendeeList[i].CventEvents__Event__c);
                 }
                       
        	 }
        }
        
       	//Check deliverables
        List<KOL_Contract_Deliverable__c> delList = new List<KOL_Contract_Deliverable__c>();
        delList = [SELECT Id, CventEventUpd__c, CventEventUpd__r.Name, KOL_Contract__c, KOL_Contract__r.Name, KOL_Contract__r.Expert__c, CventEventUpd__r.ContractedSpeaker__c, CventEventUpd__r.CventEvents__pkg_StartDate__c, CventEventUpd__r.CventEvents__pkg_EndDate__c, CventEventUpd__r.CventEvents__pkg_Title__c 
                   FROM KOL_Contract_Deliverable__c WHERE KOL_Contract__r.Expert__c =: recordId];
        
        if(!delList.IsEmpty()){

            Integer delListLen = delList.size();
            for(Integer i=0;i<delListLen;i++){
             	 String delEventToCheck = delList[i].CventEventUpd__c;            
                 if(eventIds.contains(delEventToCheck)==false){
                		eventIds.add(delList[i].CventEventUpd__c);
                 }
                 eventsWithDeliverables.put(delList[i].CventEventUpd__c, delList[i]);
            }       
        }
        
        eventList = [SELECT Id, Name, ContractedSpeaker__c, CventEvents__pkg_StartDate__c, CventEvents__pkg_StartTime__c, CventEvents__pkg_EndDate__c, CventEvents__pkg_Title__c FROM CventEvents__Event__c WHERE Id IN: eventIds ORDER BY CventEvents__pkg_StartTime__c DESC];
        Integer eventListLen = eventList.size();
        
        for(Integer j = 0;j<eventListLen;j++){
            	String eventToCheck = eventList[j].Id;
            	if(eventsWithDeliverables.containsKey(eventToCheck)){
                    KOL_Contract_Deliverable__c deliverable = eventsWithDeliverables.get(eventToCheck);
                    eventList[j].ActualCategory__c = deliverable.KOL_Contract__r.Name;
            	}
        }
        
        return eventList;
    }
    
    @AuraEnabled
    public static String getReportLink(){
         return CAHomeReportLink__c.getInstance().ReportURL__c;       
    }
    
    @AuraEnabled
    public static List<CventEvents__Event__c> getMyCventEvents(){
        
        String userEmail = UserInfo.getUserEmail();
        
        List<CventEvents__Event__c> eventList = new List<CventEvents__Event__c>();
        eventList = [SELECT Id, Name, CventEvents__pkg_Status__c, CventEvents__pkg_PlanningStatus__c, ContractedSpeaker__c, KOLManageremail__c, CventEvents__pkg_StartDate__c, CventEvents__pkg_StartTime__c, CventEvents__pkg_Title__c FROM CventEvents__Event__c WHERE (KOLManageremail__c =: userEmail AND CventEvents__pkg_PlanningStatus__c!='Cancelled') ORDER BY CventEvents__pkg_StartDate__c ASC];
        Integer listLen = eventList.size();
        Map<Id, CventEvents__Event__c> eventMap = new Map<Id, CventEvents__Event__c>();
        
        if(!eventList.IsEmpty()){

            for(Integer j=0;j<listLen;j++){
                eventMap.put(eventList[j].Id, eventList[j]);
            }

            List<KOL_Contract_Deliverable__c> deliverables = new List<KOL_Contract_Deliverable__c>();
            try{
                deliverables = [SELECT Id, Name, CventEventUpd__c FROM KOL_Contract_Deliverable__c WHERE CventEventUpd__c IN: eventMap.keySet()];    
            }
            catch(exception e){
                System.debug(e);
            }

            for(KOL_Contract_Deliverable__c deliverable : deliverables){
                if(eventMap.containsKey(deliverable.CventEventUpd__c)){
                    eventMap.remove(deliverable.CventEventUpd__c);
                }
            }

        }    
         
        return eventMap.values();

    }
      
}