src/objects/Call_Report__c.object
<CustomObject>
    <fields>
        <fullName>Call_Notes__c</fullName>
        <label>Call Notes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EndDateTime__c</fullName>
        <description>200331 CFE 2.0</description>
        <label>End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EventWhoIds__c</fullName>
        <description>Test text field to hold EventWhoIds.</description>
        <label>EventWhoIds</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDateTime__c</fullName>
        <description>200324 test start datetime field to be used to populate Event.StartDateTime</description>
        <label>Start</label>
        <type>DateTime</type>
    </fields>
    <label>Call Report</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Call Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Contact_D</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Implants</fullName>
                    <label>Global DPG</label>
                </value>
                <value>
                    <fullName>All Ortho</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ATF</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
                <value>
                    <fullName>BHR</fullName>
                </value>
                <value>
                    <fullName>BHS</fullName>
                </value>
                <value>
                    <fullName>BIH</fullName>
                </value>
                <value>
                    <fullName>BLM</fullName>
                </value>
                <value>
                    <fullName>BLR</fullName>
                </value>
                <value>
                    <fullName>BLZ</fullName>
                </value>
                <value>
                    <fullName>BMU</fullName>
                </value>
                <value>
                    <fullName>BOL</fullName>
                </value>
                <value>
                    <fullName>BRA</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProcedureTracker__c.object
<CustomObject>
    <description>Follow Up your Sales Lifecycle with step-by-step guided instructions. 
#1 Procedure Type: Clear Aligners - suresmile</description>
    <fields>
        <fullName>PracticeAccount__c</fullName>
        <label>Practice Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Procedures</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Procedure Tracker</label>
    <nameField>
        <displayFormat>Track#{000}</displayFormat>
        <label>Record Nr</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Procedure Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_CallReportQuickActionPocController.cls
/**
 * @description       : Test class for CallReportQuickActionPocController
 * @author            : kdoruibin@salesforce.com
 * @group             : 
 * @last modified on  : 09-09-2021
 * @last modified by  : kdoruibin@salesforce.com
 * Modifications Log 
 * Ver   Date         Author                     Modification
 * 1.1   09-09-2021   kdoruibin@salesforce.com   added system.runAs()
 * 2.0   14-08-2024   ohanafi@salesforce.com     TFUS-000006884 - Co_travel__c translation bug fix
**/
@isTest(seeAllData=false)
public without sharing class Test_CallReportQuickActionPocController {
    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.createUsers(1, 'System Administrator');
        List<User> userIntegrationList = TestDataFactory.insertIntegrationUsers(1, 'System Administrator');
        TestDataFactory.createGlobalIntegrationSettings(userIntegrationList);
        List<Event> eventList = TestDataFactory.returnEvents(1, userList.get(0).Id); 
        List<Account> accountsList = TestDataFactory.createAccounts(1, 'Non_ERP_Account', userList.get(0).Id);
        List<Contact> contactList = TestDataFactory.returnContacts(1, 'Contact_D', userList.get(0).Id);
        contactList.get(0).AccountId = accountsList.get(0).Id;
        insert contactList;
        eventList.get(0).WhoId = contactList.get(0).Id;
        insert eventList;
    }

    @isTest
    private static void testSetup() {
        Test.startTest();
        List<User> testUserList = [SELECT Id FROM User WHERE Alias = 'test1'];
        List<Account> testAccountList = [SELECT Id FROM Account WHERE Ownerid = :testUserList[0].Id];
        List<Contact> testContactList = [SELECT Id FROM Contact WHERE OwnerId = :testUserList[0].Id];
        Test.stopTest();
        
        System.assertEquals(1, testUserList.size(), 'Expected one User');
        System.assertEquals(1, testAccountList.size(), 'Expected one Account');
        System.assertEquals(1, testContactList.size(), 'Expected one Contact');
    }

    @isTest
    private static void testCreateEvent() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        Account testAccount = [SELECT Id FROM Account WHERE Ownerid = :testUser.Id LIMIT 1];
        Contact testContact = [SELECT Id FROM Contact WHERE Ownerid = :testUser.Id LIMIT 1];

        Call_Report__c callReportToInsert = new Call_Report__c(
            StartDateTime__c = Datetime.newInstance(2015, 20 , 12, 00, 00, 00)
            , EndDateTime__c = Datetime.newInstance(2015, 20 , 12, 01, 00, 00)
            , Call_Notes__c = 'test123'
            , EventWhoIds__c = '["' + testContact.Id + '"]'
        );
        
        Id createdEventId;
        Test.startTest();
        System.runAs(testUser) {
            insert callReportToInsert;
            createdEventId = CallReportQuickActionPocController.createEvent(callReportToInsert.Id, testContact.Id, 'Manager', false);
        }
        System.assertEquals(Schema.Event.SObjectType, createdEventId.getSobjectType());
        Test.stopTest();
    }

    /**
     * testGetPickListValuesIntoMap Test method for CallReportQuickActionPocController.getPickListValuesIntoMap()
     */
    @isTest
    private static void testGetPickListValuesIntoMap() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        System.runAs(testUser) {
            Test.startTest();
            // Call the method and store the result in a map
            Map<String, String> pickListValuesMap = CallReportQuickActionPocController.getPickListValuesIntoMap();

            // Assert that the map is not empty
            System.assertNotEquals(0, pickListValuesMap.size(), 'Expected non-empty map of picklist values');

            Test.stopTest();
        }
    }

    /**
     * testGetProcedureTrackerDataList Test method for CallReportQuickActionPocController.getProcedureTrackerDataList()
     */
    @isTest
    private static void testGetProcedureTrackerDataList() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        System.runAs(testUser) {
            List<Account> testAccountList = [SELECT Id FROM Account WHERE Ownerid = :testUser.Id];
            testAccountList[0].Country__c = 'US';
            update testAccountList[0];


            // Create a ProcedureTracker__c record
            ProcedureTracker__c procedureTracker = new ProcedureTracker__c(
                    PracticeAccount__c = testAccountList[0].Id,
                    RecordTypeId = Schema.SObjectType.ProcedureTracker__c.getRecordTypeInfosByName().get('Clear Aligners - US').getRecordTypeId()
            );
            insert procedureTracker;

            Test.startTest();

            // Call the method and retrieve the ProcedureTracker__c record by its ID
            ProcedureTracker__c result = CallReportQuickActionPocController.getProcedureTrackerDataList(procedureTracker.Id);

            // Assert that the returned record is not null
            System.assertNotEquals(null, result, 'Expected non-null ProcedureTracker__c record');

            Test.stopTest();
        }
    }


}