src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Country_Code_3_digit__c</fullName>
        <description>TFUS-000002404 Used by Eloqua</description>
        <label>Country Code (3-digit)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_Code_3_digit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Organizing Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ALL</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>BEX</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Distributor Markets</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Holland</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
                <value>
                    <fullName>HQ: DE</fullName>
                </value>
                <value>
                    <fullName>HQ: NL</fullName>
                </value>
                <value>
                    <fullName>HQ: SE</fullName>
                </value>
                <value>
                    <fullName>INDIA</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Kazakhstan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>Kuwait</fullName>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Morocco</fullName>
                </value>
                <value>
                    <fullName>New Zealand</fullName>
                </value>
                <value>
                    <fullName>Norway</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBU_Focus__c</fullName>
        <description>Used to track which SBU the Campaigns target for promotion/training.</description>
        <inlineHelpText>Pick the SBU(s) that this Campaign targets for promotion/training.</inlineHelpText>
        <label>SBU</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Implants</fullName>
                </value>
                <value>
                    <fullName>Endodontics</fullName>
                </value>
                <value>
                    <fullName>Orthodontics</fullName>
                </value>
                <value>
                    <fullName>Preventive</fullName>
                </value>
                <value>
                    <fullName>Prosthetics</fullName>
                </value>
                <value>
                    <fullName>Restorative</fullName>
                </value>
                <value>
                    <fullName>CAD/CAM</fullName>
                </value>
                <value>
                    <fullName>Treatment Centers</fullName>
                </value>
                <value>
                    <fullName>Imaging Systems</fullName>
                </value>
                <value>
                    <fullName>Instruments</fullName>
                </value>
                <value>
                    <fullName>US Consumables</fullName>
                </value>
                <value>
                    <fullName>Maillefer</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Strategy__c</fullName>
        <label>Strategy/Segment</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>Get</fullName>
                </value>
                <value>
                    <fullName>Grow</fullName>
                </value>
                <value>
                    <fullName>Keep</fullName>
                </value>
                <value>
                    <fullName>Educate</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Starter</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Campaign</fullName>
        <active>false</active>
        <description>All Campaigns excluding Symposia - Used by BeNeLux</description>
        <label>Campaign</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Country_Code_3_digit__c</fullName>
        <formula>IF(ISBLANK(ContactId),TEXT(Lead.Country_Code_3_digit__c),TEXT(Contact.Country_Code_3_digit__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Code (3-digit)</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country_Code_3_digit__c</fullName>
        <description>TFUS-000002404 Used by Eloqua</description>
        <label>Country Code (3-digit)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_Code_3_digit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>InsertEmailMarketingConsentCollected__c</fullName>
        <inlineHelpText>Please fill the information if the Email Marketing Consent was collected or not</inlineHelpText>
        <label>Insert Email Marketing Consent Collected</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Implants</fullName>
                    <label>Global DPG</label>
                </value>
                <value>
                    <fullName>All Ortho</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ATF</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
                <value>
                    <fullName>BHR</fullName>
                </value>
                <value>
                    <fullName>BHS</fullName>
                </value>
                <value>
                    <fullName>BIH</fullName>
                </value>
                <value>
                    <fullName>BLM</fullName>
                </value>
                <value>
                    <fullName>BLR</fullName>
                </value>
                <value>
                    <fullName>BLZ</fullName>
                </value>
                <value>
                    <fullName>BMU</fullName>
                </value>
                <value>
                    <fullName>BOL</fullName>
                </value>
                <value>
                    <fullName>BRA</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
                <value>
                    <fullName>DEU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Country_Code_3_digit.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AFG</fullName>
    </customValue>
    <customValue>
        <fullName>ALB</fullName>
    </customValue>
    <customValue>
        <fullName>ARE</fullName>
    </customValue>
    <customValue>
        <fullName>ARG</fullName>
    </customValue>
    <customValue>
        <fullName>ARM</fullName>
    </customValue>
    <customValue>
        <fullName>AUS</fullName>
    </customValue>
    <customValue>
        <fullName>AUT</fullName>
    </customValue>
    <customValue>
        <fullName>BDI</fullName>
    </customValue>
    <customValue>
        <fullName>BEL</fullName>
    </customValue>
    <customValue>
        <fullName>BGD</fullName>
    </customValue>
    <customValue>
        <fullName>BGR</fullName>
    </customValue>
    <customValue>
        <fullName>BHR</fullName>
    </customValue>
    <customValue>
        <fullName>BHS</fullName>
    </customValue>
    <customValue>
        <fullName>BIH</fullName>
    </customValue>
    <customValue>
        <fullName>BLR</fullName>
    </customValue>
    <customValue>
        <fullName>BLZ</fullName>
    </customValue>
    <customValue>
        <fullName>BMU</fullName>
    </customValue>
    <customValue>
        <fullName>BOL</fullName>
    </customValue>
    <customValue>
        <fullName>BRA</fullName>
    </customValue>
    <customValue>
        <fullName>BRB</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWA</fullName>
    </customValue>
    <customValue>
        <fullName>CAF</fullName>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
    </customValue>
    <customValue>
        <fullName>CHE</fullName>
    </customValue>
    <customValue>
        <fullName>CHL</fullName>
    </customValue>
    <customValue>
        <fullName>CHN</fullName>
    </customValue>
    <customValue>
        <fullName>CIV</fullName>
    </customValue>
    <customValue>
        <fullName>CMR</fullName>
    </customValue>
    <customValue>
        <fullName>COD</fullName>
    </customValue>
    <customValue>
        <fullName>DEU</fullName>
    </customValue>
    <description>Country codes of 3 digits - used mainly for Wave reporting together with Wave maps - needed for teh map to know which country on the map the country belongs to</description>
    <masterLabel>Country Code (3-digit)</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/CampMgmtTestHelpers.cls
global class CampMgmtTestHelpers
{
    global static Account createTestAccount(String name)
    {
        Account testAccount = new Account();
        String currentUserId = UserInfo.getUserId();
        testAccount = testDataFactory.returnAccounts(1, 'CIM_Account', currentUserId)[0];
        testAccount.Country__c = 'SE';
        testAccount.Name = name;
        insert testAccount;
        
        return testAccount;
    }    
    
    global static Contact createTestContact(ID accountId, String firstName, String lastName,String emailAddress)
    {
        Contact testContact = new Contact();
        testContact.AccountId = accountId;
        testContact.FirstName = firstName;
        testContact.LastName = lastName;
        testContact.InsertEmailMarketingConsentCollected__c= 'No';
        testContact.Email = emailAddress;
        testContact.Email = emailAddress;
        testContact.Country_Code_3_digit__c = 'DEU';
        insert testContact;
        
        return testContact;
    }

    global static Campaign createTestCampaign(String name, String recordTypeDeveloperName)	
    {
        RecordType recordType = [SELECT Id FROM RecordType WHERE DeveloperName = :recordTypeDeveloperName AND SObjectType = 'Campaign'];
 
        Campaign testCampaign = new Campaign();
        testCampaign.RecordTypeId = recordType.Id;
        testCampaign.Name = name;
        testCampaign.Strategy__c = 'GET';
        testCampaign.SBU_Focus__c = 'Implants';
        testCampaign.Campaign_Category__c = 'Consumables';
        testCampaign.Brands__c = 'Sinius';
        testCampaign.IsActive = true;
        testCampaign.Country_Code_3_digit__c = 'DEU';
        insert testCampaign;

        return testCampaign;
    }

    global static Campaign createTestSession(ID campaignId, String name, String recordTypeDeveloperName)
    {
        RecordType recordType = [SELECT Id FROM RecordType WHERE DeveloperName = :recordTypeDeveloperName AND SObjectType = 'Campaign'];

        Campaign testSession = new Campaign();
        testSession.RecordTypeId = recordType.Id;
        testSession.Name = name;
        testSession.Parent_Event__c = campaignId;
        testSession.Strategy__c = 'GET';
        testSession.IsActive = true;
        insert testSession;  

        return testSession;     
    }

    global static CampaignMember createTestCampaignMember(ID campaignId, ID contactId, String status)
    {
        CampaignMember testCampaignMember = createTestCampaignMember(campaignId, contactId, status, 'Participant');
        insert testCampaignMember;
        return testCampaignMember;
    } 

    global static CampaignMember createTestCampaignMember(ID campaignId, ID contactId, String status, String type)
    {
        CampaignMember testCampaignMember = new CampaignMember();
        testCampaignMember.CampaignId = campaignId;
        testCampaignMember.ContactId = contactId;
        testCampaignMember.Status = status;
        testCampaignMember.Type__c = type;

        return testCampaignMember;     
    }

    global static CampaignMember returnTestCampaignMember(ID campaignId, ID contactId, String status)
    {
        return createTestCampaignMember(campaignId, contactId, status, 'Participant');
    }
}