src/objects/Campaign.object
<CustomObject>
    <recordTypes>
        <fullName>Campaign</fullName>
        <active>false</active>
        <description>All Campaigns excluding Symposia - Used by BeNeLux</description>
        <label>Campaign</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account to where the contact is related. This is usually the same as the Account to where the Contact is related, but can be edited to cater for Contacts other location</description>
        <inlineHelpText>The Account to where the contact is related. This is usually the same as the Account to where the Contact is related, but can be edited to cater for Contacts other location</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign Members (Contacts of the Account)</relationshipLabel>
        <relationshipName>Campaign_Members2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

src/objects/CventEvents__Attendee__c.object
<CustomObject>
    <description>Represents the attendee of an event.</description>
    <fields>
        <fullName>CventEvents__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Events Participation</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CventEvents__Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Number</label>
        <referenceTo>CventEvents__Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CventEvents__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Events Participation</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CventEvents__Event__c.object
<CustomObject>
    <description>Represents the event defined in Cvent.</description>
    <fields>
        <fullName>CventEvents__pkg_Code__c</fullName>
        <label>Code</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cvent Event</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cvent Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CventEvents__Attendee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attendee</label>
        <referenceTo>CventEvents__Attendee__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CventEvents__Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cvent Event Number</label>
        <referenceTo>CventEvents__Event__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>GET</fullName>
        <active>true</active>
        <businessProcess>GET</businessProcess>
        <label>X DO NOT USE 2t</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/leadConvert.cls
/*Version History
 * Author:
 * Description: Lead Convert Class
 * Test Class:  Test_leadConvert
 * History
 *  <Date>      <Authors Name>     <Brief Description of Change>
 * 23-07-2023   Houssam Adib        Updates the campaign members linked to the new converted lead
 * 08-09-2023   Stefano Massoni     TFUS-000006014-Changed the contactId parameter with the LeadId parameter to get only the Campaign Member
                                    related to the Lead
 */
global with sharing class leadConvert {

    @InvocableMethod(label='Convert Lead' description='Converts a lead to an account/contact' category='Lead')
    public static List<String> convertLead(List<ConvertLeadRequest> input) {
        try {
            Database.LeadConvert lc = new Database.LeadConvert();
            lc.setLeadId(input[0].leadId);
            lc.setConvertedStatus(input[0].convertedStatus);

            //Create opportunity
            if(input[0].createOpportunity != null && input[0].createOpportunity == false){
                lc.setDoNotCreateOpportunity(true);
            }

            //Owner Id
            if(input[0].ownerId != null){
                lc.setOwnerId(input[0].OwnerId);
            }

            //Contact

            if(String.isNotBlank(input[0].contactId))
            {
                lc.setContactId(input[0].contactId);

                Contact c = [SELECT Id, AccountId FROM Contact WHERE Id =: input[0].contactId];

                lc.setAccountId(c.AccountId);

            }
            else if (input[0].accountId != '') {
                lc.setAccountId(input[0].accountId);

                /*if(input[0].convertToPersonAccount != null && input[0].convertToPersonAccount){
                    lc.setRelatedPersonAccountId(input[0].accountId);
                }*/

            }

            if (input[0].overWriteLeadSource != null && input[0].overWriteLeadSource) {
                lc.setOverwriteLeadSource(input[0].overWriteLeadSource);
            }

            if (input[0].sendEmailToOwner != null && input[0].sendEmailToOwner) {
                lc.setSendNotificationEmail(input[0].sendEmailToOwner);
            }

            Database.LeadConvertResult lcr = null;

            Database.DMLOptions dmlOpts = new Database.DMLOptions();
            dmlOpts.duplicateRuleHeader.allowSave = true;
            dmlOpts.optAllOrNone = true;

            lcr = Database.convertLead(lc, dmlOpts);

            if (lcr.isSuccess()) {
                List<String> result = new List<String>();
                String contactId = lcr.getContactId();
                String accountId = lcr.getAccountId();
                if(String.isNotBlank(contactId)){
                    result.add(contactId);

                    updateAttendeeIfCVENTCampaign(input[0].leadId,contactId);
                    // Update the campaign member if the contact is linked to one
                    if(String.isNotBlank(accountId))
                    {
                        updateCampaignMemberWithAccountId(input[0].leadId,accountId);
                    }
                }
                else{
                    result.add(lcr.getAccountId());
                }
                //
                /*ConvertLeadActionResult result = new ConvertLeadActionResult();
                result.accountId = lcr.getAccountId();
                result.contactId = lcr.getContactId();
                result.opportunityId = lcr.getOpportunityId();*/
                return result;
            } else {
                throw new ConvertLeadActionException(lcr.getErrors()[0].getMessage());
            }

        } catch (Exception e) {
            String errorMessage = e.getMessage();
            Integer startIndex = errorMessage.indexOf(':', errorMessage.indexOf(':') + 1) + 2;
            if (startIndex == -1) {
                throw new ConvertLeadActionException(errorMessage);
            } else {
                String filteredMessage = errorMessage.substring(startIndex);
                Integer endIndex = filteredMessage.indexOf(':');

                if(endIndex != -1){
                    filteredMessage = filteredMessage.substring(0, endIndex);
                }

                throw new ConvertLeadActionException(filteredMessage);
            }
        }

    }

    /*@AuraEnabled
    public static List<RecordType> findRecordTypes (String objectName, Boolean isPersonAccount){

        List<RecordType> result = new List<RecordType>();
        if(isPersonAccount == null){
            isPersonAccount = false;
        }

        result = [SELECT Id, Name, DeveloperName FROM RecordType WHERE SObjectType =: objectName AND IsActive = true AND IsPersonType =: isPersonAccount];

        return result;
    }*/

    /**
     * Updates the campaign members linked to the new converted lead
     * so they can show as campaign members in the account related list
     * @author hadib@salesforce.com | 23-07-2023
     *
     * @param leadId The converted Lead Id
     * @param accountId The account id of the new contact id.
     */
    public static void updateCampaignMemberWithAccountId(String leadId, String accountId)
    {
        // Put the account id of the lead converted in the campaign member account__c field.
        List<CampaignMember> members = [ SELECT Id FROM CampaignMember WHERE LeadId=:leadId];
        for(CampaignMember member : members)
        {
            member.Account__c = accountId;
        }

        update members;
    }

    /**
     * When we update the contact ID for a campaign member (after converting a lead),
     * we need to make sure the attendee record also gets updated with the same information.
     * This is important for keeping the Cvent changes synchronization working
     * @author hadib@salesforce.com | 02-10-2023
     *
     * @param leadId        Lead Id
     * @param contactId     Contact Id
     */
    public static void updateAttendeeIfCVENTCampaign(String leadId, String contactId)
    {
        // 1.Retrieve CVENT Campaign Members
        Id memberRecordTypeId   = GlobalUtils.getRecordTypeId('CampaignMember', 'CVENT_Campaign_Member');
        List<CampaignMember> allCventMembers = [    SELECT  Id,LeadId,Campaign.Event_Code__c
                                                    FROM    CampaignMember
                                                    WHERE   LeadId = :leadId
                                                            AND
                                                            RecordTypeId = :memberRecordTypeId];

        // 2.Extract Event Codes from indirect lookup CampaignMembers.ParentCampaign.Event_Code__c
        Set<String> eventCodes = new Set<String>();
        for(CampaignMember member : allCventMembers)
        {
            eventCodes.add(member.Campaign.Event_Code__c);
        }

        // 3.Retrieve Related Attendees using the Cvent Event Code
        List<CventEvents__Attendee__c> attendees = [    SELECT  Id
                                                        FROM    CventEvents__Attendee__c
                                                        WHERE   CventEvents__Lead__c =:leadId
                                                                AND
                                                                CventEvents__Event__r.CventEvents__pkg_Code__c IN :eventCodes];

        // 4.Update the attendees with the new contact resulted from lead conversion
        if(!attendees.isEmpty())
        {
            for(CventEvents__Attendee__c attendee : attendees)
            {
                attendee.CventEvents__Contact__c = contactId;
            }

            update attendees;
        }
    }

    global class ConvertLeadRequest{

        @InvocableVariable(required=true)
        global ID leadId;

        @InvocableVariable(required=true)
        global String convertedStatus;

        @InvocableVariable(required=false)
        global String accountId;

        @InvocableVariable(required=false)
        global String contactId;

        @InvocableVariable
        global Boolean overWriteLeadSource;

        @InvocableVariable
        global Boolean createOpportunity;

        @InvocableVariable
        global String opportunityName;

        @InvocableVariable
        global ID ownerId;

        @InvocableVariable
        global Boolean sendEmailToOwner;

        @InvocableVariable
        global Boolean convertToPersonAccount;
    }

    class ConvertLeadActionException extends Exception {}
}