src/objects/Campaign.object
<CustomObject>
    <recordTypes>
        <fullName>Campaign</fullName>
        <active>false</active>
        <description>All Campaigns excluding Symposia - Used by BeNeLux</description>
        <label>Campaign</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CventEvents__AttendeeTemp__c.object
<CustomObject>
    <description>Auxiliary object used for storing a fusion of contact and event participation information retrieved from Cvent.</description>
    <fields>
        <fullName>CventEvents__pkg_Attended__c</fullName>
        <description>Represents whether the Attendee participated Event or not.</description>
        <label>Attended</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CventEvents__pkg_AttendeeStatus__c</fullName>
        <label>Attendee Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CventEvents__pkg_AttendeeStub__c</fullName>
        <externalId>true</externalId>
        <label>Attendee Stub</label>
        <length>36</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CventEvents__pkg_EventStub__c</fullName>
        <externalId>true</externalId>
        <label>Event Stub</label>
        <length>36</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Attendee Temp Record</label>
    <nameField>
        <displayFormat>AT-{00000000}</displayFormat>
        <label>Attendee Temp Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendee Temp Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CventEvents__Event__c.object
<CustomObject>
    <description>Represents the event defined in Cvent.</description>
    <fields>
        <fullName>CventEvents__pkg_EventStub__c</fullName>
        <externalId>true</externalId>
        <label>Event Stub</label>
        <length>36</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cvent Event</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cvent Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DynamicMapping__mdt.object
<CustomObject>
    <description>It provides a way to map the fields of one object to another, allowing for the seamless transfer of data between the two objects</description>
    <fields>
        <fullName>SourceFieldApiName__c</fullName>
        <description>SourceObjectApiName.SourceFieldApiName will be mapped to TargetObjectApiName.TargetFieldApiName</description>
        <inlineHelpText>SourceObjectApiName.SourceFieldApiName will be mapped to TargetObjectApiName.TargetFieldApiName</inlineHelpText>
        <label>Source Field Api Name</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Dynamic Mapping</label>
    <pluralLabel>Dynamic Mappings</pluralLabel>
</CustomObject>

src/classes/ConvertUnmatchedTempsToLeadsSchedulable.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Houssam ADIB (Salesforce)
Description:    Scheduled Job that runs every hour to sync new API Changes to the Temp Attendees
Test class:     AttendeeTriggerHelperTest

History
20-03-2023     Create new class
----------------------------------------------------------------------------------------*/
global class ConvertUnmatchedTempsToLeadsSchedulable implements Schedulable {
    global void execute(SchedulableContext sc)
    {
        try
        {
            List<DynamicMapping__mdt> mappings = MappingManagement.getMapping(CventManagement.SOURCE_OBJECT_TEMP, CventManagement.TARGET_OBJECT_LEAD, false);

            // 1-Initiate the Set with the Required fields not mapped dynamically but statically in the code
            Set<String> allFields = new Set<String>{
                    'CventEvents__pkg_AttendeeStub__c',
                    'CventEvents__pkg_AttendeeStatus__c',
                    'MatchStatus__c',
                    'CventEvents__pkg_EventStub__c',
                    'CventEvents__pkg_Attended__c',
                    'Doyouhaveanintraoralscannerinyour__c',
                    'Whichsolutionsareyouinterestedin__c'
            };

            // 2-Add the Dynamic ones
            DynamicMapping__mdt mapping;
            for (Integer i = 0, j = mappings.size(); i < j; i++) {
                mapping = mappings[i];
                allFields.add(mapping.SourceFieldApiName__c);
            }

            // 3-Build the query
            Set<String> convertedEventsStubs = new Set<String>();

            Map<String, CventEvents__Event__c> stubToEvent = new Map<String, CventEvents__Event__c>();
            Map<String, Campaign> stubToConvertedCampaign = new Map<String, Campaign>();

            CventManagement.findConvertedEvents(stubToEvent,stubToConvertedCampaign);

            convertedEventsStubs = stubToEvent.keySet();
            Set<String> existingAttendeesStubs = CventManagement.getExistingAttendeesStubForConvertedEvents(convertedEventsStubs);

            String unmatchedStatus = 'Unmatched';
            String fieldsApiNames = String.join(new List<String>(allFields), ',');
            String queryString = 'SELECT ' + fieldsApiNames
                                +' FROM CventEvents__AttendeeTemp__c'
                                +' WHERE CventEvents__pkg_EventStub__c IN :convertedEventsStubs'
                                +      ' AND MatchStatus__c = :unmatchedStatus'
                                +      ' AND CventEvents__pkg_AttendeeStub__c NOT IN :existingAttendeesStubs';

            List<CventEvents__AttendeeTemp__c> unmatchedTemps = Database.query(queryString);

            if(!unmatchedTemps.isEmpty())
            {
                Map<String, List<CventEvents__AttendeeTemp__c>> tempsToProcess = CventManagement.assortByEventStub(unmatchedTemps);
                CventManagement.convertUnmatchedTempsToLeadsAndAttendees(stubToConvertedCampaign, stubToEvent, tempsToProcess);
            }

        }
        catch (Exception e) {
            DebugLog.addException(e,'ConvertUnmatchedTempsToLeadsSchedulable');
        }
    }
}