src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Product Focus (IMPL)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ANKYLOS</fullName>
                    <label>Ankylos</label>
                </value>
                <value>
                    <fullName>ASTRA TECH Implant System</fullName>
                    <label>Astra Tech Implant System</label>
                </value>
                <value>
                    <fullName>Astra Tech Implant System EV</fullName>
                </value>
                <value>
                    <fullName>Astra Tech Implant System Profile</fullName>
                </value>
                <value>
                    <fullName>ATLANTIS Abutments</fullName>
                </value>
                <value>
                    <fullName>ATLANTIS ISUS</fullName>
                </value>
                <value>
                    <fullName>DS PrimeTaper</fullName>
                </value>
                <value>
                    <fullName>DS OmniTaper</fullName>
                </value>
                <value>
                    <fullName>Frialit</fullName>
                </value>
                <value>
                    <fullName>Frios</fullName>
                </value>
                <value>
                    <fullName>MGuide</fullName>
                </value>
                <value>
                    <fullName>MIS-C1</fullName>
                </value>
                <value>
                    <fullName>MIS-Lance</fullName>
                </value>
                <value>
                    <fullName>MIS-Seven</fullName>
                </value>
                <value>
                    <fullName>MIS-V3</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>OSSIX</fullName>
                </value>
                <value>
                    <fullName>Prothèse EV Family</fullName>
                </value>
                <value>
                    <fullName>SIMPLANT</fullName>
                </value>
                <value>
                    <fullName>STEPPS</fullName>
                </value>
                <value>
                    <fullName>SYMBIOS</fullName>
                </value>
                <value>
                    <fullName>WeldOne</fullName>
                </value>
                <value>
                    <fullName>XiVe</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Campaign_Country__c</fullName>
        <description>Country where the Campaign is taking place.</description>
        <inlineHelpText>Country where the Campaign is taking place.</inlineHelpText>
        <label>Campaign Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Holland</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
                <value>
                    <fullName>Hungary</fullName>
                </value>
                <value>
                    <fullName>Iceland</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Campaign</fullName>
        <active>false</active>
        <description>All Campaigns excluding Symposia - Used by BeNeLux</description>
        <label>Campaign</label>
    </recordTypes>
    <recordTypes>
        <fullName>Digital_Marketing_Campaign</fullName>
        <active>true</active>
        <description>Used in Lightning for the Eloqua integration</description>
        <label>Digital Marketing Campaign</label>
    </recordTypes>
    <recordTypes>
        <fullName>InPersonEventCampaign</fullName>
        <active>true</active>
        <description>Used for in-person as well as virtual events where sales leads/opportunities are generated based on attendance</description>
        <label>In-Person or Virtual Event Campaign</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>3D Upgrade</fullName>
                </value>
                <value>
                    <fullName>ACB with ASA</fullName>
                </value>
                <value>
                    <fullName>AH Plus</fullName>
                </value>
                <value>
                    <fullName>AH Plus Bioceramic Sealer</fullName>
                </value>
                <value>
                    <fullName>AH Temp</fullName>
                </value>
                <value>
                    <fullName>AlginX</fullName>
                </value>
                <value>
                    <fullName>All Ceramics</fullName>
                </value>
                <value>
                    <fullName>All Other Endo</fullName>
                </value>
                <value>
                    <fullName>All Other - Niti Rotary Files</fullName>
                </value>
                <value>
                    <fullName>All Other – Obturation</fullName>
                </value>
                <value>
                    <fullName>Anaestadent</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>ANKYLOS</fullName>
                </value>
                <value>
                    <fullName>Apex Locator</fullName>
                </value>
                <value>
                    <fullName>Aquasil</fullName>
                </value>
                <value>
                    <fullName>Aquasil Ultra Plus</fullName>
                </value>
                <value>
                    <fullName>ATIS</fullName>
                </value>
                <value>
                    <fullName>ATIS EV</fullName>
                </value>
                <value>
                    <fullName>ATIS TX</fullName>
                </value>
                <value>
                    <fullName>Atlantis</fullName>
                </value>
                <value>
                    <fullName>Atlantis Abutments</fullName>
                </value>
                <value>
                    <fullName>Atlantis Suprastructures</fullName>
                </value>
                <value>
                    <fullName>Automate</fullName>
                </value>
                <value>
                    <fullName>Axano</fullName>
                </value>
                <value>
                    <fullName>Axeos</fullName>
                </value>
                <value>
                    <fullName>Azento Astra Tech</fullName>
                </value>
                <value>
                    <fullName>Azento EV</fullName>
                </value>
                <value>
                    <fullName>Azento XiVE</fullName>
                </value>
                <value>
                    <fullName>Bioceramic</fullName>
                </value>
                <value>
                    <fullName>Bioceramic Sealer</fullName>
                    <isActive>false</isActive>
                    <label>Bioceramic Sealer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>CIM_Account</value>
            </filterItems>
            <filterItems>
                <field>Account.OneAccount_Type__c</field>
                <operation>equals</operation>
                <value>Distributor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign Members (Dealer)</relationshipLabel>
        <relationshipName>Campaign_Members3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Customer Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaign Members</relationshipLabel>
        <relationshipName>Campaign_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesLead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Lead</label>
        <referenceTo>Field_Sales_Project_Members__c</referenceTo>
        <relationshipLabel>Campaign Members (Sales Lead)</relationshipLabel>
        <relationshipName>Campaign_Members1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>URL_Source__c</fullName>
        <label>URL Source</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>VoucherCode__c</fullName>
        <label>VoucherCode</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>IDSBrand__c</fullName>
        <label>IDS Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IDSCampaign__c</fullName>
        <label>IDS Campaign</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IDSDealer__c</fullName>
        <label>IDS Dealer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IDSDescription__c</fullName>
        <label>IDS Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IDSURLSource__c</fullName>
        <label>IDS URL Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IDSVoucherCode__c</fullName>
        <label>IDS Voucher Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/StandardLeadTriggerHelper.cls
global with sharing class StandardLeadTriggerHelper {
    
    private static final String SOBJECT_NAME = 'Lead';

    /**
     * Updates the "Globally Shared" checkbox on Campaigns linked to Leads.
     *
     * Finds all Campaigns linked to the provided Leads and checks if any Lead has a different Country from the Campaign.
     * Marks the Campaign as "Globally Shared" if a difference is found.
     * @author hadib@salesforce.com | 03-10-2024
     * @param newLeads The new lead records
     * @param oldLeads The old lead records
     */
    public static void processLeads(Map<Id, Lead> newLeads, Map<Id, Lead> oldLeads)
    {
        Set<Id> campaignsToProcess = collectCampaignsToProcess(newLeads,oldLeads);

        if (!campaignsToProcess.isEmpty()) {
            // Query all campaign members for the campaigns we need to process
            List<CampaignMember> membersForCampaigns = [
                    SELECT Id, CampaignId, Lead.Country, Campaign.Campaign_Country__c
                    FROM CampaignMember
                    WHERE CampaignId IN :campaignsToProcess
            ];

            // Map to track campaign processing
            Map<Id, Boolean> campaignToSharedGloballyMap = getCampaignToSharedGloballyMap(membersForCampaigns);

            // Now update the campaigns if needed
            List<Campaign> campaignsToUpdate = [SELECT Id, SharedGlobally__c FROM Campaign WHERE Id IN :campaignToSharedGloballyMap.keySet()];
            for (Campaign camp : campaignsToUpdate) {
                Boolean shouldBeShared = campaignToSharedGloballyMap.get(camp.Id);
                if (camp.SharedGlobally__c != shouldBeShared) {
                    camp.SharedGlobally__c = shouldBeShared;
                }
            }

            if (!campaignsToUpdate.isEmpty()) {
                try {
                    update campaignsToUpdate;
                } catch (Exception e) {
                    DebugLog.addException(e, 'Error while updating Campaigns based on Lead country changes');
                }
            }
        }
    }

    /**
     * Based on the campaign members countries we know if we need to shared it globally or not
     * @author hadib@salesforce.com | 03-10-2024
     * @param membersForCampaigns
     *
     * @return Map<Id, Boolean> - If the campaign should be shared or not
     */
    public static Map<Id, Boolean> getCampaignToSharedGloballyMap(List<CampaignMember> membersForCampaigns)
    {
        Map<Id, Boolean> campaignToSharedGloballyMap = new Map<Id, Boolean>();

        // Group campaign members by campaignId
        Map<Id, List<CampaignMember>> campaignIdToMembersMap = new Map<Id, List<CampaignMember>>();
        for (CampaignMember cm : membersForCampaigns) {
            if (!campaignIdToMembersMap.containsKey(cm.CampaignId)) {
                campaignIdToMembersMap.put(cm.CampaignId, new List<CampaignMember>());
            }
            campaignIdToMembersMap.get(cm.CampaignId).add(cm);
        }

        // Process each campaign and check if any member has a different country
        for (Id campaignId : campaignIdToMembersMap.keySet()) {
            List<CampaignMember> campaignMembers = campaignIdToMembersMap.get(campaignId);
            Boolean globallyShared = false;

            for (CampaignMember cm : campaignMembers) {
                if (String.isNotBlank(cm.Lead.Country) && cm.Lead.Country != cm.Campaign.Campaign_Country__c) {
                    globallyShared = true;
                    break; // No need to check further if one mismatch is found
                }
            }

            campaignToSharedGloballyMap.put(campaignId, globallyShared);
        }
        return campaignToSharedGloballyMap;
    }

    /**
     * Collects the parent campaigns of the leads. For inserts, it collects all leads;
     * for updates, it collects only those where the country field has changed.
     * @author hadib@salesforce.com | 03-10-2024
     * @param newLeads Map of new leads
     * @param oldLeads Map of old leads
     *
     * @return Set<Id> - Set of campaign Ids to process
     */
    public static Set<Id> collectCampaignsToProcess(Map<Id, Lead> newLeads, Map<Id, Lead> oldLeads) {
        Set<Id> campaignsToProcess = new Set<Id>();
        Set<Id> leadIdsToProcess = new Set<Id>();
        Lead oldLead;
        Lead newLead;
        // Loop through the new leads and check if we are in insert or update context
        for (Id leadId : newLeads.keySet())
        {
            newLead = newLeads.get(leadId);

            // If oldLead is null, it's an insert, so add the lead to process
            if (oldLeads == null) {
                leadIdsToProcess.add(leadId);
            }
            // If oldLead is not null (update), check if the Country field has changed
            else {
                oldLead = oldLeads.get(leadId);
                if (newLead.Country != oldLead.Country) {
                    leadIdsToProcess.add(leadId);
                }
            }
        }

        // Query the campaign members only for the leads we want to process
        if (!leadIdsToProcess.isEmpty()) {
            List<CampaignMember> campaignMembersLinked = [
                    SELECT CampaignId
                    FROM CampaignMember
                    WHERE LeadId IN :leadIdsToProcess
            ];

            // Add the CampaignId to the campaignsToProcess set
            for (CampaignMember cm : campaignMembersLinked) {
                campaignsToProcess.add(cm.CampaignId);
            }
        }

        return campaignsToProcess;
    }

    /**
     * It ensures that the newly converted Lead's information is reflected in associated campaign members.
     * @author unknown
     * @param oldLeadsValues old values
     * @param newLeadsValues new values
     */
    public static void updateCampaignMembers(Map<Id, Lead> oldLeadsValues, Map<Id, Lead> newLeadsValues)
    {
        Set<Id> leadIdSet = new Set<Id>();
        Set<Id> campaignIDSId = new Set<Id>();
        Map<Id, Lead> mapContactIdLead = new Map<Id,Lead>();
        Boolean leadHasBeenConverted = false;
        for(Lead newLead : newLeadsValues.values())
        {
            leadHasBeenConverted = newLead.IsConverted && !oldLeadsValues.get(newLead.Id).IsConverted; // Wasn't converted and became

            if(leadHasBeenConverted)
            {
                leadIdSet.add(newLead.ConvertedContactId);
                if(newLead.IDSCampaign__c != '')
                {
                    campaignIDSId.add(newLead.IDSCampaign__c);
                    mapContactIdLead.put(newLead.ConvertedContactId , newLead);
                }
            }
        }
        
        //Find all Campaign Members related to the converted leads
        if(leadIdSet.size()>0){
        	List<CampaignMember> cmList = [SELECT Id, SalesLead__c, Opportunity__c, VoucherCode__c, URL_Source__c, LeadId, Description__c, HasResponded, ContactId, Brand__c, CampaignId, Dealer__c,
                    Campaign.Brand__c
                                                FROM CampaignMember
                                                WHERE ContactId IN: leadIdSet AND Campaign.RecordType.DeveloperName =: 'Digital_Marketing_Campaign'];
        	Map<Id, CampaignMember> cmMap = new Map<Id, CampaignMember>(cmList);        
       		CampaignMemberTriggerHelper.convertMemberToSalesLeadOrOpportunity(cmList, cmMap, true);
        }
        if(leadIdSet.size()>0){
        	List<CampaignMember> cmList = [SELECT Id, SalesLead__c, Opportunity__c, LeadId, Lead.IDSVoucherCode__c, Lead.IDSURLSource__c, Lead.IDSBrand__c, Lead.IDSDescription__c, Lead.IDSDealer__c,
                                                Description__c, HasResponded, ContactId, Brand__c, CampaignId, Dealer__c, Campaign.Brand__c
                                            FROM CampaignMember
                                            WHERE ContactId IN: leadIdSet AND Campaign.RecordType.DeveloperName =: 'InPersonEventCampaign' AND CampaignId IN: campaignIDSId];
            for(integer i=0; i < cmList.size(); i++){
                cmList[i].VoucherCode__c = mapContactIdLead.get(cmList[i].ContactId).IDSVoucherCode__c;
                cmList[i].Brand__c = mapContactIdLead.get(cmList[i].ContactId).IDSBrand__c;
                cmList[i].Dealer__c = mapContactIdLead.get(cmList[i].ContactId).IDSDealer__c;
                cmList[i].Description__c = mapContactIdLead.get(cmList[i].ContactId).IDSDescription__c;
                cmList[i].URL_Source__c = mapContactIdLead.get(cmList[i].ContactId).IDSURLSource__c;
            }
            Map<Id, CampaignMember> cmMap = new Map<Id, CampaignMember>(cmList);
       		CampaignMemberTriggerHelper.convertMemberToSalesLeadOrOpportunity(cmList, cmMap, true);
        }
        
    }
}