src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Brands__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>3D Upgrade</fullName>
                </value>
                <value>
                    <fullName>ACB with ASA</fullName>
                </value>
                <value>
                    <fullName>AH Plus</fullName>
                </value>
                <value>
                    <fullName>AH Plus Bioceramic Sealer</fullName>
                </value>
                <value>
                    <fullName>AH Temp</fullName>
                </value>
                <value>
                    <fullName>AlginX</fullName>
                </value>
                <value>
                    <fullName>All Ceramics</fullName>
                </value>
                <value>
                    <fullName>All Other Endo</fullName>
                </value>
                <value>
                    <fullName>All Other - Niti Rotary Files</fullName>
                </value>
                <value>
                    <fullName>All Other – Obturation</fullName>
                </value>
                <value>
                    <fullName>Anaestadent</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>ANKYLOS</fullName>
                </value>
                <value>
                    <fullName>Apex Locator</fullName>
                </value>
                <value>
                    <fullName>Aquasil</fullName>
                </value>
                <value>
                    <fullName>Aquasil Ultra Plus</fullName>
                </value>
                <value>
                    <fullName>ATIS</fullName>
                </value>
                <value>
                    <fullName>ATIS EV</fullName>
                </value>
                <value>
                    <fullName>ATIS TX</fullName>
                </value>
                <value>
                    <fullName>Atlantis</fullName>
                </value>
                <value>
                    <fullName>Atlantis Abutments</fullName>
                </value>
                <value>
                    <fullName>Atlantis Suprastructures</fullName>
                </value>
                <value>
                    <fullName>Automate</fullName>
                </value>
                <value>
                    <fullName>Axano</fullName>
                </value>
                <value>
                    <fullName>Axeos</fullName>
                </value>
                <value>
                    <fullName>Azento Astra Tech</fullName>
                </value>
                <value>
                    <fullName>Azento EV</fullName>
                </value>
                <value>
                    <fullName>Azento XiVE</fullName>
                </value>
                <value>
                    <fullName>Bioceramic</fullName>
                </value>
                <value>
                    <fullName>Bioceramic Sealer</fullName>
                    <isActive>false</isActive>
                    <label>Bioceramic Sealer</label>
                </value>
                <value>
                    <fullName>Sinius</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Campaign_Country__c</fullName>
        <description>Country where the Campaign is taking place.</description>
        <inlineHelpText>Country where the Campaign is taking place.</inlineHelpText>
        <label>Campaign Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Holland</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
                <value>
                    <fullName>Hungary</fullName>
                </value>
                <value>
                    <fullName>Iceland</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
                <value>
                    <fullName>Mexico</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Convert_To__c</fullName>
        <label>Convert To:</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sales Lead</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Organizing Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ALL</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>BEX</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Distributor Markets</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Holland</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
                <value>
                    <fullName>HQ: DE</fullName>
                </value>
                <value>
                    <fullName>HQ: NL</fullName>
                </value>
                <value>
                    <fullName>HQ: SE</fullName>
                </value>
                <value>
                    <fullName>INDIA</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Kazakhstan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>Kuwait</fullName>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Morocco</fullName>
                </value>
                <value>
                    <fullName>New Zealand</fullName>
                </value>
                <value>
                    <fullName>Norway</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Campaign</fullName>
        <active>false</active>
        <description>All Campaigns excluding Symposia - Used by BeNeLux</description>
        <label>Campaign</label>
    </recordTypes>
    <recordTypes>
        <fullName>Digital_Marketing_Campaign</fullName>
        <active>true</active>
        <description>Used in Lightning for the Eloqua integration</description>
        <label>Digital Marketing Campaign</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Implants</fullName>
                    <label>Global DPG</label>
                </value>
                <value>
                    <fullName>All Ortho</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ATF</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
                <value>
                    <fullName>BHR</fullName>
                </value>
                <value>
                    <fullName>BHS</fullName>
                </value>
                <value>
                    <fullName>BIH</fullName>
                </value>
                <value>
                    <fullName>BLM</fullName>
                </value>
                <value>
                    <fullName>BLR</fullName>
                </value>
                <value>
                    <fullName>BLZ</fullName>
                </value>
                <value>
                    <fullName>BMU</fullName>
                </value>
                <value>
                    <fullName>BOL</fullName>
                </value>
                <value>
                    <fullName>BRA</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Test_StandardLeadTrigger.cls
/*------------------------------------------------------------
Author: 		Richard Trum 2021-02-23
Description:   	Test Class for all StandardLeadTrigger methods.
History
20210223   Richard Trum   	Created trigger framework
------------------------------------------------------------*/
@isTest(seeAllData=false)
public class Test_StandardLeadTrigger {

    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.createUsers(1, 'System Administrator');
        List<User> userIntegrationList = TestDataFactory.insertIntegrationUsers(1, 'System Administrator');
        TestDataFactory.createGlobalIntegrationSettings(userIntegrationList);
    }

    @isTest
    private static void testUpdateCampaignMembers() {
        
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];
        List<Account> accountsList = TestDataFactory.createAccounts(1, 'CIM_Account', testUser.Id);
        accountsList.get(0).Country__c = 'US';
        update accountsList;
        
        Lead l = new Lead();        
        l.Email = 'test1.test@dentsplysirona.com.invalid';
        l.FirstName = 'Test';
        l.LastName = 'Test';
		l.Status = 'New';
        l.Company = 'Test Customer';
        insert l;
        
        List<Campaign> campaignList = TestDataFactory.returnCampaigns(1, 'Digital_Marketing_Campaign', testUser.Id);
        campaignList.get(0).Brands__c = 'Sinius';
        campaignList.get(0).Convert_To__c = 'Sales Lead';
        insert campaignList;
        List<CampaignMember> campaignMembertList = TestDataFactory.returnCampaignMembers(1);

        campaignMembertList.get(0).LeadId = l.Id;
        campaignMembertList.get(0).CampaignId = campaignList.get(0).Id;
        campaignMembertList.get(0).Status = 'Responded';
        insert campaignMembertList;
        
		Test.startTest();
        	
        	Database.LeadConvert lc = new Database.LeadConvert();
        	LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
			lc.setConvertedStatus(convertStatus.MasterLabel);
        	lc.setAccountId(accountsList[0].Id);
        	lc.setDoNotCreateOpportunity(true);
        	lc.setLeadId(l.Id);
        	
        	//Convert lead
        	Database.LeadConvertResult lcr = Database.convertLead(lc, false);
        	
        Test.stopTest();        

    }

    /**
     * Ensures that the "SharedGlobally__c" field on Campaigns is correctly updated
     * when Leads linked to the Campaigns have a different or matching Country.
     * @author hadib@salesforce.com | 09-10-2024
     * Test Cases:
     * 1. Lead with the same country as the Campaign should not change the flag.
     * 2. Lead with a different country should mark the Campaign as "SharedGlobally__c = true".
     * 3. Reverting the Lead's country should maintain the correct state of the flag.
     */
    @IsTest
    private static void testProcessLeads()
    {
        // Create test user
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        System.runAs(testUser)
        {
            // Start test context
            Test.startTest();

            // Create a test Campaign with a specific country
            Campaign testCampaign = new Campaign(
                    Name = 'Test Campaign',
                    Campaign_Country__c = 'USA',
                    SharedGlobally__c = false,
                    RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Digital_Marketing_Campaign' LIMIT 1].Id
            );
            insert testCampaign;

            // Create a Lead that has the same country as the Campaign
            Lead leadSameCountry = new Lead(
                    FirstName = 'John',
                    LastName = 'Doe',
                    Company = 'Test Company',
                    Country = 'USA'
            );
            insert leadSameCountry;

            // Create a CampaignMember linking the Lead to the Campaign
            CampaignMember campaignMemberSameCountry = new CampaignMember(
                    LeadId = leadSameCountry.Id,
                    CampaignId = testCampaign.Id
            );
            insert campaignMemberSameCountry;

            // Now, create a Lead with a different country than the Campaign
            Lead leadDifferentCountry = new Lead(
                    FirstName = 'Jane',
                    LastName = 'Smith',
                    Company = 'Another Company',
                    Country = 'Canada'
            );
            insert leadDifferentCountry;

            // Create a CampaignMember linking the Lead with the different country to the same Campaign
            CampaignMember campaignMemberDifferentCountry = new CampaignMember(
                    LeadId = leadDifferentCountry.Id,
                    CampaignId = testCampaign.Id
            );
            insert campaignMemberDifferentCountry;

            // Now update the leads in a way that triggers the logic (same country stays, different country is added)
            leadSameCountry.Country = 'Mexico'; // Change the country to be different
            update leadSameCountry;

            // Trigger logic is invoked, now check the Campaign
            Campaign updatedCampaign = [SELECT Id, SharedGlobally__c FROM Campaign WHERE Id = :testCampaign.Id];
            System.assertEquals(true, updatedCampaign.SharedGlobally__c, 'The campaign should now be marked as Shared Globally due to country mismatch.');

            // Reset the lead back to same country
            leadSameCountry.Country = 'USA'; // Match back to campaign country
            update leadSameCountry;

            // Recheck the Campaign
            updatedCampaign = [SELECT Id, SharedGlobally__c FROM Campaign WHERE Id = :testCampaign.Id];
            System.assertEquals(true, updatedCampaign.SharedGlobally__c, 'The campaign should remain shared globally due to the other lead being different.');

            // Clean up test data
            Test.stopTest();
        }
    }

}