src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Parent_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used on sessions to show what Campaign is the parent Campaign</description>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Campaign</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Campaign</fullName>
        <active>false</active>
        <description>All Campaigns excluding Symposia - Used by BeNeLux</description>
        <label>Campaign</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CventEvents__Attendee__c.object
<CustomObject>
    <description>Represents the attendee of an event.</description>
    <fields>
        <fullName>CventEvents__Attended__c</fullName>
        <description>Represents whether the Attendee participated Event or not.</description>
        <label>Attended</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CventEvents__AttendeeName__c</fullName>
        <formula>IF(ISBLANK(CventEvents__Lead__c),
        HYPERLINK(&quot;/&quot; &amp; CventEvents__Contact__r.FirstName + &quot; &quot; + CventEvents__Contact__r.LastName, &quot;&quot;)
        &amp; HYPERLINK(&quot;/&quot; &amp; CventEvents__Contact__c, CventEvents__Contact__r.FirstName + &quot; &quot; + CventEvents__Contact__r.LastName),
        HYPERLINK(&quot;/&quot; &amp; CventEvents__Lead__r.FirstName + &quot; &quot; + CventEvents__Lead__r.LastName, &quot;&quot;)
        &amp; HYPERLINK(&quot;/&quot; &amp; CventEvents__Lead__c, CventEvents__Lead__r.FirstName + &quot; &quot; + CventEvents__Lead__r.LastName))</formula>
        <label>Attendee Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CventEvents__AttendeeStub__c</fullName>
        <externalId>true</externalId>
        <label>Attendee Stub</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CventEvents__Company__c</fullName>
        <description>Represents either the related contact&apos;s account name or lead&apos;s company.</description>
        <formula>IF(ISBLANK(CventEvents__Lead__c), CventEvents__Contact__r.Account.Name, CventEvents__Lead__r.Company)</formula>
        <inlineHelpText>Represents either the related contact&apos;s account name or lead&apos;s company.</inlineHelpText>
        <label>Company</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CventEvents__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Events Participation</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CventEvents__CurrencyCode__c</fullName>
        <formula>CventEvents__Event__r.CventEvents__pkg_CurrencyCode__c</formula>
        <label>Currency Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CventEvents__CurrencyName__c</fullName>
        <formula>CventEvents__Event__r.CventEvents__pkg_CurrencyName__c</formula>
        <label>Currency Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CventEvents__Email__c</fullName>
        <formula>IF(ISBLANK(CventEvents__Lead__c), CventEvents__Contact__r.Email, CventEvents__Lead__r.Email)</formula>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CventEvents__EventCheckInDate__c</fullName>
        <label>Event Check-In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CventEvents__EventStartDate__c</fullName>
        <formula>CventEvents__Event__r.CventEvents__pkg_StartDate__c</formula>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CventEvents__EventStartTime__c</fullName>
        <formula>CventEvents__Event__r.CventEvents__pkg_StartTime__c</formula>
        <label>Event Start Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>CventEvents__EventTimeZone__c</fullName>
        <formula>CventEvents__Event__r.CventEvents__pkg_TimeZone__c</formula>
        <label>Event Time Zone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CventEvents__EventTitle__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp; CventEvents__Event__r.CventEvents__pkg_Title__c, &quot;&quot;) &amp; HYPERLINK(&quot;/&quot; &amp; CventEvents__Event__c, CventEvents__Event__r.CventEvents__pkg_Title__c)</formula>
        <label>Event</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CventEvents__Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Number</label>
        <referenceTo>CventEvents__Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CventEvents__IsFreeloader__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Represents whether the Attendee is guest or not.</description>
        <label>Guest</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CventEvents__IsGroupLeader__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Group Leader</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CventEvents__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Events Participation</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CventEvents__Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Visited</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Denied Approval</fullName>
                </value>
                <value>
                    <fullName>Invitation Not Sent</fullName>
                </value>
                <value>
                    <fullName>Invitation Pending</fullName>
                </value>
                <value>
                    <fullName>Nomination Pending</fullName>
                </value>
                <value>
                    <fullName>Nomination Approved</fullName>
                </value>
                <value>
                    <fullName>Nomination Denied</fullName>
                </value>
                <value>
                    <fullName>Nomination Cancelled</fullName>
                </value>
                <value>
                    <fullName>Substituted</fullName>
                </value>
                <value>
                    <fullName>Registration Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CventEvents__UnsubscribedFromEvent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unsubscribed From Event</label>
        <type>Checkbox</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CventEvents__AttendeeTemp__c.object
<CustomObject>
    <description>Auxiliary object used for storing a fusion of contact and event participation information retrieved from Cvent.</description>
    <fields>
        <fullName>CventEvents__pkg_Attended__c</fullName>
        <description>Represents whether the Attendee participated Event or not.</description>
        <label>Attended</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CventEvents__pkg_AttendeeStatus__c</fullName>
        <label>Attendee Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CventEvents__pkg_AttendeeStub__c</fullName>
        <externalId>true</externalId>
        <label>Attendee Stub</label>
        <length>36</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CventEvents__pkg_ContactTypeName__c</fullName>
        <label>Contact Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CventEvents__pkg_EventStub__c</fullName>
        <externalId>true</externalId>
        <label>Event Stub</label>
        <length>36</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Attendee Temp Record</label>
    <nameField>
        <displayFormat>AT-{00000000}</displayFormat>
        <label>Attendee Temp Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendee Temp Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CventEvents__Event__c.object
<CustomObject>
    <description>Represents the event defined in Cvent.</description>
    <fields>
        <fullName>CventEvents__pkg_Code__c</fullName>
        <label>Code</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CventEvents__pkg_EventStub__c</fullName>
        <externalId>true</externalId>
        <label>Event Stub</label>
        <length>36</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cvent Event</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cvent Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CventEvents__EventCampaignEntry__c.object
<CustomObject>
    <description>Junction object between Event and Campaign that is used to support many-to-many relationship.</description>
    <fields>
        <fullName>CventEvents__Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Cvent Events</relationshipLabel>
        <relationshipName>EventCampaignEntries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CventEvents__Event__c</fullName>
        <label>Event</label>
        <referenceTo>CventEvents__Event__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>EventCampaignEntries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Event Campaign Entry</label>
    <nameField>
        <displayFormat>ECE-{00000000}</displayFormat>
        <label>Event Campaign Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Campaign Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DynamicMapping__mdt.object
<CustomObject>
    <description>It provides a way to map the fields of one object to another, allowing for the seamless transfer of data between the two objects</description>
    <fields>
        <fullName>SourceFieldApiName__c</fullName>
        <description>SourceObjectApiName.SourceFieldApiName will be mapped to TargetObjectApiName.TargetFieldApiName</description>
        <inlineHelpText>SourceObjectApiName.SourceFieldApiName will be mapped to TargetObjectApiName.TargetFieldApiName</inlineHelpText>
        <label>Source Field Api Name</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TargetFieldApiName__c</fullName>
        <description>SourceObjectApiName.SourceFieldApiName will be mapped to TargetObjectApiName.TargetFieldApiName</description>
        <inlineHelpText>SourceObjectApiName.SourceFieldApiName will be mapped to TargetObjectApiName.TargetFieldApiName</inlineHelpText>
        <label>Target Field Api Name</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Dynamic Mapping</label>
    <pluralLabel>Dynamic Mappings</pluralLabel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>AttendeeStub__c</fullName>
        <description>Cvent Application Attendee Stub</description>
        <externalId>true</externalId>
        <label>Attendee Stub</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/CventManagement.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Houssam ADIB (Salesforce)
Description:    Cvent Management Class
Test class:     MappingManagementTest

History
20-03-2023     Houssam ADIB - Create new class
29-01-2024     Houssam ADIB - TFUS-000006858 - Map new fields from Temp to attendee ( static mapping ) and fix contact type not flowing
----------------------------------------------------------------------------------------*/
public without sharing class CventManagement {

    public static final String SOURCE_OBJECT_EVENT      = 'CventEvents__Event__c';
    public static final String TARGET_OBJECT_CAMPAIGN   = 'Campaign';

    public static final String SOURCE_OBJECT_TEMP       = 'CventEvents__AttendeeTemp__c';
    public static final String TARGET_OBJECT_LEAD       = 'Lead';

    public static final String CONVERTED_TO_LEAD       = 'Converted to Lead';

    /**
     * Searches for the Cvent Event record using the code field (CventEvents__pkg_Code__c)
     * @author hadib@salesforce.com | 20-03-2023
     *
     * @param cventCode             The Cvent Event Code
     *
     * @return List<CventEvents__Event__c> - Query Result
     */
    public static List<CventEvents__Event__c> findCventByCode(String cventCode)
    {
        List<CventEvents__Event__c> events = new List<CventEvents__Event__c>();
        events = [  SELECT Id,CventEvents__pkg_EventStub__c FROM CventEvents__Event__c
        WHERE CventEvents__pkg_Code__c = :cventCode];

        return events;
    }

    /**
     * Retrieve Matched Attendees for a particular event
     * @author hadib@salesforce.com | 20-03-2023
     *
     * @param sourceCvent Event
     *
     * @return Map<String,List<CventEvents__Attendee__c> - Map of attendees to their attendee stubs
     */
    public static Map<String,CventEvents__Attendee__c> getMatchedAttendees(CventEvents__Event__c sourceCvent)
    {
        Map<String,CventEvents__Attendee__c>  matchedAttendeesMap = new Map<String,CventEvents__Attendee__c>();

        for(CventEvents__Attendee__c attendee : [
                SELECT Id, Name, CventEvents__AttendeeName__c, CventEvents__AttendeeStub__c,
                        CventEvents__Company__c, CventEvents__CurrencyCode__c, CventEvents__CurrencyName__c,
                        CventEvents__Status__c, CventEvents__Email__c, CventEvents__EventStartDate__c,
                        CventEvents__EventStartTime__c, CventEvents__EventCheckInDate__c,
                        CventEvents__EventTimeZone__c, CventEvents__EventTitle__c, CventEvents__Event__c,
                        CventEvents__Lead__c, CventEvents__IsFreeloader__c, CventEvents__IsGroupLeader__c,
                        CventEvents__UnsubscribedFromEvent__c, CventEvents__Contact__c, CventEvents__Attended__c, ContactType__c
                FROM CventEvents__Attendee__c
                WHERE CventEvents__Event__c = :sourceCvent.Id])
        {
            matchedAttendeesMap.put(attendee.CventEvents__AttendeeStub__c,attendee);
        }

        return matchedAttendeesMap;
    }

    /**
     * Find exising Leads generated for unmatched attendees
     * @author hadib@salesforce.com | 20-03-2023
     *
     * @return Map<String, Lead> - Maps stub to lead
     */
    public static Map<String, Lead> getStubToLead()
    {
        List<Lead> existingLeads = [SELECT Id, AttendeeStub__c FROM Lead WHERE AttendeeStub__c != NULL      ];
        Map<String, Lead> stubToLead = new Map<String, Lead>();
        Lead lead;
        for (Integer i = 0, j = existingLeads.size(); i < j; i++) {
            lead = existingLeads[i];
            stubToLead.put(lead.AttendeeStub__c, lead);
        }
        return stubToLead;
    }

    /**
     * Links the event with its generated campaign record
     * @author hadib@salesforce.com | 20-03-2023
     *
     * @param eventId       event Id
     * @param campaignId    campaign Id
     */
    public static void linkCampaignWithEvent(Id eventId, Id campaignId)
    {
        CventEvents__EventCampaignEntry__c link = new CventEvents__EventCampaignEntry__c();
        link.CventEvents__Event__c = eventId;
        link.CventEvents__Campaign__c = campaignId;
        insert link;
    }

    /**
     * Convert Unmatched Attendees to Leads
     * Makes sure not to duplicate leads using old existing stubToLead map
     * @author hadib@salesforce.com | 20-03-2023
     *
     * @param unmatchedAttendees            unmatched Attendees
     * @param newTempsConvertedToLeads      new unmatched Attendees converted to leads
     * @param sourceCvent                   Event
     * @param mappings                      Fields Mapping (mdt)
     * @param stubToLead                    AttendeeStub -> Lead Map
     * @param eventCampaigns                Existing converted campaign
     * @param attendeeWrappers              Attendees Wrappers
     *
     * @return List<Lead> - New Leads
     */
    public static List<Lead> InstantiateLeadsForUnmatchedTemps(     List<CventEvents__AttendeeTemp__c> unmatchedAttendees,
                                                                    List<CventEvents__AttendeeTemp__c> newTempsConvertedToLeads,
                                                                    CventEvents__Event__c sourceCvent,
                                                                    List<DynamicMapping__mdt> mappings,
                                                                    Map<String,Lead> stubToLead,
                                                                    Map<String,Campaign> eventCampaigns,
                                                                    List<AttendeeWrapper> attendeeWrappers )
    {
        List<Lead> newLeads = new List<Lead>();
        CventEvents__AttendeeTemp__c temp;
        Id leadRecordType = GlobalUtils.getRecordTypeId('Lead', 'CVENT_Lead');

        for (Integer i = 0, j = unmatchedAttendees.size(); i < j; i++)
        {
            // Wrappers will be used to generate attendees & members
            temp = unmatchedAttendees[i];
            AttendeeWrapper attendeeWrapper = new AttendeeWrapper();
            attendeeWrapper.event = sourceCvent;
            attendeeWrapper.matched = false;
            attendeeWrapper.tempAttendee = temp;

            if(stubToLead.containsKey(temp.CventEvents__pkg_AttendeeStub__c))
            {
                // If we already have one in the database generated before
                attendeeWrapper.lead = stubToLead.get(temp.CventEvents__pkg_AttendeeStub__c);
                if (temp.MatchStatus__c != CONVERTED_TO_LEAD)
                {
                    temp.MatchStatus__c = CONVERTED_TO_LEAD;
                    newTempsConvertedToLeads.add(temp);
                }
            }
            else
            {
                // Never been generated before, We create a new lead
                DynamicMapping__mdt mapping;
                Lead lead = new Lead();
                lead.Status = 'New';
                lead.RecordTypeId = leadRecordType;

                if(eventCampaigns.containsKey(sourceCvent.CventEvents__pkg_EventStub__c))
                {
                    lead.OwnerId = eventCampaigns.get(sourceCvent.CventEvents__pkg_EventStub__c).OwnerId;
                }

                // For each mapping, we get a field value and put it in the lead
                for (Integer x = 0, y = mappings.size(); x < y; x++)
                {
                    mapping = mappings[x];
                    Object targetValue = temp.get(mapping.SourceFieldApiName__c);
                    lead.put(mapping.TargetFieldApiName__c, targetValue);
                }

                lead.AttendeeStub__c = temp.CventEvents__pkg_AttendeeStub__c; // System field required not brought from mappings
                newLeads.add(lead);

                temp.MatchStatus__c = CONVERTED_TO_LEAD;
                newTempsConvertedToLeads.add(temp);

                attendeeWrapper.lead = lead;
            }

            attendeeWrappers.add(attendeeWrapper);
        }
        return newLeads;
    }


    /**
     * Partition And Process Wrappers to end up with 2 Lists:
     * 1-List of new attendees to insert (newAttendees)
     * 2-List of attendees that needs to be recreated to trigger campaign members creation by cvent app
     * @author hadib@salesforce.com | 20-03-2023
     *
     * @param attendeeWrappers                  Input:  Attendees Wrappers
     * @param attendeesToReCreateInLaterStage   Output: Attendees to recreate
     * @param newAttendees                      Output: Attendees to insert
     */
    public static void partitionAndProcessWrapper(List<AttendeeWrapper> attendeeWrappers, List<CventEvents__Attendee__c> attendeesToReCreateInLaterStage, List<CventEvents__Attendee__c> newAttendees)
    {
        AttendeeWrapper wrapper;

        for (Integer i = 0, j = attendeeWrappers.size(); i < j; i++)
        {
            wrapper = attendeeWrappers[i];

            CventEvents__Attendee__c attendee = new CventEvents__Attendee__c();
            if (!wrapper.matched)
            {
                // Create New Attendee for unmatched Temps. (+Static Cvent Fields.)
                attendee.CventEvents__Lead__c           = wrapper.lead.Id;
                attendee.CventEvents__Event__c          = wrapper.event.Id;
                attendee.CventEvents__Status__c         = wrapper.tempAttendee.CventEvents__pkg_AttendeeStatus__c;
                attendee.CventEvents__AttendeeStub__c   = wrapper.tempAttendee.CventEvents__pkg_AttendeeStub__c;
                attendee.CventEvents__Attended__c       = wrapper.tempAttendee.CventEvents__pkg_Attended__c;
                attendee.ContactType__c                 = wrapper.tempAttendee.CventEvents__pkg_ContactTypeName__c;
                attendee.IntraoralScannerInUse__c       = wrapper.tempAttendee.Doyouhaveanintraoralscannerinyour__c;
                attendee.SolutionsInterest__c           = wrapper.tempAttendee.Whichsolutionsareyouinterestedin__c;
            }
            else
            {
                // Clone deletes ones
                attendee = (wrapper.attendee).clone(false, true);
                attendeesToReCreateInLaterStage.add(wrapper.attendee);
            }
            newAttendees.add(attendee);
        }
    }

    /**
     * Triggers the conversion of Temp Records to Lead+Attendee for an event
     * @param stubToConvertedCampaign       Campaigns generated in a map by Event Stub
     * @param stubToEvent                   Events converted in a map by Event Stub
     * @param eventAndNewTempAttendees      Map of Converted Events To their unmatched Temps needing conversion to lead+attendee
     */
    public static void convertUnmatchedTempsToLeadsAndAttendees(Map<String, Campaign> stubToConvertedCampaign,
                                                                Map<String, CventEvents__Event__c> stubToEvent,
                                                                Map<String,List<CventEvents__AttendeeTemp__c>> eventAndNewTempAttendees)
    {
        if (!eventAndNewTempAttendees.isEmpty())
        {
            // Find existing leads by stub in case we already generated leads for temps
            Map<String, Lead> stubToLead = CventManagement.getStubToLead();

            List<DynamicMapping__mdt> mappings = MappingManagement.getMapping(CventManagement.SOURCE_OBJECT_TEMP, CventManagement.TARGET_OBJECT_LEAD,false);

            List<AttendeeWrapper> attendeeWrappers = new List<AttendeeWrapper>();
            List<Lead> newLeads = new List<Lead>();
            List<CventEvents__Attendee__c> newAttendees = new List<CventEvents__Attendee__c>();
            List<CventEvents__AttendeeTemp__c> newTempsConvertedToLeads = new List<CventEvents__AttendeeTemp__c>();

            for (String eventStub : eventAndNewTempAttendees.keySet()) {
                List<CventEvents__AttendeeTemp__c> eventTemps = eventAndNewTempAttendees.get(eventStub);
                newLeads.addAll(CventManagement.InstantiateLeadsForUnmatchedTemps(eventTemps,                     // All the Event unmatched Temps
                        newTempsConvertedToLeads,       // new Temps Converted To Leads.
                        stubToEvent.get(eventStub),     // Event
                        mappings,                       // Fields Mappings
                        stubToLead,                     // Existing Leads to avoid duplicates
                        stubToConvertedCampaign,        // Will be used to get campaign information
                        attendeeWrappers               // Forms an output. Will be used to insert Attendees
                        ));
            }

            // New Leads Insertion
            insertLeads(newLeads);

            List<CventEvents__Attendee__c> attendeesToReCreateInLaterStage = new List<CventEvents__Attendee__c>();
            CventManagement.partitionAndProcessWrapper(
                    attendeeWrappers,                   // Wrappers as an input
                    attendeesToReCreateInLaterStage,    // No recreation in this context, we only process new unmatched temps attendees
                    newAttendees);                      // Will be populate with new attendees to insert

            // New Attendees Insertion
            insertAttendees(newAttendees);

            CventManagement.updateTempStatus(newTempsConvertedToLeads);
        }
    }

    /**
     * Inserts New Leads
     * @author hadib@salesforce.com | 20-03-2023
     *
     * @param newLeads New Leads
     */
    public static void insertLeads(List<Lead> newLeads)
    {
        try {
            if (!newLeads.isEmpty()) {
                insert newLeads;
            }
        }
        catch (Exception e) {
            DebugLog.addException(e, 'CventManagement.triggerConvertTempAttendeesToLeads.Leads');
        }
    }

    /**
     * Inserts New Attendees
     * @author hadib@salesforce.com | 20-03-2023
     *
     * @param newAttendees  New Attendees
     */
    public static void insertAttendees(List<CventEvents__Attendee__c> newAttendees)
    {
        try {
            if (!newAttendees.isEmpty()) {
                insert newAttendees;
            }
        }
        catch (Exception e) {
            DebugLog.addException(e, 'CventManagement.triggerConvertTempAttendeesToLeads.Attendees');
        }
    }

    /**
    * Assort the map of Temp to a new map (EventStub -> List of child Temps)
    * @author hadib@salesforce.com | 20-03-2023
    *
    * @param unmatchedTemps Map of Temp Attendees
    *
    * @return Map<String, List<CventEvents__AttendeeTemp__c>> - Temp record to process
    */
    public static Map<String, List<CventEvents__AttendeeTemp__c>> assortByEventStub(List<CventEvents__AttendeeTemp__c>  unmatchedTemps)
    {
        Map<String, List<CventEvents__AttendeeTemp__c>> eventStubToTempAttendees = new Map<String, List<CventEvents__AttendeeTemp__c>>();

        CventEvents__AttendeeTemp__c temp;
        for (Integer i = 0, j = unmatchedTemps.size(); i < j; i++) {
            temp = unmatchedTemps[i];

            String key = temp.CventEvents__pkg_EventStub__c;
            if (eventStubToTempAttendees.containsKey(key)) {
                eventStubToTempAttendees.get(key).add(temp);
            }
            else {
                eventStubToTempAttendees.put(key, new List<CventEvents__AttendeeTemp__c>{temp});
            }
        }
        return eventStubToTempAttendees;
    }

    /**
     * Populate two maps with the converted event / campaigns
     * @author hadib@salesforce.com | 30-03-2023
     */
    public static void findConvertedEvents(Map<String, CventEvents__Event__c> stubToEvent, Map<String, Campaign> stubToConvertedCampaign)
    {
        CventEvents__EventCampaignEntry__c[] entries = [    SELECT   Id,CventEvents__Event__c,CventEvents__Campaign__c,
                                                                    CventEvents__Event__r.CventEvents__pkg_EventStub__c,
                                                                    CventEvents__Campaign__r.OwnerId
                                                            FROM    CventEvents__EventCampaignEntry__c ];

        // Gather all stubs in the entries
        for(CventEvents__EventCampaignEntry__c entry : entries)
        {
            stubToEvent.put(entry.CventEvents__Event__r.CventEvents__pkg_EventStub__c,entry.CventEvents__Event__r);
            stubToConvertedCampaign.put(entry.CventEvents__Event__r.CventEvents__pkg_EventStub__c,entry.CventEvents__Campaign__r);
        }
    }

    /**
     * Retrieves the existing attendees stubs for converted events
     * @author hadib@salesforce.com | 06-04-2023
     * @param convertedEventsStubs Set of converted events stubs
     *
     * @return Set of attendees stubs
     */
    public static Set<String> getExistingAttendeesStubForConvertedEvents(Set<String> convertedEventsStubs)
    {
        Set<String> existingAttendeesStubs = new Set<String>();

        List<CventEvents__Attendee__c> existingAttendees = [SELECT Id,CventEvents__AttendeeStub__c
                                                            FROM CventEvents__Attendee__c
                                                            WHERE CventEvents__Event__r.CventEvents__pkg_EventStub__c IN :convertedEventsStubs];

        CventEvents__Attendee__c attendee;
        for (CventEvents__Attendee__c existingAttendee : existingAttendees)
        {
            attendee = existingAttendee;
            if(attendee.CventEvents__AttendeeStub__c != null)
            {
                existingAttendeesStubs.add(attendee.CventEvents__AttendeeStub__c);
            }
        }

        return existingAttendeesStubs;
    }

    /**
     * Sets MatchStatus__c for the temp record and set it to 'Converted to Lead' Was set in InstantiateLeadsForUnmatchedTemps function
     * @author hadib@salesforce.com | 01-11-2023
     *
     * @param newTempsConvertedToLeads new Temps Converted To Leads
     */
    public static void updateTempStatus(List<CventEvents__AttendeeTemp__c> newTempsConvertedToLeads)
    {
        try {
            update newTempsConvertedToLeads;
        }
        catch (Exception e) {
            DebugLog.addException(e, 'quickCreateCampaignFromCventController.updateTempStatus');
        }
    }

    /**
     * Switch On or Off the isConverted__c checkbox on the Cvent Event Record based on their conversion state
     * @author hadib@salesforce.com | 01-11-2023
     *
     * @param entries       Event Campaign Entry record
     * @param isConverted   Value to put on isConverted field on the parent event
     */
    public static void tickParentEventAs(List<CventEvents__EventCampaignEntry__c> entries, Boolean isConverted)
    {
        Set<Id> eventIds = new Set<Id>();

        for (CventEvents__EventCampaignEntry__c entry : entries) {
            eventIds.add(entry.CventEvents__Event__c);
        }

        List<CventEvents__Event__c> eventsToUpdate = [SELECT Id, IsConverted__c FROM CventEvents__Event__c WHERE Id IN :eventIds];

        for (CventEvents__Event__c event : eventsToUpdate) {
            event.IsConverted__c = isConverted;
        }

        if (!eventsToUpdate.isEmpty()) {
            try {
                update eventsToUpdate;
            }
            catch (Exception e) {
                DebugLog.addException(e,'Error in updating events "Is converted" field.');
            }
        }
    }
}