src/objects/Contract.object
<CustomObject>
    <recordTypes>
        <fullName>Contract</fullName>
        <active>true</active>
        <description>Intended to be the global contract record type - first version is a very basic contract launched in BeNeLux</description>
        <label>Contract</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ContractLineItem.object
<CustomObject>
    <fields>
        <fullName>DEPUniqueKey__c</fullName>
        <externalId>true</externalId>
        <label>DEP Unique Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Implants</fullName>
                    <label>Global DPG</label>
                </value>
                <value>
                    <fullName>All Ortho</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ATF</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
                <value>
                    <fullName>BHR</fullName>
                </value>
                <value>
                    <fullName>BHS</fullName>
                </value>
                <value>
                    <fullName>BIH</fullName>
                </value>
                <value>
                    <fullName>BLM</fullName>
                </value>
                <value>
                    <fullName>BLR</fullName>
                </value>
                <value>
                    <fullName>BLZ</fullName>
                </value>
                <value>
                    <fullName>BMU</fullName>
                </value>
                <value>
                    <fullName>BOL</fullName>
                </value>
                <value>
                    <fullName>BRA</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Company_Code__c</fullName>
        <description>The Company Code as written in the GDW</description>
        <inlineHelpText>The Company Code as written in the GDW</inlineHelpText>
        <label>Company Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPP_Code__c</fullName>
        <inlineHelpText>Global Product Platform Code</inlineHelpText>
        <label>GPP Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GlobalSKUMapping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GlobalSKU Mapping</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Mapped LocalSKUs</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PG2_Code__c</fullName>
        <label>Product Group 2 Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceContract.object
<CustomObject>
    <fields>
        <fullName>DEPUniqueKey__c</fullName>
        <externalId>true</externalId>
        <label>DEP Unique Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>ServiceContract</fullName>
        <active>true</active>
        <description>Standard record type used by integration of contracts/subscriptions as well</description>
        <label>Service Contract</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Source_Record__c.object
<CustomObject>
    <description>Includes Accounts from different sources mapped to one golden account. Fully integrated ( Read Only for all users)</description>
    <fields>
        <fullName>Atlantis_Web_Order_Customer__c</fullName>
        <description>Shows the Atlantis Web Order customer Number from ERP. Temporary solution until AWO is included as own source record.</description>
        <label>Atlantis Web Order Customer</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CIM_Account__c</fullName>
        <label>CIM Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Source Records</relationshipLabel>
        <relationshipName>Source_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <label>Company Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Id__c</fullName>
        <label>Source Id</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>63</fullName>
                    <label>CRM Data, External CRM Data</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>BPCS</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>M3</label>
                </value>
                <value>
                    <fullName>30</fullName>
                    <label>Distributors</label>
                </value>
                <value>
                    <fullName>62</fullName>
                    <label>Ecommerce</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>AX</label>
                </value>
                <value>
                    <fullName>31</fullName>
                    <label>SAP</label>
                </value>
                <value>
                    <fullName>60</fullName>
                    <label>SFDC</label>
                </value>
                <value>
                    <fullName>64</fullName>
                    <label>SIROFORCE</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SuresmileAlignerPlatform__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Information collected from Customer Interfaces table in AX (related table to Accounts) - set to true if an active record exists as Suresmile Aligner</description>
        <inlineHelpText>Information collected from Customer Interfaces table in AX (related table to Accounts) - set to true if an active record exists as Suresmile Aligner</inlineHelpText>
        <label>Suresmile Aligner Platform</label>
        <type>Checkbox</type>
    </fields>
    <label>Source Record</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_AccountFlagsController.cls
/**
 * @Author          Omar (ohanafi@salesforce.com)
 * @Description     Test class of AccountFlagsController
 *
 * @History
 * 16-08-2023   Omar     Created test class
 */

@isTest(seeAllData=false)
public without sharing class Test_AccountFlagsController {

    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.returnUsers(1, '#System: System Administrator');
        insert userList;
        TestDataFactory.createGlobalIntegrationSettings(userList);
        TestDataFactory.createDefaultOrgLevelBypassPB();

    }

    @isTest
    private static void testGetAccountFlagsJSON() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        System.runAs(testUser) {

            // Create test account
            List<Account> testAccount = TestDataFactory.returnAccounts(1, 'CIM_Account', testUser.Id);
            testAccount[0].Country__c = 'US';
            insert testAccount;

            // Create test custom pricebook
            List<Pricebook2> testPricebook = TestDataFactory.returnPricebooks(1, 'Test Price Book');
            testPricebook[0].IsActive = true;

            insert testPricebook[0];

            // Create test Service Contracts
            ServiceContract activeContract = new ServiceContract(
                    Name = 'Active Contract',
                    AccountId = testAccount[0].Id,
                    StartDate = Date.today().addDays(-30),
                    EndDate = Date.today().addDays(30),
                    Pricebook2Id = testPricebook[0].Id
            );

            ServiceContract expiredContract = new ServiceContract(
                    Name = 'Expired Contract',
                    AccountId = testAccount[0].Id,
                    StartDate = Date.today().addDays(-30),
                    EndDate = Date.today().addDays(-25),
                    Pricebook2Id = testPricebook[0].Id
            );

            insert new List<ServiceContract>{activeContract, expiredContract};

            // Create test Global SKU Mapping
            List<Product2> skuList = TestDataFactory.returnProducts(2);
            skuList[0].PG2_Code__c = 'DC10';
            skuList[1].GPP_Code__c = 'DT';
            insert skuList;

            // Create test products
            List<Product2> testProducts = TestDataFactory.returnProducts(2);
            testProducts[0].GlobalSKUMapping__c = skuList[0].Id;
            testProducts[1].GlobalSKUMapping__c = skuList[1].Id;
            insert testProducts;

            // Create test pricebook entry
            List<PricebookEntry> testPricebookEntries = TestDataFactory.returnPricebookEntries(2, testPricebook, testProducts);
            testPricebookEntries[0].UnitPrice = 100;
            testPricebookEntries[0].IsActive = true;
            testPricebookEntries[1].UnitPrice = 100;
            testPricebookEntries[1].IsActive = true;

            insert testPricebookEntries;

            // Create test Contract Line Item Records
            ContractLineItem testActiveContractLineItem = new ContractLineItem(
                    ServiceContractId = activeContract.Id,
                    StartDate = Date.today().addDays(-1),
                    EndDate = Date.today().addDays(1),
                    PricebookEntryId = testPricebookEntries[0].Id,
                    Quantity = 1,
                    UnitPrice = 100,
                    DEPUniqueKey__c = 'TEST'
            );
            ContractLineItem testExpiredContractLineItem = new ContractLineItem(
                    ServiceContractId = expiredContract.Id,
                    StartDate = Date.today().addDays(-2),
                    EndDate = Date.today().addDays(-1),
                    PricebookEntryId = testPricebookEntries[1].Id,
                    Quantity = 1,
                    UnitPrice = 100,
                    DEPUniqueKey__c = 'TST'
            );

            insert new List<ContractLineItem>{testActiveContractLineItem, testExpiredContractLineItem};

            // Create test Source Records
            List<Source_Record__c> testSourceRecords = TestDataFactory.returnSourceRecords(1);

            testSourceRecords[0].CIM_Account__c = testAccount[0].Id;
            testSourceRecords[0].Status__c = 'Active';
            testSourceRecords[0].Company_Code__c = 'BUYDS';
            testSourceRecords[0].SuresmileAlignerPlatform__c = true;
            testSourceRecords[0].Atlantis_Web_Order_Customer__c = 'AWO';
            testSourceRecords[0].Source_Id__c = '64';

            insert testSourceRecords[0];


            Test.startTest();

            String flagsJSON = AccountFlagsController.getAccountFlagsJSON(testAccount[0].Id);

            Test.stopTest();

            Map<String, Object> flagMap = (Map<String, Object>) JSON.deserializeUntyped(flagsJSON);

            Assert.areEqual(1, ((Map<String, Object>) flagMap.get('awo')).get('level'));
            Assert.areEqual(1, ((Map<String, Object>) flagMap.get('dsCom')).get('level'));
            Assert.areEqual(2, ((Map<String, Object>) flagMap.get('dsCoreAccess')).get('level'));
            Assert.areEqual(1, ((Map<String, Object>) flagMap.get('dsCoreCare')).get('level'));
        }
    }
}