src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Discount_model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Discount model</label>
        <referenceTo>Discount_model__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ContractItem__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Items</relationshipLabel>
        <relationshipName>Contract_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>TEXT(Contract__r.Account.Country__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DiscountModel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Discount Model</label>
        <referenceTo>Discount_model__c</referenceTo>
        <relationshipLabel>Contract Items</relationshipLabel>
        <relationshipName>Contract_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GrowthDiscount__c</fullName>
        <label>Growth Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Growth__c</fullName>
        <label>Growth</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OfferedDiscount__c</fullName>
        <label>Offered Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PGsPurchasedDiscount__c</fullName>
        <label>PGs Purchased Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PGsPurchased__c</fullName>
        <label>PGs Purchased</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecommendedDiscount__c</fullName>
        <label>Recommended Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SegmentationDiscount__c</fullName>
        <label>Segmentation Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Segmentation__c</fullName>
        <label>Segmentation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TGAtlantisManuallyUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PG Atlantis Manually Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TGAtlantis__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PG Atlantis</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TGCBCTManuallyUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PG CBCT Manually Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TGCBCT__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PG CBCT</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TGImplantSystem__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PG ImplantSystem</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TGOssix__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PG Ossix</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TGPrimescanManuallyUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PG Primescan Manually Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TGPrimescan__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PG Primescan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TGSimplantManuallyUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PG Simplant Manually Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TGSimplant__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PG Simplant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TotalNetSales2YAgo__c</fullName>
        <label>Total Net Sales 2Y Ago</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalNetSalesDiscount__c</fullName>
        <label>Total Net Sales Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalNetSales__c</fullName>
        <label>Total Net Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ofYearsPurchasingFromDSDiscount__c</fullName>
        <label># of Years Purchasing From DS Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ofYearsPurchasingFromDS__c</fullName>
        <label># of Years Purchasing From DS</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Contract Item</label>
    <nameField>
        <label>Contract Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Implants</fullName>
                    <label>Global DPG</label>
                </value>
                <value>
                    <fullName>All Ortho</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ATF</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
                <value>
                    <fullName>BHR</fullName>
                </value>
                <value>
                    <fullName>BHS</fullName>
                </value>
                <value>
                    <fullName>BIH</fullName>
                </value>
                <value>
                    <fullName>BLM</fullName>
                </value>
                <value>
                    <fullName>BLR</fullName>
                </value>
                <value>
                    <fullName>BLZ</fullName>
                </value>
                <value>
                    <fullName>BMU</fullName>
                </value>
                <value>
                    <fullName>BOL</fullName>
                </value>
                <value>
                    <fullName>BRA</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Discount_model__c.object
<CustomObject>
    <description>Used for storing discount models related to Contracts</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Discount Model</label>
    <nameField>
        <label>Discount Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discount Model</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Discount_row__c.object
<CustomObject>
    <fields>
        <fullName>Allowed_discount__c</fullName>
        <label>Allowed discount</label>
        <precision>4</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Discount_Model__c</fullName>
        <label>Discount Model</label>
        <referenceTo>Discount_model__c</referenceTo>
        <relationshipLabel>Discount row</relationshipLabel>
        <relationshipName>Discount_row</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Discount_lever__c</fullName>
        <label>Discount lever</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Revenue: materials</fullName>
                </value>
                <value>
                    <fullName>Revenue: equipments &amp; instruments</fullName>
                </value>
                <value>
                    <fullName>Implant: materials</fullName>
                </value>
                <value>
                    <fullName>Implants: equipments &amp; instruments</fullName>
                </value>
                <value>
                    <fullName>Abutments: materials</fullName>
                </value>
                <value>
                    <fullName>Abutments: equipments &amp; instruments</fullName>
                </value>
                <value>
                    <fullName>Pooled implant order: Material</fullName>
                </value>
                <value>
                    <fullName>Pooled implant order: Equipment</fullName>
                </value>
                <value>
                    <fullName>Payment type</fullName>
                </value>
                <value>
                    <fullName>Segment base</fullName>
                </value>
                <value>
                    <fullName>Total Net Sales</fullName>
                </value>
                <value>
                    <fullName>Workflow coverage</fullName>
                </value>
                <value>
                    <fullName>Growth</fullName>
                </value>
                <value>
                    <fullName>Loyalty</fullName>
                </value>
                <value>
                    <fullName>E-commerce</fullName>
                </value>
                <value>
                    <fullName>Skonto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Equals__c</fullName>
        <label>Equals</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaxNumber__c</fullName>
        <label>Max Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MinNumber__c</fullName>
        <label>Min Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MinTotalSalesNet__c</fullName>
        <label>Min Total Sales Net</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TextMatchResult__c</fullName>
        <label>Text Match Result</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Allowed_discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Allowed discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Source_Record__c.object
<CustomObject>
    <description>Includes Accounts from different sources mapped to one golden account. Fully integrated ( Read Only for all users)</description>
    <fields>
        <fullName>DiscountModel__c</fullName>
        <label>Discount Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Source Record</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SimulateContractLineController.cls
public with sharing class SimulateContractLineController {
    

    @AuraEnabled
    public static ContractItem__c insertOrUpdateContractItem(ContractItem__c contractLine, Boolean isInsert) {
        try {
            if(isInsert == true){
                insert contractLine;
            } else {
                update contractLine;
            }
            return(contractLine);
        }
        catch (Exception e) {
            DebugLog.addException(e, 'SimulateContractLineController.contractLine');
            throw new AuraHandledException(e.getMessage());    
        }
    }

    @AuraEnabled
    public static ContractItem__c getContractItem(Id contractLineId) {
        //system.debug(contractItem);
        try {
            ContractItem__c contractItem = new ContractItem__c();
            contractItem = [SELECT Id, discountModel__r.MaxDiscountToOffer__c , TGAtlantisManuallyUpdated__c, TGCBCTManuallyUpdated__c, TGPrimescanManuallyUpdated__c, TGSimplantManuallyUpdated__c, TGAtlantis__c, TGCBCT__c, TGImplantSystem__c, TGOssix__c, TGPrimescan__c, TGSimplant__c, Contract__r.Status, Contract__r.AccountId, Segmentation__c, DiscountModel__c, SegmentationDiscount__c, TotalNetSales__c, TotalNetSales2YAgo__c, CurrencyIsoCode, TotalNetSalesDiscount__c, PGsPurchased__c, PGsPurchasedDiscount__c, Growth__c, GrowthDiscount__c, ofYearsPurchasingFromDS__c, ofYearsPurchasingFromDSDiscount__c, RecommendedDiscount__c, OfferedDiscount__c  FROM ContractItem__c WHERE Id =: contractLineId LIMIT 1];       
            return(contractItem);
        }
        catch (Exception e) {
            DebugLog.addException(e, 'SimulateContractLineController.contractLine');
            throw new AuraHandledException(e.getMessage());    
        }
    }

    @AuraEnabled
    public static List<ContractItem__c> getAlreadyAddedContractItems(Id contractId) {
        //system.debug(contractItem);
        try {
            List<ContractItem__c> contractItems = new List<ContractItem__c>();
            contractItems = [SELECT Name, Id  FROM ContractItem__c WHERE Contract__c =: contractId];       
            return(contractItems);
        }
        catch (Exception e) {
            DebugLog.addException(e, 'SimulateContractLineController.contractLine');
            throw new AuraHandledException(e.getMessage());    
        }
    }

    @AuraEnabled
    public static Discount_model__c getRelatedDiscount(Id discountModelId) {
        //system.debug(contractItem);
        try {
            Discount_model__c discountModel = new Discount_model__c();
            discountModel = [SELECT Id, MaxDiscountToOffer__c, Product__c, SAQLQuery__c, CompanyCodes__c, FirstLevelApproval__c, SecondLevelApproval__c, (SELECT Id, MinTotalSalesNet__c, TextMatchResult__c, Discount_lever__c, Allowed_discount__c, MaxNumber__c, MinNumber__c, Equals__c FROM Discount_row__r) FROM Discount_model__c WHERE Id =: discountModelId LIMIT 1];
            return(discountModel);
        }
        catch (Exception e) {
            DebugLog.addException(e, 'SimulateContractLineController.contractLine');
            throw new AuraHandledException(e.getMessage());    
        }
    }

    @AuraEnabled
    public static List<Discount_model__c> getDiscountModels( String accountId) {
        List<Discount_model__c> discountRecords = new List<Discount_model__c>();
        Account acc = new Account();
        acc = [SELECT country__c FROM Account WHERE id =: accountId LIMIT 1];
        discountRecords = [SELECT Id, MaxDiscountToOffer__c, Product__c, SAQLQuery__c, CompanyCodes__c, FirstLevelApproval__c, SecondLevelApproval__c, (SELECT Id, MinTotalSalesNet__c, TextMatchResult__c, Discount_lever__c, Allowed_discount__c, MaxNumber__c, MinNumber__c, Equals__c FROM Discount_row__r) FROM Discount_model__c WHERE Country__c =: acc.Country__c AND Active__c = true ];
        return(discountRecords);
    }

    @AuraEnabled
    public static List<Source_Record__c> getSorceRecords( String accountId,List<String> companyCodes) {
        List<Source_Record__c> sourceRecords = new List<Source_Record__c>();
        sourceRecords = [SELECT Id, Source_Id__c, Combined_Fields__c, Company_Code__c, Customer_Id__c FROM Source_Record__c WHERE CIM_Account__c =: accountId AND Status__c = 'Active' AND Company_Code__c IN :companyCodes ORDER BY Source_Id__c, Company_Code__c];
        system.debug(sourceRecords);
        return(sourceRecords);
    }




/*
    global class ContractSalesDataResponse {
        @InvocableVariable
        global Decimal salesResult;
        
        @InvocableVariable
        global Decimal implantsResult;       
    }

*/




    private static String[] findDatasetVersion(String datasetName){

        HttpRequest req = new HttpRequest();
        
        //Endpoint is built upon a Named Credential called Analytics
        String endpoint = 'callout:Analytics/services/data/v50.0/wave/datasets';
        endpoint = endpoint +'/'+datasetName;
        req.setEndpoint(endpoint);
        req.setHeader('Content-Type', 'application/json');

        //Auth token is collected from Auth. Provider called SalesforceAnalytics
        req.setHeader('Authorization', 'Bearer {!$SalesforceAnalytics.OAuthToken}'); 
        req.setMethod('GET');

        http http = new http();
        HttpResponse res = new HttpResponse();
        
        if (!Test.isRunningTest()) { 
            res = http.send(req);
        }
        else{
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(200);
            res.setBody('{"currentVersionId":"12345", "id":"56789", "createdBy":{"id":"00520000001BhymAAC","name":"Force Flow","profilePhotoUrl":"https://dentsplysirona--geo--c.documentforce.com/profilephoto/005/T"}}');
        }     

        Integer calloutStatus = res.getStatusCode();
        List<String> result = new List<String>{};

        //Handle response
        if(calloutStatus == 200){
            Map<String, Object> results = (Map<String, Object>) 
            JSON.deserializeUntyped(res.getBody());
            Map<String,Object> tempMap = (Map<String,Object>)results;

            String datasetId = String.valueOf(tempMap.get('id'));
            String versionId = String.valueOf(tempMap.get('currentVersionId'));

            result.add(datasetId);
            result.add(versionId);
        }
        else{
            System.debug(res.getStatus());
        }

        return result;

    }








    @AuraEnabled
	public static  Map<String,Object> getSalesData(String accountId, String querySAQL){

    List<String> datasetDetails = findDatasetVersion('AccountSalesDetail');
    List<String> datasetAssetsDetails = findDatasetVersion('Assets');
    List<Decimal> salesData = new List<Decimal>{};
    Map<String,Object> results = new Map<String,Object>();
    Account acc = [SELECT Id, OneSF_Id__c FROM Account WHERE Id =: accountId LIMIT 1];

    if(datasetDetails[0]!= null && datasetDetails[1] != null && datasetAssetsDetails[0]!= null && datasetAssetsDetails[1] != null){
        String querySAQLtoFilter = querySAQL;
        querySAQLtoFilter = querySAQLtoFilter.replace('*replaceAccountSalesDetail*',datasetDetails[0] + '/' + datasetDetails[1]);
        querySAQLtoFilter = querySAQLtoFilter.replace('*replaceAssets*',datasetAssetsDetails[0] + '/' + datasetAssetsDetails[1]);
        querySAQLtoFilter = querySAQLtoFilter.replace('*replaceSFDCOneId*',acc.OneSF_Id__c);
        
        String response = '';
        if (!Test.isRunningTest()) {
            ConnectApi.LiteralJson queryresult =  ConnectApi.Wave.executeQuery(querySAQLtoFilter);
            response = queryresult.json;
        }
        else{
            response = '{"results":{"records":[{"NetAmount":3000, "ImplantUnitsQty":30},{"NetAmount":2000, "ImplantUnitsQty":40}]}, "id":"56789"}';   
        }
        results = (Map<String,Object>)JSON.deserializeUntyped(response);

        
        }
        return(results);
    }
}