src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Global Pick List</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Implants</fullName>
                    <label>Global DPG</label>
                </value>
                <value>
                    <fullName>All Ortho</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ATF</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
                <value>
                    <fullName>BHR</fullName>
                </value>
                <value>
                    <fullName>BHS</fullName>
                </value>
                <value>
                    <fullName>BIH</fullName>
                </value>
                <value>
                    <fullName>BLM</fullName>
                </value>
                <value>
                    <fullName>BLR</fullName>
                </value>
                <value>
                    <fullName>BLZ</fullName>
                </value>
                <value>
                    <fullName>BMU</fullName>
                </value>
                <value>
                    <fullName>BOL</fullName>
                </value>
                <value>
                    <fullName>BRA</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Non_ERP_Products__c.object
<CustomObject>
    <fields>
        <fullName>Competitor_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Competitor Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KeyProduct__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Focus Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <label>Manufacturer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <formula>IF(TEXT( Product_Market_Mapping__r.Market__c )=&apos;IT&apos;, &apos;Italy&apos;,IF(TEXT( Product_Market_Mapping__r.Market__c )=&apos;ES&apos;, &apos;Iberia&apos;, TEXT(Product_Market_Mapping__r.Market__c)))</formula>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductGroupText__c</fullName>
        <label>Product Group (Global)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <description>Free Text, optional</description>
        <inlineHelpText>This field controls the grouping of records in the Product Profiling component on Accounts/Contacts</inlineHelpText>
        <label>Product Group (Local)</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Market_Mapping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Market Mapping</label>
        <referenceTo>SSIS_ERP_SKU_Metadata_Country_Connectio__c</referenceTo>
        <relationshipName>Products_Profiling</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Non-ERP Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non-ERP Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product_Profiling__c.object
<CustomObject>
    <fields>
        <fullName>Competitor_Product__c</fullName>
        <formula>Product_Name__r.Competitor_Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Competitor Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <formula>Product_Name__r.Manufacturer__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Manufacturer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <formula>Product_Name__r.Product_Category__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <label>Product Profiling</label>
    <nameField>
        <displayFormat>PP{000000000}</displayFormat>
        <label>Profiling Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Profiling</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SSIS_ERP_SKU_Metadata_Country_Connectio__c.object
<CustomObject>
    <description>This object manages the M:M relationships between the ERP/SKU Metadata/Company Code record and the Country/Global Setting record</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this field is checked the connection between Company code and the country is active.</description>
        <inlineHelpText>If this field is checked the connection between Company code and the country is active.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Market</valueSetName>
        </valueSet>
    </fields>
    <label>SSIS: ERP/SKU - Market Mapping</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>SSIS: ERP/SKU Metadata Country Connectio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSIS_ERP_SKU_Market_Mappings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <description>&lt;ADMINISTRATION&gt; Keep the values of this field aligned with the Price Book Market field values.</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>BeNelux</fullName>
                </value>
                <value>
                    <fullName>BEX</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>CEE</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>DEX</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
                <value>
                    <fullName>HQ</fullName>
                </value>
                <value>
                    <fullName>Iberia</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Kazakhstan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>MEA</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>Nordics</fullName>
                </value>
                <value>
                    <fullName>Poland</fullName>
                </value>
                <value>
                    <fullName>Russia</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>South Africa</fullName>
                </value>
                <value>
                    <fullName>Switzerland</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/globalValueSets/Market.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>BeNeLux</fullName>
    </customValue>
    <customValue>
        <fullName>BEX</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>CEE</fullName>
    </customValue>
    <customValue>
        <fullName>CH</fullName>
    </customValue>
    <customValue>
        <fullName>CN</fullName>
    </customValue>
    <customValue>
        <fullName>DACH (Ortho)</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DEX</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>HK</fullName>
    </customValue>
    <customValue>
        <fullName>HQ</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesia</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>JP</fullName>
    </customValue>
    <customValue>
        <fullName>KR</fullName>
    </customValue>
    <customValue>
        <fullName>Malaysia</fullName>
    </customValue>
    <customValue>
        <fullName>MEA</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>Nordics</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
    </customValue>
    <customValue>
        <fullName>Russia</fullName>
    </customValue>
    <customValue>
        <fullName>SG</fullName>
    </customValue>
    <masterLabel>Market</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/Test_ProductProfilingHierarchyController.cls
/*------------------------------------------------------------	
Author: 		Richard Trum (Glimt) 2019-11-28 	
Description:   	Test class related to the class ProductProfilingHierarchyController
------------------------------------------------------------*/

@isTest
private class Test_ProductProfilingHierarchyController {
	
    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.createUsers(1, 'System Administrator'); 
        TestDataFactory.createGlobalIntegrationSettings(userList);
        TestDataFactory.createDefaultOrgLevelBypassPB();
    }
    
    @isTest
    private static void testERPProducts(){
    
        User currentUser = TestDataFactory.createUsers(1, 'System Administrator')[0]; 
        system.runAs(currentUser){
            Account acc = new Account();
            acc = testDataFactory.returnAccounts(1, 'CIM_Account', currentUser.Id)[0];
            acc.Name ='Test account';
            acc.Country__c = 'DE';
            insert acc;
            
            Contact con = new Contact();
            con.FirstName = 'Test';
            con.LastName = 'Test';
            con.AccountId = acc.Id;
            insert con;
            
            SSIS_ERP_SKU_Metadata_Country_Connectio__c pmm = new SSIS_ERP_SKU_Metadata_Country_Connectio__c();
            pmm.Market__c = currentUser.Market__c;
            pmm.Active__c = true;
            insert pmm;
            
            Non_ERP_Products__c ERP = new Non_ERP_Products__c();
            ERP.Name = 'Test product';
            ERP.Competitor_Product__c = false;
            ERP.KeyProduct__c = true;
            ERP.ProductGroupText__c = 'Implants';
            ERP.Product_Category__c = 'Implants';
            ERP.Product_Market_Mapping__c = pmm.Id;
            ERP.Manufacturer__c = 'Test manufacturer';
            ERP.Countries__c = 'DE';
            ERP.Inactive__c = false;
            
            insert ERP;
            
            Product_Profiling__c prodP = new Product_Profiling__c();
            prodP.Product_Name__c = ERP.Id;
            prodP.Account__c = acc.Id;
            prodP.Contact__c = con.Id;
            insert prodP;
            
            Test.startTest();
            
            List<ProductProfilingHierarchyController.HierarchyNode> res = ProductProfilingHierarchyController.getChildProducts(String.valueOf(acc.Id), '', 'Test manufacturer', 'Test', 'Implants', false, true, '', '');
            System.assertEquals(res.size(), 1);
            
            List<String> resSBUs = ProductProfilingHierarchyController.getSBUs(acc.Id);
            List<String> resManufacturers = ProductProfilingHierarchyController.getManufacturers(acc.Id, 'Implants');
            List<String> resManufacturersContact = ProductProfilingHierarchyController.getManufacturers(con.Id, 'Implants');
            List<String> resLocalCategories = ProductProfilingHierarchyController.getLocalCategories(acc.Id, 'Implants', 'Test manufacturer');
            List<String> resLocalCategoriesContact = ProductProfilingHierarchyController.getLocalCategories(con.Id, 'Implants', 'Test manufacturer');
            List<String> resLocalCategoriesWOmanufact = ProductProfilingHierarchyController.getLocalCategories(acc.Id, 'Implants', '');
            List<String> resLocalCategoriesWOcat = ProductProfilingHierarchyController.getLocalCategories(acc.Id, '', 'Test manufacturer');
            List<String> resCategories =  ProductProfilingHierarchyController.getAllCategories(acc.Id, 'Implants');
            List<String> resCategoriesContact =  ProductProfilingHierarchyController.getAllCategories(con.Id, 'Implants');
            List<Workflow__c> resWorkflows =  ProductProfilingHierarchyController.getWorkflows(acc.Id);
            
            Map<Id, Product_Profiling__c> resMapAcc = ProductProfilingHierarchyController.getProductProfilingMap(acc.Id);
            System.assertNotEquals(resMapAcc, null);
            
            Map<Id, Product_Profiling__c> resMapCon = ProductProfilingHierarchyController.getProductProfilingMap(con.Id);
            System.assertNotEquals(resMapCon, null);
            
            List<Product_Profiling__c> resAcc = ProductProfilingHierarchyController.getProductProfiling(acc.Id);
            System.assertNotEquals(resAcc, null);
            
            List<Product_Profiling__c> resCon = ProductProfilingHierarchyController.getProductProfiling(con.Id);
            System.assertNotEquals(resCon, null);
            
            Test.stopTest();
        }
        
        
    }

    @isTest
    private static void testDistinctValues(){
    
        User currentUser = TestDataFactory.createUsers(1, 'System Administrator')[0]; 
        system.runAs(currentUser){
            Account acc = new Account();
            acc = testDataFactory.returnAccounts(1, 'CIM_Account', currentUser.Id)[0];
            acc.Name ='Test account';
            insert acc;
            
            Contact con = new Contact();
            con.FirstName = 'Test';
            con.LastName = 'Test';
            con.AccountId = acc.Id;
            insert con;
            
            SSIS_ERP_SKU_Metadata_Country_Connectio__c pmm = new SSIS_ERP_SKU_Metadata_Country_Connectio__c();
            pmm.Market__c = currentUser.Market__c;
            pmm.Active__c = true;
            insert pmm;
            
            Non_ERP_Products__c ERP = new Non_ERP_Products__c();
            ERP.Name = 'Test product';
            ERP.Competitor_Product__c = false;
            ERP.KeyProduct__c = true;
            ERP.Product_Category__c = 'Implants';
            ERP.Product_Market_Mapping__c = pmm.Id;
            ERP.Manufacturer__c = 'DentsplySirona';
            insert ERP;
            
            Product_Profiling__c prodP = new Product_Profiling__c();
            prodP.Product_Name__c = ERP.Id;
            prodP.Account__c = acc.Id;
            prodP.Contact__c = con.Id;
            insert prodP;
            
            Test.startTest();
            
            List<String> res = ProductProfilingHierarchyController.getDistinctValues('Manufacturer__c', acc.Id);
            System.assertEquals(res.size(), 1);
                
            List<String> resCon = ProductProfilingHierarchyController.getDistinctValues('Manufacturer__c', con.Id);
            System.assertEquals(resCon.size(), 1);    
            
            Boolean deleted = ProductProfilingHierarchyController.deleteProductProfilingRecord(prodP.Id);
                                    
            Test.stopTest();
        }
        
        
    }
    
    
    
}