src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Consent_Date__c</fullName>
        <description>Used by Canada for legal reasons</description>
        <inlineHelpText>Used by Canada for legal reasons</inlineHelpText>
        <label>Email Consent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Consent_collected__c</fullName>
        <description>This field is used as part of the data privacy, e.g. GDPR process to make sure we are collecting information about whether a consent has been collected or not for sending marketing emails. If yes is selected that Email Consent Date fields will be updated with Todays date. If no the email opt out checkbox will be checked. Using workflows. Email still kept for both selections</description>
        <inlineHelpText>I confirm that I have obtained the customers permission for their email address to be used by Dentsply Sirona for Marketing communications.</inlineHelpText>
        <label>Email Marketing Consent collected</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Please Select Yes or No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To identify whether a Contact is Inactive or Active</description>
        <inlineHelpText>Check this checkbox if the contact is either retired, deceased or has left position/post</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>InsertEmailMarketingConsentCollected__c</fullName>
        <inlineHelpText>Please fill the information if the Email Marketing Consent was collected or not</inlineHelpText>
        <label>Insert Email Marketing Consent Collected</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>inactive_dedupe_HQ__c</fullName>
        <description>Used for duplicate management since original field cannot be used in duplicate rules. Updated by workflow.</description>
        <label>inactive dedupe(HQ)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FALSE</fullName>
                    <default>true</default>
                    <label>FALSE</label>
                </value>
                <value>
                    <fullName>TRUE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Implants</fullName>
                    <label>Global DPG</label>
                </value>
                <value>
                    <fullName>All Ortho</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ATF</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
                <value>
                    <fullName>BHR</fullName>
                </value>
                <value>
                    <fullName>BHS</fullName>
                </value>
                <value>
                    <fullName>BIH</fullName>
                </value>
                <value>
                    <fullName>BLM</fullName>
                </value>
                <value>
                    <fullName>BLR</fullName>
                </value>
                <value>
                    <fullName>BLZ</fullName>
                </value>
                <value>
                    <fullName>BMU</fullName>
                </value>
                <value>
                    <fullName>BOL</fullName>
                </value>
                <value>
                    <fullName>BRA</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CountryCodeMap__mdt.object
<CustomObject>
    <description>TFUS-000002404</description>
    <fields>
        <fullName>Country_Code_2_digit__c</fullName>
        <label>Country Code (2-digit)</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Code_full__c</fullName>
        <label>Country Code (full)</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Country Code Map</label>
    <pluralLabel>Country Code Maps</pluralLabel>
</CustomObject>

src/objects/EncryptionSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting stores configuration data related to encryption settings. It includes essential information such as encryption keys and other parameters required for secure data handling</description>
    <fields>
        <fullName>AESKey__c</fullName>
        <description>[TFUS-000006026]  This field stores the AES key used for encrypting custom data included as a GET parameter within a DS.com link. The purpose is to initiate an invitation/registration email process tailored for a specific customer, identified by the encrypted data.</description>
        <inlineHelpText>This field stores the AES key used for encrypting custom data included as a GET parameter within a DS.com link. The purpose is to initiate an invitation/registration email process tailored for a specific customer, identified by the encrypted data.</inlineHelpText>
        <label>AES Key</label>
        <type>TextArea</type>
    </fields>
    <label>Encryption Settings</label>
</CustomObject>

src/objects/Expert__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>KOL information</relationshipLabel>
        <relationshipName>KOL_information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>TEXT(Contact__r.Account.Country__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if the KOL is no longer active as KOL but we still want to keep information if re-activated again.</description>
        <inlineHelpText>Checked if the KOL is no longer active as KOL.</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <label>KOL information</label>
    <nameField>
        <label>KOL Information</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KOL information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContactTriggerHelper.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Roberto Narbona 
Description:    Contact Trigger Helper Class
Test Class:      
History 
20210401        Roberto Narbona         created showNoDeleteError method TFUS-000002832
20210908        Roberto Narbona        Refractoring done cause TFUS TFUS-000003164
20220622        Roberto Narbona        Refractoring done cause TFUS TFUS-000004110
20220622        Houssam ADIB            DS com Encryption logic TFUS-000006026
--------------------------------------------------------------------------------------------------------*/

public with sharing class ContactTriggerHelper {


    private static final string ENCRYPTION_FNAME_ATTRIBUTE = 'fname=';
    private static final string ENCRYPTION_LNAME_ATTRIBUTE = 'lname=';
    private static final string ENCRYPTION_EMAIL_ATTRIBUTE = 'email=';
    private static final string ENCRYPTION_CIM360ID_ATTRIBUTE = 'cim360id=';
    private static final string ENCRYPTION_SEPARATOR = '&';
    private static final string ENCRYPTION_ALGORITHM = 'AES256';


    public static void setValues(List<Contact> newContactList,Map<Id, Contact> newContactMap, Map<Id, Contact> oldContactMap){
        Map<String, CountryCodeMap__mdt> countryCodeMapping = new Map<String, CountryCodeMap__mdt>();
        List<CountryCodeMap__mdt> countryList = [SELECT  Country_Code_full__c, Country_Code_2_digit__c FROM CountryCodeMap__mdt];
        for (CountryCodeMap__mdt country : countryList) {
            countryCodeMapping.put(country.Country_Code_2_digit__c, country);
        }

        Set<Id> contactAccountIds = new Set<Id>();
        for(Contact contact : newContactList)
        {
            contactAccountIds.add(contact.AccountId);
        }

        Map<ID, Account> mapAccounts = new Map<ID, Account>([SELECT Id, CIM360Id__c, CurrencyIsoCode, Country__c FROM Account WHERE Id IN: contactAccountIds]);

        Blob aesKey = getAESKeyFromCustomSetting();
        Boolean isAesKeyNull = (aesKey == null);

        for (Contact contact : newContactList) {
            //Story TFUS-000004110

            contact.CurrencyIsoCode = (!mapAccounts.isempty() && contact.AccountId != null && mapAccounts.get(contact.AccountId)!= null && mapAccounts.get(contact.AccountId).CurrencyIsoCode != null) ? mapAccounts.get(contact.AccountId).CurrencyIsoCode : contact.CurrencyIsoCode;

            //Migrated process builder entry -> Entry country validation

            if(!mapAccounts.isempty() && contact.Country__c == null && contact.AccountId != null && mapAccounts.get(contact.AccountId)!= null && mapAccounts.get(contact.AccountId).country__c != null){ //add account country null exception
                string country = mapAccounts.get(contact.AccountId).country__c;
                contact.country__c = countryCodeMapping.get(Country).Country_Code_full__c;
            }
            //Migrated process builder entry -> Marketing Consent not given
            if((contact.Email == null || contact.InsertEmailMarketingConsentCollected__c == 'No' ) && (newContactMap == null  || (newContactMap != null && contact.email != oldContactMap.get(contact.Id).email) || (newContactMap != null && contact.InsertEmailMarketingConsentCollected__c != oldContactMap.get(contact.Id).InsertEmailMarketingConsentCollected__c)))
                {
                contact.Email_Consent_collected__c = 'No';
                contact.HasOptedOutOfEmail = true;
            }
            //Migrated process builder entry -> Email Marketing consent process
            if( contact.Email != null && contact.InsertEmailMarketingConsentCollected__c == 'Yes' && (newContactMap == null ||(newContactMap != null && contact.InsertEmailMarketingConsentCollected__c != oldContactMap.get(contact.Id).InsertEmailMarketingConsentCollected__c) || (newContactMap != null && contact.email != oldContactMap.get(contact.Id).email))){
                contact.Email_Consent_collected__c = 'Yes';
                contact.Email_Consent_Date__c = system.today();
                contact.HasOptedOutOfEmail = false;
            }
            //Migrated process builder entry -> Email Opt-Out Denied by Customer *only for change so not insert*
            if( (newContactMap != null && contact.HasOptedOutOfEmail != oldContactMap.get(contact.Id).HasOptedOutOfEmail)
                && contact.HasOptedOutOfEmail == true && contact.Email_Consent_collected__c != 'Please Select Yes or No'){
                    contact.Email_Consent_collected__c = 'No';
            }
            //Migrated process builder entry -> Email Opt-In Confirmed By Customer *only for change so not insert*
            if((newContactMap != null && contact.HasOptedOutOfEmail != oldContactMap.get(contact.Id).HasOptedOutOfEmail)
                && contact.HasOptedOutOfEmail == false && contact.Email_Consent_collected__c != 'Please Select Yes or No' ){
                    contact.Email_Consent_collected__c = 'Yes';

            }
            //Migrated process builder entry -> Email Marketing Consent - Delete Email
            if(contact.Email == null){
                contact.Email_Consent_Date__c = null;
                contact.HasOptedOutOfEmail= false;
            }
            //Migrated process builder entry -> Set Inactive Field Value in Duplicate Management
            if(contact.InsertEmailMarketingConsentCollected__c == 'Yes'){
                contact.inactive_dedupe_HQ__c = 'FALSE';
            }
            //Migrated process builder entry -> US Owner Assignment
            if(!mapAccounts.isempty() && contact.accountId != null && mapAccounts.get(contact.AccountId) != null && mapAccounts.get(contact.AccountId).country__c != null && (mapAccounts.get(contact.AccountId).country__c == 'US' || mapAccounts.get(contact.AccountId).country__c == 'CA')   && contact.OwnerId != '0056M00000A0kR9QAJ'){
                contact.OwnerId = '0056M00000A0kR9QAJ';
            }
            //Migrated process builder entry -> BR Owner Assignment
            if(!mapAccounts.isempty() && contact.accountId != null && mapAccounts.get(contact.AccountId)!= null && mapAccounts.get(contact.AccountId).country__c != null && mapAccounts.get(contact.AccountId).country__c == 'BR' &&  contact.OwnerId != '0056M000009Z3c2QAC'){
                contact.OwnerId = '0056M000009Z3c2QAC';
            }

            //Migrated process builder entry -> Set Inactive Field Value in Duplicate - Active
            if(contact.Inactive__c == false){
                contact.inactive_dedupe_HQ__c = 'FALSE';
            }

            if(!isAesKeyNull) setEncryptedUrl(contact,aesKey,mapAccounts);

        }
    }

    /**
     * Retrieves the AES Key from the custom settings
     * @author hadib@salesforce.com | 11-11-2023
     * @return Bloc - AES Key
     */
    public static Blob getAESKeyFromCustomSetting()
    {
        Blob aesKey;
        EncryptionSettings__c settings = EncryptionSettings__c.getInstance();
        if (settings != null && settings.AesKey__c != null) {
            // Convert the base64-encoded string back to a Blob
            aesKey = EncodingUtil.base64Decode(settings.AesKey__c);
        }
        return aesKey;
    }

    /**
     * Encrypt contact field using AES Key and put the value in DScomUrlParam__c field
     * @author hadib@salesforce.com | 11-11-2023
     * @param contact Contact record
     * @param aesKey AES Key as a blob
     * @param parentAccounts Parent Accounts
     */
    public static void setEncryptedUrl(Contact contact, Blob aesKey, Map<Id,Account> parentAccounts)
    {
        // Original text
        String textToEncrypt = '';
        if (contact.FirstName != null) {
            textToEncrypt += ENCRYPTION_FNAME_ATTRIBUTE + contact.FirstName + ENCRYPTION_SEPARATOR;
        }
        if (contact.LastName != null) {
            textToEncrypt += ENCRYPTION_LNAME_ATTRIBUTE + contact.LastName + ENCRYPTION_SEPARATOR;
        }
        if (contact.Email != null) {
            textToEncrypt += ENCRYPTION_EMAIL_ATTRIBUTE + contact.Email + ENCRYPTION_SEPARATOR;
        }
        if (parentAccounts.get(contact.AccountId)?.CIM360Id__c != null) {
            textToEncrypt += ENCRYPTION_CIM360ID_ATTRIBUTE + parentAccounts.get(contact.AccountId).CIM360Id__c;
        }
        // Remove the trailing ENCRYPTION_SEPARATOR ('&') if any
        if (textToEncrypt.endsWith(ENCRYPTION_SEPARATOR)) {
            textToEncrypt = textToEncrypt.removeEnd(ENCRYPTION_SEPARATOR);
        }

        // Encrypt with the AES key
        Blob encryptedData = Crypto.encryptWithManagedIV(ENCRYPTION_ALGORITHM, aesKey, Blob.valueOf(textToEncrypt));
        String encryptedText = EncodingUtil.base64Encode(encryptedData);

        contact.DScomUrlParam__c = EncodingUtil.urlEncode(encryptedText, 'UTF-8');
    }

    public static void showNoDeleteError(Map<Id, Contact> contactsMap, List<Contact> contactList){
        Map<Id, Contact> contactsCopy = contactsMap.clone();
        //keeping only those contacts with KOLs
        contactsCopy.keySet().retainAll(
        new Map<Id, AggregateResult>(
            [SELECT Contact__c Id
             FROM Expert__c
             WHERE Contact__c = :contactList
             GROUP BY Contact__c]).keySet());
        for(Contact record: contactsCopy.values()) {
            record.addError(Label.KOLDeleteError);
        }
    }
}