src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Discount_End_year__c</fullName>
        <inlineHelpText>Discount granted to the customer based on the total sales at the end of the year. Not applied to the order</inlineHelpText>
        <label>Discount End Year</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <recordTypes>
        <fullName>Contract</fullName>
        <active>true</active>
        <description>Intended to be the global contract record type - first version is a very basic contract launched in BeNeLux</description>
        <label>Contract</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Account_for_Sample_in_AX__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account to track sample in AX</description>
        <label>Payer Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>Account.OneAccount_Type__c</field>
                <operation>equals</operation>
                <value>DENTSPLY</value>
            </filterItems>
            <filterItems>
                <field>Account.Sub_Account_Type__c</field>
                <operation>equals</operation>
                <value>Sales Rep</value>
            </filterItems>
            <filterItems>
                <field>Account.OneAccount_Type__c</field>
                <operation>equals</operation>
                <value>Internal</value>
            </filterItems>
            <filterItems>
                <field>Account.Sub_Account_Type__c</field>
                <operation>equals</operation>
                <value>Free Goods, Internal Sales Rep</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sample Orders</relationshipLabel>
        <relationshipName>Sample_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricebook_Name__c</fullName>
        <formula>Pricebook2.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pricebook Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SIMPLANT_Software_Evaluation__c</fullName>
        <label>SIMPLANT Software Evaluation</label>
        <summarizedField>OrderItem.SIMPLANT_Software_Line_Item__c</summarizedField>
        <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>User_CountryPL__c</fullName>
        <label>User CountryPL</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>BEX</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Distributor Markets</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Holland</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
                <value>
                    <fullName>HQ: DE</fullName>
                </value>
                <value>
                    <fullName>HQ: NL</fullName>
                </value>
                <value>
                    <fullName>HQ: SE</fullName>
                </value>
                <value>
                    <fullName>Hungary</fullName>
                </value>
                <value>
                    <fullName>INDIA</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Jordan</fullName>
                </value>
                <value>
                    <fullName>Kazakhstan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Account_for_Sample_in_AX__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account for Sample in AX</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.OneAccount_Type__c</field>
                <operation>equals</operation>
                <value>DENTSPLY</value>
            </filterItems>
            <filterItems>
                <field>Account.Sub_Account_Type__c</field>
                <operation>equals</operation>
                <value>Sales Rep</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AvailableCouponCode__c</fullName>
        <formula>IF(AND(
OR((Order.Order_Amount_global__c - Total_Line_Item_Price__c)&gt;=  PricebookEntry.FreeProductThreshold__c * Quantity, UseCoupon__c = true), NOT(ISNULL(PricebookEntry.FreeProductThreshold__c))), TEXT(PricebookEntry.FreeProductThreshold__c), &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Available Coupon Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>PricebookEntry.Product2.Brand__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DiscountApproval_Line_Item__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Discount Approval Line Item</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Approval_Eval__c</fullName>
        <formula>IF( AND(Discount_Percent__c  &gt; 0, (LEN( Text(Sales_Special__c))&gt;0)),&quot;NO APPROVAL NEEDED&quot;, 

IF(AND(Discount_Percent__c  &gt; 0,(LEN( Text(Sales_Special__c))=0)), &quot;YES - APPROVAL NEEDED&quot;,

IF(Discount_Percent__c  &gt; 0, &quot;YES - APPROVAL NEEDED&quot;,
IF(Discount_Percent__c   = 0, &quot;NO APPROVAL NEEDED&quot;,

&quot;YES&quot;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount Approval Evaluation</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Percent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Discount</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Free_of_Charge_Delivery__c</fullName>
        <description>Used to state who should deliver a free of charge item - it can be either a dealer, Dentsply Sirona Customer Service or given directly during meeting by Sales Rep</description>
        <label>Free of Charge Delivery</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dealer</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Sales Rep</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MTF_EvaluationNumber__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MTF Evaluation Line Item</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MTF_Evaluation__c</fullName>
        <formula>CASE( PricebookEntry.Product2.Article__c ,
&quot;US228005&quot;, 1,
&quot;US228010&quot;, 1,
&quot;US228025&quot;, 1,
&quot;US420038&quot;,1,
&quot;US420039&quot;,1,
&quot;US420075&quot;, 1,
&quot;US420076&quot;,1,
&quot;US420077&quot;, 1,
&quot;US420078&quot;,1,
&quot;US400175&quot;,1,
&quot;US400173&quot;, 1,
&quot;US400174&quot;,1,
&quot;US400191&quot;,1,
&quot;US400192&quot;,1,
&quot;US400175&quot;, 1,
&quot;US400176&quot;,1,
&quot;US400177&quot;,1,
&quot;US400178&quot;,1,
&quot;US791101&quot;, 1,
&quot;US791102&quot;, 1,
&quot;US791104&quot;, 1,
&quot;US791204&quot;, 1,
&quot;US790101&quot;, 1,
&quot;US790102&quot;, 1,
&quot;US790104&quot;, 1,
&quot;US790202&quot;, 1,
&quot;US790204&quot;, 1,
&quot;US400193&quot;, 1,
&quot;US420048&quot;, 1,
&quot;US400172&quot;, 1,
&quot;US400178&quot;, 1,
&quot;US400194&quot;, 1,
&quot;US420049&quot;, 1,

&quot;US600172&quot;, 1,
&quot;US600173&quot;, 1,
&quot;US600174&quot;, 1,
&quot;US600175&quot;, 1,
&quot;US600176&quot;, 1,
&quot;US600177&quot;, 1,
&quot;US600178&quot;, 1,
&quot;US600191&quot;, 1,
&quot;US600192&quot;, 1,
&quot;US600193&quot;, 1,
&quot;US600194&quot;, 1,
&quot;US620038&quot;, 1,
&quot;US620039&quot;, 1,
&quot;US620048&quot;, 1,
&quot;US620049&quot;, 1,
&quot;US620075&quot;, 1,
&quot;US620076&quot;, 1,
&quot;US620077&quot;, 1,
&quot;US620078&quot;, 1,


0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MTF Evaluation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Non_SIMPLANT_Evaluation__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>Populated by a workflow update, this enables the order to evaluate how many Simplant/Non Simplant Line items are on this order for Approval Process Purposes</inlineHelpText>
        <label>Non-SIMPLANT Evaluation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offer_Code_Applied_Number__c</fullName>
        <description>Updated by the Order Product Process Builder and used in the Roll Up Summary field on the Order</description>
        <label>Offer Code Applied Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offer_Code_dna__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Offer_Code__c.Offer_Code_Status__c</field>
                <operation>notEqual</operation>
                <value>Expired</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Offer_Code__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SIMPLANT_Line_Item__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Populated by a workflow rule which evaluates the formula field SIMPLANT Order and brings back a numerical value. This field will be used in a rollup summary to the Order for evaluation in an approval process for North America</description>
        <inlineHelpText>Populated by a workflow rule which evaluates the formula field SIMPLANT Order and brings back a numerical value. This field will be used in a rollup summary to the Order for evaluation in an approval process for North America</inlineHelpText>
        <label>SIMPLANT Line Item</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SIMPLANT_Software_Line_Item__c</fullName>
        <label>SIMPLANT Software Line Item</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UseCoupon__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Coupon?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Value_of_Samples_for_Sales_Rep__c</fullName>
        <label>Value of Samples for Sales Rep</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Value_of_free_product__c</fullName>
        <label>Value of free product</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>ShowApprovalLevelOrderLine__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for showing/hiding the approval level on order line level</description>
        <label>Show Approval Level Order Line (OM)</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderItemTriggerHelper.cls
/*-------------------------------------------------------------------------------------------------------
Author: 		LOUDRASSI Ahmed (Salesforce) 2020-02-25
Description:    OrderItem Trigger Helper Class
Test Class:     
History 
Kevin Ruibin Do 20210419    Updated totalAmountOfSamplesAndFreeProducts to also set value when there are no free products
Richard Trum	20200804	Changed setDiscountAllowedforTurkey to use the Contract field Discount__c instead of Discount_End_year__c
Miguel Coimbra	20200511	Added descriptions
Roberto Narbona 20231218    TFUS-000006230 ne method setOfferCodeAppliedNumber
Roberto			20240219	TFUS-000006492
----------------------------------------------------------------------------------------*/
public class OrderItemTriggerHelper {
    /*------------------------------------------------------------  
    Description:    define Order Discount Percent to max 100 (as per logic defined on Order Management 2.0)
    Inputs:         @param newOrderItemList
    ------------------------------------------------------------*/
    public static void set100PercentForFOC(List<OrderItem> newOrderItemtList) {
        Set<ID> orderIds = new Set<ID>();
        for(OrderItem orderItem: newOrderItemtList) {
            orderIds.add(orderItem.OrderId);
        }
        Map<Id,Order> parentOrders = new Map<ID, Order>([SELECT Id, Pricebook2Id, Pricebook_Name__c, Pricebook2.ShowApprovalLevelOrderLine__c FROM Order WHERE ID IN :orderIds]); 
        for (OrderItem orderItem: newOrderItemtList) {
            Order parentOrder = parentOrders.get(orderItem.OrderId);
            if (parentOrder.Pricebook2Id != null && (String.isNotBlank(orderItem.Free_of_Charge_Delivery__c) || (orderItem.UseCoupon__c == true && orderItem.AvailableCouponCode__c != null))) { //|| (parentOrder.Pricebook2.ShowApprovalLevelOrderLine__c == true && orderItem.Offer_code_dna__c != null)
                orderItem.Discount_Percent__c = 100;
            }

            if(String.isNotBlank(parentOrder.Pricebook2Id) && (orderItem.UseCoupon__c == true && orderItem.AvailableCouponCode__c == null) ){
                orderItem.Discount_Percent__c = 0;
                orderItem.UseCoupon__c = false;
            }

        }
    }
    /*------------------------------------------------------------  
    Description:   
    Inputs:         @param newOrderItemList
    ------------------------------------------------------------*/
    public static void totalAmountOfSamplesAndFreeProducts(List<OrderItem> newOrderItemtList) { 
        for(OrderItem orderItem: newOrderItemtList) {
            setOfferCodeAppliedNumber(orderItem);
            if(orderItem.Quantity > 0) {
                // Amount Samples
                if(String.isBlank(orderItem.Account_for_Sample_in_AX__c)) {
                    orderItem.Value_of_Samples_for_Sales_Rep__c = 0;
                } else {
                    orderItem.Value_of_Samples_for_Sales_Rep__c = orderItem.UnitPrice * orderItem.Quantity;
                }
                // Value of Free Products
                if(orderItem.Discount_Percent__c == 100) {
                    orderItem.Value_of_free_product__c = orderItem.UnitPrice * orderItem.Quantity;
                } else {
                    orderItem.Value_of_free_product__c = 0;
                }
            }
        } 
    }
    
    /*------------------------------------------------------------  
    Description:   Check if there is an offer code if yes set offer code applied number to 1
                   Migrate prcess builder entries "Offer Code selected" and "Offer Code Deselected"
    Inputs:         @param orderItem
    ------------------------------------------------------------*/
    public static void setOfferCodeAppliedNumber(OrderItem orderItem) { 
        orderItem.Offer_Code_Applied_Number__c = String.isBlank(orderItem.Offer_Code_dna__c) ? 0 : 1;
    }

    	
    /*------------------------------------------------------------  
    Description:    
    Inputs:         @param newOrderItemList
    ------------------------------------------------------------*/
    public static void orderProductEvaluation(List<OrderItem> newOrderItemtList) { 
        Set<ID> orderIds = new Set<ID>();
        for(OrderItem orderItem: newOrderItemtList) {
            orderIds.add(orderItem.OrderId);
        }
        Map<Id,Order> parentOrders = new Map<ID, Order>([SELECT Id, User_CountryPL__c FROM Order WHERE ID IN :orderIds]); 
        for(OrderItem orderItem: newOrderItemtList) {
            if(String.isNotBlank(parentOrders.get(orderItem.OrderId).User_CountryPL__c)) {
                // ORDER: Update SIMPLANT Evaluation
                orderItem.SIMPLANT_Line_Item__c = 'SIMPLANT'.equals(orderItem.PricebookEntry.Product2.Brand__c) ? 1 : 0;
                // ORDER: Update MTF Evaluation
                orderItem.MTF_EvaluationNumber__c = orderItem.MTF_Evaluation__c == 1 ? 1 : 0;
                // ORDER: Discount Approval Evaluation
                orderItem.DiscountApproval_Line_Item__c  = 'NO APPROVAL NEEDED'.equals(orderItem.Discount_Approval_Eval__c) ? 0 : 1; 
                // ORDER: Update NON-SIMPLANT Evaluation
                orderItem.Non_SIMPLANT_Evaluation__c = 'SIMPLANT'.equals(orderItem.PricebookEntry.Product2.Brand__c) ? 0 : 1;
                // SIMPLANT Software Line Item Eval
                orderItem.SIMPLANT_Software_Line_Item__c = orderItem.SIMPLANT_Software_Evaluation__c;
                // Update # of Items at 100% Discount
                orderItem.Number_of_Items_at_100_Discount__c = orderItem.Item_at_100__c;
            }
        }
    }
    /*------------------------------------------------------------  
    Description:    Method migrated from Process Builder on Order Product 
    Inputs:         @param newOrderItemList
    ------------------------------------------------------------*/
    public static void setDiscountAllowedforTurkey(List<OrderItem> newOrderItemtList) { 
        Set<ID> orderIds = new Set<ID>();
        for(OrderItem orderItem: newOrderItemtList) {
            orderIds.add(orderItem.OrderId);
        }
        Map<Id,Order> parentOrders = new Map<ID, Order>
            ([SELECT Id, Pricebook2Id, Country__c, Discount_to_be_used__c, 
              Allowed_discount__c, Order_Type__c, Contract.Discount_End_year__c, Contract.Discount__c FROM Order WHERE ID IN :orderIds]); 
        Map<Id,Order> ordersToUpdate = new Map<Id,Order> ();
        for(OrderItem orderItem: newOrderItemtList) {
            Order parentOrder = parentOrders.get(orderItem.OrderId);
            if('TR'.equals(parentOrder.Country__c) &&
              	String.isNotBlank(parentOrder.Pricebook2Id) &&
              	'Implants'.equals(parentOrder.Order_Type__c)) {
               	if(String.isNotBlank(parentOrder.ContractId)) {
                	parentOrder.Discount_to_be_used__c = parentOrder.Contract.Discount__c;
                } else {
                    parentOrder.Discount_to_be_used__c = 0;
                }
                if(!ordersToUpdate.containsKey(parentOrder.Id)) {
                    ordersToUpdate.put(parentOrder.Id, parentOrder);
                }
            }
        }
        update ordersToUpdate.values();
    }
    /*Set if product is related with parent kit */
    public static void setParentKitProduct(List<OrderItem> newOrderItemtList) { 
        Set<ID> productsIds = new Set<ID>();
        for(OrderItem orderItem: newOrderItemtList) {
            productsIds.add(orderItem.Product2Id);
        }
        Map<Id,Product2> parentProducts = new Map<ID, Product2>([SELECT Id, ParentKit__c FROM Product2 WHERE ID IN :productsIds]); 
        for(OrderItem orderItem: newOrderItemtList) {
            orderItem.ParentKit__c = parentProducts.get(orderItem.Product2Id).ParentKit__c;
        }
    }
    
    /*Set Floor Price */
    public static void setFloorPrice(List<OrderItem> newOrderItemtList) { 
        Set<ID> pricebookEntryIds = new Set<ID>();
        for(OrderItem orderItem: newOrderItemtList) {
            pricebookEntryIds.add(orderItem.PricebookEntryId);
        }
        Map<Id,PricebookEntry> pricebookEntries = new Map<ID, PricebookEntry>([SELECT Id, FloorPrice__c FROM PricebookEntry WHERE ID IN :pricebookEntryIds]); 
        for(OrderItem orderItem: newOrderItemtList) {
            Decimal floorPrice = pricebookEntries.get(orderItem.PricebookEntryId).FloorPrice__c;
            if(! String.isBlank(String.Valueof(floorPrice))){
            	orderItem.TotalFloorPrice__c = floorPrice * orderItem.Quantity;
            	orderItem.FloorPrice__c = floorPrice;
            	orderItem.TotalFloorPriceDeviation__c = (orderItem.SalesPrice__c - floorPrice) * orderItem.Quantity;
            }
        }
    }

}