src/objects/Contract.object
<CustomObject>
    <recordTypes>
        <fullName>Contract</fullName>
        <active>true</active>
        <description>Intended to be the global contract record type - first version is a very basic contract launched in BeNeLux</description>
        <label>Contract</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ContractItem__c.object
<CustomObject>
    <fields>
        <fullName>NoDelete__c</fullName>
        <formula>Text( Contract__r.Status ) != &apos;Draft&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>No Delete</label>
        <type>Checkbox</type>
    </fields>
    <label>Contract Item</label>
    <nameField>
        <label>Contract Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContractItemTriggerHelper.cls
/*----------------------------------------------------------------------------------------
Author:         Roberto Narbona
Description:    Contract Item Trigger Helper Class
Test class      

History
----------------------------------------------------------------------------------------*/
public with sharing class ContractItemTriggerHelper {

    public static final String PREVENT_DELETION_MESSAGE = 'Contract items that are not in Draft contracts cannot be deleted.';

    public static void canBeDeleted(List<ContractItem__c> oldContractItemList) {
        if (oldContractItemList.isEmpty()) return ;
        for (ContractItem__c cI: oldContractItemList){
            if (cI.NoDelete__c == true){
                cI.addError(PREVENT_DELETION_MESSAGE);
            }
        }
    }
}