src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Previous_contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous contract</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contract.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Previous contract</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Contract</fullName>
        <active>true</active>
        <description>Intended to be the global contract record type - first version is a very basic contract launched in BeNeLux</description>
        <label>Contract</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Implants</fullName>
                    <label>Global DPG</label>
                </value>
                <value>
                    <fullName>All Ortho</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ATF</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
                <value>
                    <fullName>BHR</fullName>
                </value>
                <value>
                    <fullName>BHS</fullName>
                </value>
                <value>
                    <fullName>BIH</fullName>
                </value>
                <value>
                    <fullName>BLM</fullName>
                </value>
                <value>
                    <fullName>BLR</fullName>
                </value>
                <value>
                    <fullName>BLZ</fullName>
                </value>
                <value>
                    <fullName>BMU</fullName>
                </value>
                <value>
                    <fullName>BOL</fullName>
                </value>
                <value>
                    <fullName>BRA</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContractTriggerHelper.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Kevin Do (Salesforce) 20190924
Description:    Contract Trigger Helper Class
Test Class:     
History:
20200205    Kevin Do            Bug fix on updateAllowedDiscount to recalculate formula fields 
20190924    Kevin Do            Created Class
20211206	Roberto Narbona		Uopdated SAQL query(TFUS-000003784)
20231114    Richard Trum        Cleaned up methods related to the retired Pricing Contract record type/functionality
----------------------------------------------------------------------------------------*/

global with sharing class ContractTriggerHelper {
    private static final String SOBJECT_NAME = 'Contract';
    
    /*------------------------------------------------------------  
    Description:    Method migrated from Contract_Default_Process_Builder: Contract: Set start parameters criteria node 
                    Containing Contract_Update_sales_history Flow and Contract_find_previous Flow
                    Should only be called before insert or from Update sales history button on Contract record page.
    Inputs:         @param newContractList
    ------------------------------------------------------------*/
    public static void setStartParameters(List<Contract> newContractList) {
        // Create a Set of AccountIds of the Contract AccountIds
        Set<Id> accountToQueryIdSet = new Set<Id>();
        Set<Contract> contractToUpdateSet = new Set<Contract>();
        for (Contract contractRecord : newContractList) {
            // Only update Contracts with Record Type 'DiscountContract'
            if (contractRecord.RecordTypeId == GlobalUtils.getRecordTypeId(SOBJECT_NAME, 'DiscountContract')) {
                accountToQueryIdSet.add(contractRecord.AccountId);
                contractToUpdateSet.add(contractRecord);
            }
        }
         // Get related Account records
        Map<Id, Account> relatedAccountMap = new Map<Id, Account>([
            SELECT Id, OneSF_Id__c, Country__c,
                (SELECT Id, AccountId FROM Contracts ORDER BY CreatedDate DESC LIMIT 1)
            FROM Account
            WHERE Id IN :accountToQueryIdSet
        ]);

        for (Contract contractToUpdate: contractToUpdateSet) {
            // Only update Contracts where Account.Country__c is 'DE'
            if ('DE'.equalsIgnoreCase(relatedAccountMap.get(contractToUpdate.AccountId).Country__c)) {
                Account relatedAccount = relatedAccountMap.get(contractToUpdate.AccountId);
                setPreviousContract(contractToUpdate, relatedAccount);
            }
        }
    }

    /*------------------------------------------------------------  
    Description:    Helper method for setStartParameters()
                    Method migrated from Contract_Default_Process_Builder (Find previous contract)
                    Updates Contract sales fields based on its' Account fields
    Inputs:         @param contractToUpdate, @param relatedAccount
    ------------------------------------------------------------*/
    public static void setPreviousContract(Contract contractToUpdate, Account relatedAccount) {
        if (!relatedAccount.Contracts.isEmpty() && null == contractToUpdate.Previous_contract__c && relatedAccount.Contracts[0].Id != contractToUpdate.Id) {
            contractToUpdate.Previous_contract__c = relatedAccount.Contracts[0].Id;
        }
    }

}