src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PreferredLanguage</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Profession__c</fullName>
        <description>Dependent upon Product Area</description>
        <label>Role/Profession</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Advanced Practice Dental Therapist</fullName>
                </value>
                <value>
                    <fullName>Clinical Director</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Dean</fullName>
                    <label>Dean/Head</label>
                </value>
                <value>
                    <fullName>Dental Assistant</fullName>
                </value>
                <value>
                    <fullName>Dental Hygienist</fullName>
                </value>
                <value>
                    <fullName>Dental Laboratory General Manager</fullName>
                </value>
                <value>
                    <fullName>Dental Laboratory Office Manager</fullName>
                </value>
                <value>
                    <fullName>Dental Laboratory Technician</fullName>
                </value>
                <value>
                    <fullName>Dental Nurse</fullName>
                </value>
                <value>
                    <fullName>Dental Nurse Manager</fullName>
                </value>
                <value>
                    <fullName>Dental Student</fullName>
                </value>
                <value>
                    <fullName>Dental Technician</fullName>
                </value>
                <value>
                    <fullName>Dental Technician Master</fullName>
                </value>
                <value>
                    <fullName>Dental Therapist</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Denturist</fullName>
                </value>
                <value>
                    <fullName>Distributor General Manager</fullName>
                </value>
                <value>
                    <fullName>Distributor Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Doctor</fullName>
                </value>
                <value>
                    <fullName>DS Employee</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Endodontist</fullName>
                </value>
                <value>
                    <fullName>Faculty/Instructor/Professor</fullName>
                </value>
                <value>
                    <fullName>General Dentist</fullName>
                </value>
                <value>
                    <fullName>General Manager</fullName>
                </value>
                <value>
                    <fullName>Head of Department</fullName>
                </value>
                <value>
                    <fullName>Implant Manager</fullName>
                </value>
                <value>
                    <fullName>Implantologist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/PreferredLanguage.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <customValue>
        <fullName>Danish</fullName>
    </customValue>
    <customValue>
        <fullName>Dutch</fullName>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>Finnish</fullName>
    </customValue>
    <customValue>
        <fullName>Flemish</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>German</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <customValue>
        <fullName>Japanese</fullName>
    </customValue>
    <customValue>
        <fullName>Norwegian</fullName>
    </customValue>
    <customValue>
        <fullName>Portuguese</fullName>
    </customValue>
    <customValue>
        <fullName>Russian</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>Swedish</fullName>
    </customValue>
    <customValue>
        <fullName>Thai</fullName>
    </customValue>
    <customValue>
        <fullName>Vietnamese</fullName>
    </customValue>
    <customValue>
        <fullName>Mandarin</fullName>
        <isActive>false</isActive>
        <label>Mandarin</label>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
        <isActive>false</isActive>
        <label>DE</label>
    </customValue>
    <customValue>
        <fullName>,English</fullName>
        <isActive>false</isActive>
        <label>,English</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
        <isActive>false</isActive>
        <label>EN</label>
    </customValue>
    <description>Used on Contacts and Leads.</description>
    <masterLabel>Preferred Language</masterLabel>
</GlobalValueSet>

src/classes/UpdateContactsBypassDuplicate.cls
/**
 * @Author          Omar (ohanafi@salesforce.com)
 * @Description     Class for updating contacts without triggering the duplicate rule.
 * @Test-Class      Test_UpdateContactsBypassDuplicate
 *
 * @History
 * 03-02-2023   Omar Hanafi     Created the UpdateContactsBypassDuplicate class.
 */

public with sharing class UpdateContactsBypassDuplicate {

    /**
     * updateContact Method to update contacts without triggering the duplicate rule.
     * @author ohanafi@salesforce.com | 03-02-2023
     *
     * @param contacts   List of ContactRecord objects
     *
     * @return void
     */
    @InvocableMethod(
            label='Update Contacts Bypass Duplicate'
            description='Update contacts without triggering the duplicate rule'
            category='Contact'
    )
    public static void updateContact(List<ContactRecord> contacts) {
        Database.DMLOptions dmlOpts = new Database.DMLOptions();
        dmlOpts.duplicateRuleHeader.allowSave = true;

        // Update the contacts
        List<Contact> recordsToUpdate = new List<Contact>();
        for (ContactRecord contactRecord : contacts) {
            recordsToUpdate.add(new Contact(
                    Id = contactRecord.Id,
                    Email = contactRecord.Email,
                    FirstName = contactRecord.FirstName,
                    LastName = contactRecord.LastName,
                    Preferred_Language__c = contactRecord.PreferredLanguage,
                    Profession__c = contactRecord.Profession,
                    Salutation = contactRecord.Salutation
            ));
        }

        Database.update(recordsToUpdate, dmlOpts);
    }

    //Contact Record class used to pass data to the UpdateContactsBypassDuplicate method.
    public class ContactRecord {
        @InvocableVariable(required=false)
        public Id Id;
        @InvocableVariable(required=false)
        public String Email;
        @InvocableVariable(required=false)
        public String FirstName;
        @InvocableVariable(required=true)
        public String LastName;
        @InvocableVariable(required=false)
        public String PreferredLanguage;
        @InvocableVariable(required=false)
        public String Profession;
        @InvocableVariable(required=false)
        public String Salutation;
    }
}