src/objects/Contract.object
<CustomObject>
    <recordTypes>
        <fullName>Contract</fullName>
        <active>true</active>
        <description>Intended to be the global contract record type - first version is a very basic contract launched in BeNeLux</description>
        <label>Contract</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>User_Country__c</fullName>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_Code_full</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src/globalValueSets/Country_Code_full.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>BEX</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>Croatia</fullName>
    </customValue>
    <customValue>
        <fullName>Cyprus</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor Markets</fullName>
    </customValue>
    <customValue>
        <fullName>Egypt</fullName>
    </customValue>
    <customValue>
        <fullName>Estonia</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Greece</fullName>
    </customValue>
    <customValue>
        <fullName>Holland</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>HQ: DE</fullName>
    </customValue>
    <customValue>
        <fullName>HQ: NL</fullName>
    </customValue>
    <customValue>
        <fullName>HQ: SE</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesia</fullName>
    </customValue>
    <customValue>
        <fullName>Israel</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <masterLabel>Country Code (full)</masterLabel>
</GlobalValueSet>

src/classes/NewContractController.cls
/*-------------------------------------------------------------------------------------------------	
Author: 	naoussar@salesforce.com (Salesforce) 2022094 	
Description:   	NewContractController controller of the new Contract action on the account page 
Test Class:     Test_NewContractController
History	
2022094   created (TFUS-000004611) 
--------------------------------------------------------------------------------------------------*/
public with sharing class NewContractController {
    /*------------------------------------------------------------	
	Description:   isUserEligibleForCustomContractCreation to decide if the user is eligible for creating a contract 
					using flow or the std creation
	Inputs:    @recordId : id of the account from which we are trying to create teh contract
	------------------------------------------------------------*/
    @AuraEnabled
    public Static Boolean isUserEligibleForCustomContractCreation(String recordId){
         Boolean result; 
         String country = [ SELECT User_Country__c FROM User WHERE Id =:UserInfo.getUserId() LIMIT 1][0].User_Country__c;
         String accType = [SELECT OneAccount_Type__c  from Account WHERE Id =: recordId][0].OneAccount_Type__c;
         Boolean hasPermission = FeatureManagement.checkPermission('DS_Activate');
         if(accType != 'Distributor' && (country == 'Germany' || country == 'Austria' || hasPermission)){
            result = true;
         }else{
            result = false;
         }
         return result;
    }
    
}