src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PreferredLanguage</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Profession__c</fullName>
        <description>Dependent upon Product Area</description>
        <label>Role/Profession</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Advanced Practice Dental Therapist</fullName>
                </value>
                <value>
                    <fullName>Clinical Director</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Dean</fullName>
                    <label>Dean/Head</label>
                </value>
                <value>
                    <fullName>Dental Assistant</fullName>
                </value>
                <value>
                    <fullName>Dental Hygienist</fullName>
                </value>
                <value>
                    <fullName>Dental Laboratory General Manager</fullName>
                </value>
                <value>
                    <fullName>Dental Laboratory Office Manager</fullName>
                </value>
                <value>
                    <fullName>Dental Laboratory Technician</fullName>
                </value>
                <value>
                    <fullName>Dental Nurse</fullName>
                </value>
                <value>
                    <fullName>Dental Nurse Manager</fullName>
                </value>
                <value>
                    <fullName>Dental Student</fullName>
                </value>
                <value>
                    <fullName>Dental Technician</fullName>
                </value>
                <value>
                    <fullName>Dental Technician Master</fullName>
                </value>
                <value>
                    <fullName>Dental Therapist</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Denturist</fullName>
                </value>
                <value>
                    <fullName>Distributor General Manager</fullName>
                </value>
                <value>
                    <fullName>Distributor Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Doctor</fullName>
                </value>
                <value>
                    <fullName>DS Employee</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Endodontist</fullName>
                </value>
                <value>
                    <fullName>Faculty/Instructor/Professor</fullName>
                </value>
                <value>
                    <fullName>General Dentist</fullName>
                </value>
                <value>
                    <fullName>General Manager</fullName>
                </value>
                <value>
                    <fullName>Head of Department</fullName>
                </value>
                <value>
                    <fullName>Implant Manager</fullName>
                </value>
                <value>
                    <fullName>Implantologist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Specialty__c</fullName>
        <label>Specialty</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Profession__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alloys</fullName>
                </value>
                <value>
                    <fullName>CAD/CAM</fullName>
                </value>
                <value>
                    <fullName>Ceramic</fullName>
                </value>
                <value>
                    <fullName>Crown &amp; Bridge</fullName>
                </value>
                <value>
                    <fullName>Dental Public Health</fullName>
                </value>
                <value>
                    <fullName>Dentist Anesthesiologist</fullName>
                </value>
                <value>
                    <fullName>Emergency Medicine</fullName>
                </value>
                <value>
                    <fullName>Endodontics</fullName>
                </value>
                <value>
                    <fullName>Esthetics &amp; Plastic Surgery</fullName>
                </value>
                <value>
                    <fullName>Generalist</fullName>
                </value>
                <value>
                    <fullName>General Medicine</fullName>
                </value>
                <value>
                    <fullName>General Practice</fullName>
                </value>
                <value>
                    <fullName>Imaging</fullName>
                </value>
                <value>
                    <fullName>Implantology</fullName>
                </value>
                <value>
                    <fullName>Investments</fullName>
                </value>
                <value>
                    <fullName>Model Casting</fullName>
                </value>
                <value>
                    <fullName>Oral and Maxillofacial Pathology</fullName>
                </value>
                <value>
                    <fullName>Oral and Maxillofacial Radiology</fullName>
                </value>
                <value>
                    <fullName>Oral and Maxillofacial Surgery</fullName>
                </value>
                <value>
                    <fullName>Orofacial Pain</fullName>
                </value>
                <value>
                    <fullName>Orthodontics and Dentofacial Orthopedics</fullName>
                </value>
                <value>
                    <fullName>Pediatric Dentistry</fullName>
                </value>
                <value>
                    <fullName>Periodontics</fullName>
                </value>
                <value>
                    <fullName>Prevention</fullName>
                </value>
                <value>
                    <fullName>Prosthodontics</fullName>
                </value>
                <value>
                    <fullName>Removable Prosthetics</fullName>
                </value>
                <value>
                    <fullName>Restorative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>PreferredLanguage__c</fullName>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PreferredLanguage</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Profession__c</fullName>
        <description>Profession of Lead - Dependent upon Product Area</description>
        <label>Profession</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Dental Assistant</fullName>
                </value>
                <value>
                    <fullName>Dental Hygienist</fullName>
                </value>
                <value>
                    <fullName>Dental Student</fullName>
                </value>
                <value>
                    <fullName>Dental Technician</fullName>
                </value>
                <value>
                    <fullName>Denturist</fullName>
                </value>
                <value>
                    <fullName>Endodontist</fullName>
                </value>
                <value>
                    <fullName>Faculty/Instructor/Professor</fullName>
                </value>
                <value>
                    <fullName>General Dentist</fullName>
                </value>
                <value>
                    <fullName>General Manager</fullName>
                </value>
                <value>
                    <fullName>Implant Manager</fullName>
                </value>
                <value>
                    <fullName>Implantologist</fullName>
                </value>
                <value>
                    <fullName>Lab Owner</fullName>
                </value>
                <value>
                    <fullName>Maxillofacial Surgeon</fullName>
                </value>
                <value>
                    <fullName>Oral surgeon</fullName>
                </value>
                <value>
                    <fullName>Orthodonist</fullName>
                </value>
                <value>
                    <fullName>Other staff Dental</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Periodontist</fullName>
                </value>
                <value>
                    <fullName>Post Graduate trainee</fullName>
                </value>
                <value>
                    <fullName>Prosthodontist</fullName>
                </value>
                <value>
                    <fullName>Purchaser</fullName>
                </value>
                <value>
                    <fullName>Registrar</fullName>
                </value>
                <value>
                    <fullName>Restorative Dentist</fullName>
                </value>
                <value>
                    <fullName>Sales Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RoleProfession__c</fullName>
        <label>Role/Profession</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RoleProfession</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Specialty__c</fullName>
        <label>Specialty</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Specialty</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src/globalValueSets/PreferredLanguage.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <customValue>
        <fullName>Danish</fullName>
    </customValue>
    <customValue>
        <fullName>Dutch</fullName>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>Finnish</fullName>
    </customValue>
    <customValue>
        <fullName>Flemish</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>German</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <customValue>
        <fullName>Japanese</fullName>
    </customValue>
    <customValue>
        <fullName>Norwegian</fullName>
    </customValue>
    <customValue>
        <fullName>Portuguese</fullName>
    </customValue>
    <customValue>
        <fullName>Russian</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>Swedish</fullName>
    </customValue>
    <customValue>
        <fullName>Thai</fullName>
    </customValue>
    <customValue>
        <fullName>Vietnamese</fullName>
    </customValue>
    <customValue>
        <fullName>Mandarin</fullName>
        <isActive>false</isActive>
        <label>Mandarin</label>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
        <isActive>false</isActive>
        <label>DE</label>
    </customValue>
    <customValue>
        <fullName>,English</fullName>
        <isActive>false</isActive>
        <label>,English</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
        <isActive>false</isActive>
        <label>EN</label>
    </customValue>
    <description>Used on Contacts and Leads.</description>
    <masterLabel>Preferred Language</masterLabel>
</GlobalValueSet>

src/globalValueSets/RoleProfession.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Advanced Practice Dental Therapist</fullName>
    </customValue>
    <customValue>
        <fullName>Clinical Director</fullName>
    </customValue>
    <customValue>
        <fullName>Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Contractor</fullName>
    </customValue>
    <customValue>
        <fullName>Dean / Head</fullName>
    </customValue>
    <customValue>
        <fullName>Dental Assistant</fullName>
    </customValue>
    <customValue>
        <fullName>Dental Hygienist</fullName>
    </customValue>
    <customValue>
        <fullName>Dental Laboratory Technician</fullName>
    </customValue>
    <customValue>
        <fullName>Dental Therapist</fullName>
    </customValue>
    <customValue>
        <fullName>Dentist</fullName>
    </customValue>
    <customValue>
        <fullName>Denturist</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor Sales Rep</fullName>
    </customValue>
    <customValue>
        <fullName>Doctor</fullName>
    </customValue>
    <customValue>
        <fullName>DS Employee</fullName>
    </customValue>
    <customValue>
        <fullName>Employee</fullName>
    </customValue>
    <customValue>
        <fullName>General Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Implant Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Office Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Office Staff/Front Desk</fullName>
    </customValue>
    <customValue>
        <fullName>Oral Medicinist</fullName>
    </customValue>
    <customValue>
        <fullName>Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Post Graduate Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Prevention Professional</fullName>
    </customValue>
    <customValue>
        <fullName>Professor</fullName>
    </customValue>
    <customValue>
        <fullName>Purchaser</fullName>
    </customValue>
    <customValue>
        <fullName>Purchasing Assistant</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Nurse</fullName>
    </customValue>
    <customValue>
        <fullName>Registrar</fullName>
    </customValue>
    <customValue>
        <fullName>Student in an Organized Health Care Education/Training Program</fullName>
    </customValue>
    <customValue>
        <fullName>Surgeon</fullName>
    </customValue>
    <masterLabel>Role/Profession</masterLabel>
</GlobalValueSet>

src/globalValueSets/Specialty.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Dental Public Health</fullName>
    </customValue>
    <customValue>
        <fullName>Dentist Anesthesiologist</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Endodontics</fullName>
    </customValue>
    <customValue>
        <fullName>Esthetics &amp; Plastic Surgery</fullName>
    </customValue>
    <customValue>
        <fullName>General Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>General Practice</fullName>
    </customValue>
    <customValue>
        <fullName>Implantology</fullName>
    </customValue>
    <customValue>
        <fullName>Oral and Maxillofacial Pathology</fullName>
    </customValue>
    <customValue>
        <fullName>Oral and Maxillofacial Radiology</fullName>
    </customValue>
    <customValue>
        <fullName>Oral and Maxillofacial Surgery</fullName>
    </customValue>
    <customValue>
        <fullName>Orofacial Pain</fullName>
    </customValue>
    <customValue>
        <fullName>Orthodontics and Dentofacial Orthopedics</fullName>
    </customValue>
    <customValue>
        <fullName>Pediatric Dentistry</fullName>
    </customValue>
    <customValue>
        <fullName>Periodontics</fullName>
    </customValue>
    <customValue>
        <fullName>Prevention</fullName>
    </customValue>
    <customValue>
        <fullName>Prosthodontics</fullName>
    </customValue>
    <masterLabel>Specialty</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/leadContactController.cls
/*------------------------------------------------------------	
Author: 		Richard Trum (Glimt) 2023-08-22 	
Description:   	Class for handling comparisons between leads and contacts
Test class:     
History:        
------------------------------------------------------------*/

public with sharing class leadContactController {
    
    @AuraEnabled(cacheable=true)
    public static Lead getLeadDetails(String leadId){
        Lead l = new Lead();
        System.debug(leadId);
        try {
            l = [SELECT Id, FirstName, LastName, Email, Phone, Salutation, RoleProfession__c, Specialty__c, PreferredLanguage__c FROM Lead WHERE Id =: leadId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return l;
    }

    @AuraEnabled(cacheable=true)
    public static Contact getContactDetails(String contactId){
        Contact c = new Contact();
        try {
            c = [SELECT Id, FirstName, LastName, Email, Phone, Salutation, Profession__c, Specialty__c, Preferred_Language__c FROM Contact WHERE Id =: contactId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return c;
    }

}