src/objects/Country__c.object
<CustomObject>
    <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Implants</fullName>
                    <label>Global DPG</label>
                </value>
                <value>
                    <fullName>All Ortho</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ATF</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
                <value>
                    <fullName>BHR</fullName>
                </value>
                <value>
                    <fullName>BHS</fullName>
                </value>
                <value>
                    <fullName>BIH</fullName>
                </value>
                <value>
                    <fullName>BLM</fullName>
                </value>
                <value>
                    <fullName>BLR</fullName>
                </value>
                <value>
                    <fullName>BLZ</fullName>
                </value>
                <value>
                    <fullName>BMU</fullName>
                </value>
                <value>
                    <fullName>BOL</fullName>
                </value>
                <value>
                    <fullName>BRA</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Workflow__c.object
<CustomObject>
    <fields>
        <fullName>Countries__c</fullName>
        <description>To which countries, this workflow should be excluded for account profiling.</description>
        <label>Countries</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_Code_2_digit</valueSetName>
        </valueSet>
    </fields>
    <label>Workflow</label>
    <nameField>
        <label>Workflow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workflows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkflowProfiling__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Workflows Profiling</relationshipLabel>
        <relationshipName>Workflows_Profiling</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rating</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Workflow__c</fullName>
        <label>Workflow</label>
        <referenceTo>Workflow__c</referenceTo>
        <relationshipLabel>Workflows Profiling</relationshipLabel>
        <relationshipName>Workflows_Profiling</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workflow Profiling</label>
    <nameField>
        <displayFormat>WFP #{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workflows Profiling</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Country_Code_2_digit.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AN</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AQ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AS</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AX</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BF</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BJ</fullName>
    </customValue>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>US</fullName>
    </customValue>
    <masterLabel>Country Code (2-digit)</masterLabel>
</GlobalValueSet>

src/classes/Test_WorkflowProfilingController.cls
/**
 * @Author          Omar (ohanafi@salesforce.com)
 * @Description     Test class of WorkflowProfilingController
 *
 * @History
 * 12-12-2023   Omar     Created test class
 */

@isTest(seeAllData=false)
public without sharing class Test_WorkflowProfilingController {

    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.returnUsers(1, '#System: System Administrator');
        insert userList;
        TestDataFactory.createGlobalIntegrationSettings(userList);
        TestDataFactory.createDefaultOrgLevelBypassPB();

    }

    @isTest
    static void testGetWorkflows() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        System.runAs(testUser) {

            // Create test account
            List<Account> testAccount = TestDataFactory.returnAccounts(1, 'CIM_Account', testUser.Id);
            testAccount[0].Country__c = 'US';
            insert testAccount;

            Workflow__c testWorkflow = new Workflow__c(Name = 'Test Workflow', Countries__c = 'US');
            insert testWorkflow;

            Test.startTest();
            List<Workflow__c> workflows = WorkflowProfilingController.getWorkflows(testAccount[0].Id);
            Test.stopTest();

            // Assertions
            System.assertEquals(1, workflows.size());
        }
    }

    @isTest
    static void testGetWorkflowProfilingsByAccount() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        System.runAs(testUser) {

            // Create test account
            List<Account> testAccount = TestDataFactory.returnAccounts(1, 'CIM_Account', testUser.Id);
            testAccount[0].Country__c = 'US';
            insert testAccount;

            Workflow__c testWorkflow = new Workflow__c(Name = 'Test Workflow', Countries__c = 'US');
            insert testWorkflow;

            WorkflowProfiling__c testWorkflowProfiling = new WorkflowProfiling__c(Account__c = testAccount[0].Id, Workflow__c = testWorkflow.Id);
            insert testWorkflowProfiling;

            Test.startTest();
            List<WorkflowProfiling__c> workflowProfilings = WorkflowProfilingController.getWorkflowProfilingsByAccount(testAccount[0].Id);
            Test.stopTest();

            // Assertions
            System.assertEquals(1, workflowProfilings.size());
            System.assertEquals(testAccount[0].Id, workflowProfilings[0].Account__c);

        }
    }

    @isTest
    static void testCreateOrUpdateWorkflowProfilings() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        System.runAs(testUser) {

            // Create test account
            List<Account> testAccount = TestDataFactory.returnAccounts(1, 'CIM_Account', testUser.Id);
            testAccount[0].Country__c = 'US';
            insert testAccount;

            Workflow__c testWorkflow = new Workflow__c(Name = 'Test Workflow', Countries__c = 'US');
            insert testWorkflow;

            WorkflowProfiling__c testWorkflowProfiling = new WorkflowProfiling__c(Account__c = testAccount[0].Id, Workflow__c = testWorkflow.Id, Rating__c = 3);
            insert testWorkflowProfiling;

            testWorkflowProfiling.Rating__c = 5;
            List<WorkflowProfiling__c> newRecords = new List<WorkflowProfiling__c>{ testWorkflowProfiling };

            Test.startTest();
            WorkflowProfilingController.createOrUpdateWorkflowProfilings(newRecords);
            Test.stopTest();

            // Assertions
            List<WorkflowProfiling__c> insertedRecords = [SELECT Id, Rating__c FROM WorkflowProfiling__c WHERE Account__c = :testAccount[0].Id AND Workflow__c = :testWorkflow.Id];
            System.assertEquals(1, insertedRecords.size());
            System.assertEquals(5, insertedRecords[0].Rating__c);


        }
    }

    @isTest
    static void testDeleteWorkflowProfilings() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        System.runAs(testUser) {

            // Create test account
            List<Account> testAccount = TestDataFactory.returnAccounts(1, 'CIM_Account', testUser.Id);
            testAccount[0].Country__c = 'US';
            insert testAccount;

            Workflow__c testWorkflow = new Workflow__c(Name = 'Test Workflow', Countries__c = 'US');
            insert testWorkflow;

            WorkflowProfiling__c testWorkflowProfiling = new WorkflowProfiling__c(Account__c = testAccount[0].Id, Workflow__c = testWorkflow.Id);
            insert testWorkflowProfiling;

            List<Id> recordIdsToDelete = new List<Id>{ testWorkflowProfiling.Id };

            Test.startTest();
            WorkflowProfilingController.deleteWorkflowProfilings(recordIdsToDelete);
            Test.stopTest();

            // Assertions
            List<WorkflowProfiling__c> deletedRecords = [SELECT Id FROM WorkflowProfiling__c WHERE Id = :testWorkflowProfiling.Id];
            System.assertEquals(0, deletedRecords.size());


        }
    }
}