src/objects/Country__c.object
<CustomObject>
    <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Implants</fullName>
                    <label>Global DPG</label>
                </value>
                <value>
                    <fullName>All Ortho</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ATF</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
                <value>
                    <fullName>BHR</fullName>
                </value>
                <value>
                    <fullName>BHS</fullName>
                </value>
                <value>
                    <fullName>BIH</fullName>
                </value>
                <value>
                    <fullName>BLM</fullName>
                </value>
                <value>
                    <fullName>BLR</fullName>
                </value>
                <value>
                    <fullName>BLZ</fullName>
                </value>
                <value>
                    <fullName>BMU</fullName>
                </value>
                <value>
                    <fullName>BOL</fullName>
                </value>
                <value>
                    <fullName>BRA</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Field_Sales_Project_Members__c.object
<CustomObject>
    <description>Used to track targets for sales for specified initiatives based on target lists, regional initiatives, or customer interactions.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Leads</relationshipLabel>
        <relationshipName>Field_Sales_Project_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>UserCountry__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>3D Imaging</fullName>
                    <isActive>false</isActive>
                    <label>3D Imaging</label>
                </value>
                <value>
                    <fullName>ATLANTIS</fullName>
                    <isActive>false</isActive>
                    <label>ATLANTIS</label>
                </value>
                <value>
                    <fullName>CEREC Equipment</fullName>
                    <isActive>false</isActive>
                    <label>CEREC Equipment</label>
                </value>
                <value>
                    <fullName>Class II</fullName>
                </value>
                <value>
                    <fullName>Consumables</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Digital Group</fullName>
                </value>
                <value>
                    <fullName>Digital Services</fullName>
                </value>
                <value>
                    <fullName>Digital Solutions</fullName>
                    <isActive>false</isActive>
                    <label>Digital Solutions</label>
                </value>
                <value>
                    <fullName>Endentulous</fullName>
                    <isActive>false</isActive>
                    <label>Endentulous</label>
                </value>
                <value>
                    <fullName>Endodontics</fullName>
                </value>
                <value>
                    <fullName>Equipment</fullName>
                </value>
                <value>
                    <fullName>Equipment &amp; Imaging</fullName>
                </value>
                <value>
                    <fullName>Extra Oral Imaging</fullName>
                    <isActive>false</isActive>
                    <label>Extra Oral Imaging</label>
                </value>
                <value>
                    <fullName>Implants</fullName>
                </value>
                <value>
                    <fullName>InLab</fullName>
                    <isActive>false</isActive>
                    <label>InLab</label>
                </value>
                <value>
                    <fullName>Intra Oral Imaging</fullName>
                    <isActive>false</isActive>
                    <label>Intra Oral Imaging</label>
                </value>
                <value>
                    <fullName>Midwest Equipment</fullName>
                    <isActive>false</isActive>
                    <label>Midwest Equipment</label>
                </value>
                <value>
                    <fullName>Orthodontics</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Preventive</fullName>
                    <isActive>false</isActive>
                    <label>Preventive</label>
                </value>
                <value>
                    <fullName>Procedures</fullName>
                    <isActive>false</isActive>
                    <label>Procedures</label>
                </value>
                <value>
                    <fullName>Prosthetics</fullName>
                </value>
                <value>
                    <fullName>Regenerative</fullName>
                    <isActive>false</isActive>
                    <label>Regenerative</label>
                </value>
                <value>
                    <fullName>Restorative</fullName>
                    <isActive>false</isActive>
                    <label>Restorative</label>
                </value>
                <value>
                    <fullName>Root To Crown</fullName>
                </value>
                <value>
                    <fullName>Single Unit Crown</fullName>
                </value>
                <value>
                    <fullName>Treatment Centers</fullName>
                    <isActive>false</isActive>
                    <label>Treatment Centers</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3 AND 5) OR (2 AND 3 AND 4)</booleanFilter>
            <errorMessage>You must select a distributor.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>ERP Distributor, Non-ERP Distributor, DNA Distributor</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>CIM Account</value>
            </filterItems>
            <filterItems>
                <field>Account.OneAccount_Type__c</field>
                <operation>equals</operation>
                <value>Distributor, DNA Distributor</value>
            </filterItems>
            <filterItems>
                <field>Account.DistributorCategories__c</field>
                <operation>notContain</operation>
                <valueField>$Source.Category__c</valueField>
            </filterItems>
            <filterItems>
                <field>Account.DistributorCategories__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Leads (Distributor)</relationshipLabel>
        <relationshipName>Prospects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Lead</label>
    <nameField>
        <displayFormat>Ld-{0000000}</displayFormat>
        <label>LD ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LeadOpportunitySetting__mdt.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consumables</fullName>
                    <default>true</default>
                    <label>Consumables</label>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Digital Group</fullName>
                </value>
                <value>
                    <fullName>Endodontics</fullName>
                </value>
                <value>
                    <fullName>Equipment</fullName>
                </value>
                <value>
                    <fullName>Equipment &amp; Imaging</fullName>
                </value>
                <value>
                    <fullName>Implants</fullName>
                </value>
                <value>
                    <fullName>Orthodontics</fullName>
                </value>
                <value>
                    <fullName>Prosthetics</fullName>
                </value>
                <value>
                    <fullName>Class II</fullName>
                </value>
                <value>
                    <fullName>Single Unit Crown</fullName>
                </value>
                <value>
                    <fullName>Root To Crown</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Digital Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lead &amp; Opportunity Setting</label>
    <pluralLabel>Lead &amp; Opportunity Settings</pluralLabel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3 AND 5) OR (2 AND 3 AND 4)</booleanFilter>
            <errorMessage>You must select a distributor.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>ERP Distributor, Non-ERP Distributor, DNA Distributor</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>CIM Account</value>
            </filterItems>
            <filterItems>
                <field>Account.OneAccount_Type__c</field>
                <operation>equals</operation>
                <value>Distributor, DNA Distributor</value>
            </filterItems>
            <filterItems>
                <field>Account.DistributorCategories__c</field>
                <operation>notContain</operation>
                <valueField>$Source.NA_Category__c</valueField>
            </filterItems>
            <filterItems>
                <field>Account.DistributorCategories__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <infoMessage>Search for the Delaer connected to this opportunity</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Distributor)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>GET</fullName>
        <active>true</active>
        <businessProcess>GET</businessProcess>
        <label>X DO NOT USE 2t</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SuggestedOwnerManager.cls
/**
 * Author:         Houssam ADIB (Salesforce)
 * Description:
 *
 * Encapsulates the logic for assigning suggested owners to Sales Leads and other objects. Key Steps :
 * 1- Category: The code first considers the sales lead's category to match with lead opportunity settings.
 * 2- Brand: Within the category, it checks if the sales lead's brand matches the brand settings in the lead opportunity settings.
 * 3- Role: It then examines the user roles defined in the lead opportunity settings.
 *
 * Test class:      Test_BatchSalesLeadAssignSOwner
 * Modifications Log
 * Ver   Date         Author                    Modification
 * 1.0   06-15-2021   hadib@salesforce.com      Initial Version
 */
public class SuggestedOwnerManager {

    private static final String DEALER = 'Dealer';

    /**
     * ROOT METHOD
     * Method to assign suggested owners to a list of sales leads
     * @author hadib@salesforce.com | 06-09-2023
     *
     * @param salesLeadsIds Sales Leads Ids
     */
    @InvocableMethod(Label='Assign Suggested Owner to Sales Leads')
    public static void assignSuggestedOwners(List<String> salesLeadsIds)
    {
        try
        {
            // 0- Query Sales Leads Records
            List<Field_Sales_Project_Members__c> salesLeads = getSalesLeadsRecords(salesLeadsIds);

            // 1- Custom Metadata
            Map<String, List<LeadOpportunitySetting__mdt>> leadOpportunitySettingMap = getLeadOpportunitySettings();

            // 2- Account Territory
            Map<Id, List<Id>> accountTerritoryMap = getAccountTerritoryMap(salesLeads);

            // 3- User Territory
            Map<Id, Map<String, UserTerritory2Association>> territoryIdUserAssociationMap = getTerritoryIdUserAssociationMap(accountTerritoryMap);

            // 4- Find Sales Lead to suggest their owner
            List<Field_Sales_Project_Members__c> leadsToUpdate = detectSalesLeadsThatNeedsToBeUpdated(salesLeads,
                    leadOpportunitySettingMap,
                    accountTerritoryMap,
                    territoryIdUserAssociationMap);

            // 5- Execute Update
            updateSalesLeads(leadsToUpdate);
        }
        catch (Exception e)
        {
            DebugLog.addException(e, 'SuggestedOwnerManager.assignSuggestedOwners');
        }
    }

    /**
     * Retrieves Sales Leads Records that don't have an owner (Sales_Rep__c) populated
     * @author hadib@salesforce.com | 06-09-2023
     *
     * @param salesLeadsIds Sales Leads Ids
     *
     * @return List<Field_Sales_Project_Members__c> - Sales Leads Records
     */
    public static List<Field_Sales_Project_Members__c> getSalesLeadsRecords(List<String> salesLeadsIds)
    {
        List<Field_Sales_Project_Members__c> salesLeads = [
                SELECT Id, Account__c, Dealer__c, Sales_Rep__c, Category__c, Account__r.Country__c, Brand__c
                FROM Field_Sales_Project_Members__c
                WHERE Id IN :salesLeadsIds AND Sales_Rep__c = NULL
        ];
        return salesLeads;
    }

    /**
     * Determines the suggested owner for a single sales lead based on various criteria.
     * @author hadib@salesforce.com | 06-09-2023
     *
     * @param salesLeadToUpdate             The Sales Lead record for which the suggested owner is determined.
     * @param leadOpportunitySettingMap     A map of lead opportunity settings organized by Country and Category.
     * @param accountTerritoryMap           A map of accounts and their associated territories.
     * @param territoryIdUserAssociationMap A map of territory Ids and user associations by role.
     *
     * @return Id - The Id of the suggested owner User, or null if no suitable owner is found.
     */
    private static Id determineSuggestedOwner(  Field_Sales_Project_Members__c                      salesLeadToUpdate,
                                                Map<String, List<LeadOpportunitySetting__mdt>>      leadOpportunitySettingMap,
                                                Map<Id, List<Id>>                                   accountTerritoryMap,
                                                Map<Id, Map<String, UserTerritory2Association>>     territoryIdUserAssociationMap)
    {
        Id suggestedUserId = null;
        String key = salesLeadToUpdate.Account__r.Country__c + salesLeadToUpdate.Category__c; // First the Account country + Category
        if(!leadOpportunitySettingMap.containsKey(key)) return null;

        List<LeadOpportunitySetting__mdt> settingList = leadOpportunitySettingMap.get(key);
        for (LeadOpportunitySetting__mdt setting : settingList)
        {
            List<String> userRoleList = setting?.UserRoles__c.split(';');

            if (salesLeadToUpdate.Brand__c != null && setting.BrandsList__c.contains(salesLeadToUpdate.Brand__c)) // Brand is mandatory
            {
                Id accountId = (setting.AssignOwnerFrom__c == DEALER) ? salesLeadToUpdate.Dealer__c : salesLeadToUpdate.Account__c;

                if (accountId != null && accountTerritoryMap.containsKey(accountId))
                {
                    for (Id territoryId : accountTerritoryMap.get(accountId))
                    {
                        for (String userRole : userRoleList) // Search the account or dealer territories to get the right person based on role
                        {
                            suggestedUserId = territoryIdUserAssociationMap.get(territoryId)?.get(userRole.trim())?.UserId;
                            if (suggestedUserId != null) { break; }
                        }

                        if (suggestedUserId != null) { break; }
                    }
                }
            }

            if (suggestedUserId != null) {
                break;
            }
        }

        return suggestedUserId;
    }

    /**
     * Fetch Lead opportunity settings and arranges them into a map where the key is a combination of the Country__c and Category__c fields
     * @author hadib@salesforce.com | 06-09-2023
     *
     * @return Map<String, List<LeadOpportunitySetting__mdt>> - A map of lead opportunity settings key: (Country__c + Category__c) .
     */
    public static Map<String, List<LeadOpportunitySetting__mdt>> getLeadOpportunitySettings()
    {
        Map<String, List<LeadOpportunitySetting__mdt>> leadOpportunitySettingMap = new Map<String, List<LeadOpportunitySetting__mdt>>();

        for (LeadOpportunitySetting__mdt leadOpptySetting : LeadOpportunitySetting__mdt.getAll().values())
        {
            // 1-Skip setting if mandatory fields are empty
            if (String.isEmpty(leadOpptySetting.Country__c))    continue;
            if (String.isEmpty(leadOpptySetting.Category__c))   continue;
            if (String.isEmpty(leadOpptySetting.UserRoles__c))  continue;
            if (String.isEmpty(leadOpptySetting.BrandsList__c)) continue;

            // 2-Construct Map of settings with Country__c + Category__c as key (e.g. USImplants)
            String settingKeyString = leadOpptySetting.Country__c + leadOpptySetting.Category__c;
            if (leadOpportunitySettingMap.containsKey(settingKeyString)) {
                leadOpportunitySettingMap.get(settingKeyString).add(leadOpptySetting);
            } else {
                leadOpportunitySettingMap.put(settingKeyString, new List<LeadOpportunitySetting__mdt>{leadOpptySetting});
            }
        }
        return leadOpportunitySettingMap;
    }

    /**
     * Constructs a map of accounts and their associated territories.
     * @author hadib@salesforce.com | 06-09-2023
     *
     * @param accountIds    Set of Account Ids
     *
     * @return Map<Id,List<Id>> - A map where each Account Id leads to a list of associated territory Ids.
     */
    public static Map<Id,List<Id>> getAccountTerritoryMap(Set<Id> accountIds)
    {
        Map<Id,List<Id>> accountTerritoryMap = new Map<Id,List<Id>>();

        for (ObjectTerritory2Association association : [SELECT ObjectId, Territory2Id FROM ObjectTerritory2Association WHERE ObjectId IN :accountIds])
        {
            // Construct Map of accounts and territories where an accountId leads to a list of associated territories
            if (accountTerritoryMap.containsKey(association.ObjectId)) {
                accountTerritoryMap.get(association.ObjectId).add(association.Territory2Id);
            } else {
                accountTerritoryMap.put(association.ObjectId, new List<Id>{association.Territory2Id});
            }
        }
        return accountTerritoryMap;
    }

    /**
     * Fetch Account Territories based on the given Sales Leads
     * @author hadib@salesforce.com | 06-09-2023
     *
     * @param salesLeads Sales Leads records
     *
     * @return Map<Id, List<Id>> - Account Territories
     */
    public static Map<Id, List<Id>> getAccountTerritoryMap(List<Field_Sales_Project_Members__c> salesLeads)
    {
        Set<Id> accountIdSet = extractLeadAccountIds(salesLeads);
        Map<Id,List<Id>> accountTerritoryMap = getAccountTerritoryMap(accountIdSet);
        return accountTerritoryMap;
    }

    /**
     * Extracts a set of Account Ids associated with Sales Lead records.
     * @author hadib@salesforce.com | 06-09-2023
     *
     * @param salesLeads List of Sales Lead records.
     *
     * @return Set<Id> - A set of Account Ids linked to the provided Sales Lead records.
     */
    public static Set<Id> extractLeadAccountIds(List<Field_Sales_Project_Members__c> salesLeads)
    {
        Set<Id> accountIdSet = new Set<Id>();

        for (Field_Sales_Project_Members__c salesLead : salesLeads)
        {
            // Sets used to query the right AccountUserTerritory2View records
            accountIdSet.add(salesLead.Account__c);
            accountIdSet.add(salesLead.Dealer__c);
        }

        return accountIdSet;
    }

    /**
     * Fetch Territory to User Associations based on Account Territories
     * @author hadib@salesforce.com | 06-09-2023
     *
     * @param accountTerritoryMap aze
     *
     * @return aze
     */
    public static Map<Id, Map<String, UserTerritory2Association>> getTerritoryIdUserAssociationMap(Map<Id, List<Id>> accountTerritoryMap)
    {
        Set<Id> flattenedTerritoryIdSet = getFlattenedTerritoryIdSet(accountTerritoryMap);

        Map<Id, Map<String, UserTerritory2Association>> territoryIdUserAssociationMap = new Map<Id, Map<String, UserTerritory2Association>>();

        for (UserTerritory2Association userTerritoryAssociations : [ SELECT Id, Territory2Id, UserId, RoleInTerritory2
                                                                    FROM UserTerritory2Association
                                                                    WHERE Territory2Id IN :flattenedTerritoryIdSet ])
        {
            // Construct Map of territories and associated users based on RoleInTerritory2
            if (territoryIdUserAssociationMap.containsKey(userTerritoryAssociations.Territory2Id)) {
                territoryIdUserAssociationMap.get(userTerritoryAssociations.Territory2Id).put(userTerritoryAssociations.RoleInTerritory2, userTerritoryAssociations);
            } else {
                territoryIdUserAssociationMap.put(userTerritoryAssociations.Territory2Id, new Map<String, UserTerritory2Association>{userTerritoryAssociations.RoleInTerritory2 => userTerritoryAssociations});
            }
        }
        return territoryIdUserAssociationMap;
    }

    /**
     * Flatten the territory IDs for efficient processing.
     * @author hadib@salesforce.com | 06-09-2023
     *
     * @param listMap List of ids to flatten
     *
     * @return Set<Id> - Ids flattened
     */
    public static Set<Id> getFlattenedTerritoryIdSet(Map<Id,List<Id>> listMap)
    {
        Set<Id> flattenedIdsSet = new Set<Id>();
        for (List<Id> idList : listMap.values()) {
            flattenedIdsSet.addAll(idList);
        }
        return flattenedIdsSet;
    }

    /**
     * We find the sales lead that we can suggest their owner following the account country, category, brand and user role
     * @author hadib@salesforce.com | 06-09-2023
     *
     * @param salesLeads Sales Lead records to update their owner
     * @param leadOpportunitySettingMap Lead opportunity custom metadata
     * @param accountTerritoryMap Account Territories
     * @param territoryIdUserAssociationMap User Territories
     *
     * @return List<Field_Sales_Project_Members__c> - Sales leads updated with suggested owner
     */
    public static List<Field_Sales_Project_Members__c> detectSalesLeadsThatNeedsToBeUpdated(
            List<Field_Sales_Project_Members__c>                salesLeads,
            Map<String, List<LeadOpportunitySetting__mdt>>      leadOpportunitySettingMap,
            Map<Id, List<Id>>                                   accountTerritoryMap,
            Map<Id, Map<String, UserTerritory2Association>>     territoryIdUserAssociationMap)
    {
        List<Field_Sales_Project_Members__c> leadsToUpdate = new List<Field_Sales_Project_Members__c>();

        for (Field_Sales_Project_Members__c leadToUpdate : salesLeads) {
            Id previousSuggestedUserId = leadToUpdate.Sales_Rep__c;
            Id suggestedUserId = determineSuggestedOwner(leadToUpdate, leadOpportunitySettingMap, accountTerritoryMap, territoryIdUserAssociationMap);

            if (previousSuggestedUserId != suggestedUserId && suggestedUserId != null) {
                leadToUpdate.Sales_Rep__c = suggestedUserId;
                leadsToUpdate.add(leadToUpdate);
            }
        }

        return leadsToUpdate;
    }

    /**
     * Update the sales lead records with the new owners
     * @author hadib@salesforce.com | 06-09-2023
     *
     * @param leadsToUpdate Sales Leads to update
     */
    public static void updateSalesLeads(List<Field_Sales_Project_Members__c> leadsToUpdate)
    {
        if (!leadsToUpdate.isEmpty()) {
            update leadsToUpdate;
        }
    }
}