src/objects/Country__c.object
<CustomObject>
    <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Implants</fullName>
                    <label>Global DPG</label>
                </value>
                <value>
                    <fullName>All Ortho</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ATF</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
                <value>
                    <fullName>BHR</fullName>
                </value>
                <value>
                    <fullName>BHS</fullName>
                </value>
                <value>
                    <fullName>BIH</fullName>
                </value>
                <value>
                    <fullName>BLM</fullName>
                </value>
                <value>
                    <fullName>BLR</fullName>
                </value>
                <value>
                    <fullName>BLZ</fullName>
                </value>
                <value>
                    <fullName>BMU</fullName>
                </value>
                <value>
                    <fullName>BOL</fullName>
                </value>
                <value>
                    <fullName>BRA</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order</label>
        <type>Checkbox</type>
    </fields>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Non_ERP_Products__c.object
<CustomObject>
    <fields>
        <fullName>Competitor_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Competitor Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Countries__c</fullName>
        <label>Countries</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_Code_2_digit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GlobalProductShowtoallcountries__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this product will be shown to all countries regardless of the countries&apos; field selection.  
TFUS-000005477</description>
        <inlineHelpText>If checked, this product will be shown to all countries regardless of the countries&apos; field selection.</inlineHelpText>
        <label>Global Product (Show to all countries)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProductFamily__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Assocaites the non-ERP product to a product family. Used for the Workflow definitions and analysis</description>
        <label>Product Family</label>
        <referenceTo>ProductFamily__c</referenceTo>
        <relationshipLabel>Non-ERP Products</relationshipLabel>
        <relationshipName>Non_ERP_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Non-ERP Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non-ERP Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Profiling__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products Profiling</relationshipLabel>
        <relationshipName>Products_Profiling</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Competitor_Product__c</fullName>
        <formula>Product_Name__r.Competitor_Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Competitor Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Products that are no longer associated with the account (Obsolete, Lapsed Usage)</description>
        <inlineHelpText>Products that are no longer associated with the account (Obsolete, Lapsed Usage)</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Non-ERP Product</label>
        <referenceTo>Non_ERP_Products__c</referenceTo>
        <relationshipLabel>Products Profiling</relationshipLabel>
        <relationshipName>Products_Profiling</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Product Profiling</label>
    <nameField>
        <displayFormat>PP{000000000}</displayFormat>
        <label>Profiling Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Profiling</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProductFamily__c.object
<CustomObject>
    <description>Product Categories will be used to globally classify products (DS &amp; Competition) and simplify the way we can identify the procedures and workflows that are being used by our customers. 

TFUS-000005712</description>
    <label>Product Family</label>
    <nameField>
        <label>Product Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Workflow__c.object
<CustomObject>
    <fields>
        <fullName>Countries__c</fullName>
        <description>To which countries, this workflow should be excluded for account profiling.</description>
        <label>Countries</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_Code_2_digit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GlobalProductShowtoallcountries__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this product will be shown to all countries regardless of the countries&apos; field selection.
TFUS-000006035</description>
        <inlineHelpText>If checked, this product will be shown to all countries regardless of the countries&apos; field selection.</inlineHelpText>
        <label>Global Product (Show to all countries)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WorkflowLabel__c</fullName>
        <label>Workflow Label</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>workflows</valueSetName>
        </valueSet>
    </fields>
    <label>Workflow</label>
    <nameField>
        <label>Workflow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workflows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkflowLine__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductFamily__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Family</label>
        <referenceTo>ProductFamily__c</referenceTo>
        <relationshipLabel>Workflow Lines</relationshipLabel>
        <relationshipName>FamilyWorkflow_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Workflow__c</fullName>
        <label>Workflow</label>
        <referenceTo>Workflow__c</referenceTo>
        <relationshipLabel>Workflow Lines</relationshipLabel>
        <relationshipName>WorkflowLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workflow Line</label>
    <nameField>
        <label>Workflow Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workflow Linses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkflowProfiling__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Workflows Profiling</relationshipLabel>
        <relationshipName>Workflows_Profiling</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rating</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Workflow__c</fullName>
        <label>Workflow</label>
        <referenceTo>Workflow__c</referenceTo>
        <relationshipLabel>Workflows Profiling</relationshipLabel>
        <relationshipName>Workflows_Profiling</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workflow Profiling</label>
    <nameField>
        <displayFormat>WFP #{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workflows Profiling</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Country_Code_2_digit.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AN</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AQ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AS</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AX</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BF</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BJ</fullName>
    </customValue>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>CH</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <masterLabel>Country Code (2-digit)</masterLabel>
</GlobalValueSet>

src/globalValueSets/workflows.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Tooth Preservation - Indirect Restoration</fullName>
    </customValue>
    <customValue>
        <fullName>Tooth Preservation - Indirect Restoration - Scan to Lab</fullName>
    </customValue>
    <customValue>
        <fullName>Tooth Replacement - Implant</fullName>
    </customValue>
    <customValue>
        <fullName>Lab - Indirect Restoration</fullName>
    </customValue>
    <customValue>
        <fullName>Tooth Preservation - Endodontic</fullName>
    </customValue>
    <customValue>
        <fullName>Tooth Movement - Smile design</fullName>
    </customValue>
    <customValue>
        <fullName>Tooth Preservation - Direct Restoration</fullName>
    </customValue>
    <masterLabel>workflows</masterLabel>
</GlobalValueSet>

src/classes/WorkflowProfilingController.cls
/**
 * @Author          Omar (ohanafi@salesforce.com)
 * @Description     Workflow Profiling Controller Class.
 * @Test-Class      Test_WorkflowProfilingController
 *
 * @History
 * 21-05-2023   Omar     TFUS-000006676 - Excluding Germany, Austria and Switzerland from the global definition
 * 15-09-2023   Omar     TFUS-000006118 - Create Workflow Profiling Controller Class
 * 07-12-2023   Omar     Added the deleteWorkflowProfilings method
 */
public with sharing class WorkflowProfilingController {

    /**
     * getWorkflows Return a list of workflows based on the provided account Id
     * @author ohanafi@salesforce.com | 15-09-2023
     *
     * @param accountId   Account Id to fetch workflows
     *
     * @return List<Workflow__c> - List of workflows
     */
    @AuraEnabled(cacheable=true)
    public static List<Workflow__c> getWorkflows(Id accountId) {
        Account acc = [SELECT Id, Country__c from Account where id = :accountId LIMIT 1];

        if (acc != null) {
            String country = acc.Country__c;

            if (!new List<String>{'AT', 'DE', 'CH'}.contains(country)) {
                return [SELECT Id, WorkflowLabel__c FROM Workflow__c WHERE Countries__c INCLUDES (:country) OR GlobalProductShowtoallcountries__c = TRUE];
            } else {
                return [
                        SELECT Id, WorkflowLabel__c
                        FROM Workflow__c
                        WHERE ((GlobalProductShowtoallcountries__c = false AND Countries__c INCLUDES (:country)) OR (GlobalProductShowtoallcountries__c = true AND (Countries__c = null OR (NOT(Countries__c INCLUDES (:country))))))
                ];
            }
        }

        return null;
    }

    /**
     * getWorkflowProfilingsByAccount Return a list of Workflow Profiling records based on the provided account Id
     * @author ohanafi@salesforce.com | 15-09-2023
     *
     * @param accountId   Account Id to fetch Workflow Profilings
     *
     * @return List<WorkflowProfiling__c> - List of Workflow Profiling records
     */
    @AuraEnabled(cacheable=true)
    public static List<WorkflowProfiling__c> getWorkflowProfilingsByAccount(Id accountId) {
        return [SELECT Id, Name, Rating__c, Account__c, Inactive__c, Workflow__c FROM WorkflowProfiling__c WHERE Account__c = :accountId];
    }

    /**
     * createOrUpdateWorkflowProfilings Upsert or insert Workflow Profiling records based on the provided list of records
     * @author ohanafi@salesforce.com | 15-09-2023
     *
     * @param newRecords   List of Workflow Profiling records to upsert or insert
     */
    @AuraEnabled
    public static void createOrUpdateWorkflowProfilings(List<WorkflowProfiling__c> newRecords) {
        // Fetch existing records
        Map<Id, WorkflowProfiling__c> existingRecordsMap = new Map<Id, WorkflowProfiling__c>();

        if (!newRecords.isEmpty()) {

            Set<Id> accountIds = new Set<Id>();

            for (WorkflowProfiling__c eachWorkflowProfiling : newRecords) {
                accountIds.add(eachWorkflowProfiling.Account__c);
            }

            for (WorkflowProfiling__c existingRecord : [
                    SELECT Id, Workflow__c, Rating__c
                    FROM WorkflowProfiling__c
                    WHERE Account__c = :accountIds
            ]
            ) {
                existingRecordsMap.put(existingRecord.Workflow__c, existingRecord);
            }

            List<WorkflowProfiling__c> recordsToUpsert = new List<WorkflowProfiling__c>();

            // Iterate through new records
            for (WorkflowProfiling__c newRecord : newRecords) {
                // Check if there's a matching existing record
                WorkflowProfiling__c existingRecord = existingRecordsMap.get(newRecord.Workflow__c);

                if (existingRecord != null) {
                    // Update the existing record's rating
                    existingRecord.Rating__c = newRecord.Rating__c;
                    existingRecord.Inactive__c = newRecord.Inactive__c;
                    recordsToUpsert.add(existingRecord);
                } else {
                    // No matching record found, insert a new record
                    recordsToUpsert.add(newRecord);
                }
            }

            // Perform the upsert operation to either insert or update records
            if (!recordsToUpsert.isEmpty()) {
                upsert recordsToUpsert;
            }
        }

    }

    /**
     * getProductFamilyListByWorkflowId Get a list of ProductFamily__c records and its associated Non_ERP_Products__c
     * @author ohanafi@salesforce.com | 22-12-2023
     *
     * @param workflowId   Workflow ID
     * @param accountId   Account ID
     *
     * @return List<ProductFamilyWrapper> - List of ProductFamily__c records
     */
    @AuraEnabled
    public static List<ProductFamilyWrapper> getProductFamilyListByWorkflowId(Id workflowId, Id accountId) {
        List<ProductFamilyWrapper> productFamilyWrapperList = new List<ProductFamilyWrapper>();

        Account acc = [SELECT Id, Country__c from Account where id = :accountId LIMIT 1];

        String country = '';

        if (acc != null) {
            country = acc.Country__c;
        }

        List<ProductFamily__c> productFamilyList = new List<ProductFamily__c>();

        if (!new List<String>{'AT', 'DE', 'CH'}.contains(country)) {
            productFamilyList = [
                    SELECT Id, ProductFamilyLabel__c, (
                            SELECT Id, Name, Competitor_Product__c
                            FROM Non_ERP_Products__r
                            WHERE GlobalProductShowtoallcountries__c = true OR Countries__c INCLUDES (:country)
                    )
                    FROM ProductFamily__c
                    WHERE Id IN (
                            SELECT ProductFamily__c
                            FROM WorkflowLine__c
                            WHERE Workflow__c = :workflowId
                    )
            ];        } else {
            productFamilyList = [
                    SELECT Id, ProductFamilyLabel__c, (
                            SELECT Id, Name, Competitor_Product__c
                            FROM Non_ERP_Products__r
                            WHERE ((GlobalProductShowtoallcountries__c = false AND Countries__c INCLUDES (:country)) OR (GlobalProductShowtoallcountries__c = true AND (Countries__c = null OR (NOT(Countries__c INCLUDES (:country))))))
                    )
                    FROM ProductFamily__c
                    WHERE Id IN (
                            SELECT ProductFamily__c
                            FROM WorkflowLine__c
                            WHERE Workflow__c = :workflowId
                    )
            ];
        }



        // Collect Non_ERP_Products__c Ids
        Set<String> nonERPProductIds = new Set<String>();
        for (ProductFamily__c productFamily : productFamilyList) {
            for (Non_ERP_Products__c nonERPProduct : productFamily.Non_ERP_Products__r) {
                nonERPProductIds.add(nonERPProduct.Id);
            }
        }

        // Map to hold active ProductProfiling__c Ids related to Non_ERP_Products__c
        Map<Id, Id> activeNonErpProductsIds = new Map<Id, Id>();

        // Map to hold inactive ProductProfiling__c Ids related to Non_ERP_Products__c
        Map<Id, Id> inactiveNonErpProductsIds = new Map<Id, Id>();

        for (Product_Profiling__c productProfiling : [
                SELECT Id, Product_Name__c, Inactive__c
                FROM Product_Profiling__c
                WHERE Product_Name__c IN :nonERPProductIds AND Account__c = :accountId
        ]) {
            if(!productProfiling.Inactive__c){
                activeNonErpProductsIds.put(productProfiling.Product_Name__c, productProfiling.Id);
            } else {
                inactiveNonErpProductsIds.put(productProfiling.Product_Name__c, productProfiling.Id);
            }
        }

        // Get the order values for each ProductFamily__c in a map
        Map<Id, Integer> familyOrderMap = new Map<Id, Integer>();
        for (WorkflowLine__c line : [SELECT ProductFamily__c, Order__c FROM WorkflowLine__c WHERE Workflow__c = :workflowId]) {
            familyOrderMap.put(line.ProductFamily__c, (Integer) line.Order__c);
        }

        // Populate ProductFamilyWrapperList
        for (ProductFamily__c productFamily : productFamilyList) {
            ProductFamilyWrapper wrapper = new ProductFamilyWrapper(familyOrderMap, productFamily);

            for (Non_ERP_Products__c nonERPProduct : productFamily.Non_ERP_Products__r) {
                if (nonERPProduct.Competitor_Product__c) {
                    Boolean isActive = activeNonErpProductsIds.containsKey(nonERPProduct.Id);
                    Boolean isInactive = inactiveNonErpProductsIds.containsKey(nonERPProduct.Id);
                    wrapper.competitorProducts.add(new NonERPProductWrapper(nonERPProduct, isActive, isInactive, isActive ? activeNonErpProductsIds.get(nonERPProduct.Id) : (isInactive ? inactiveNonErpProductsIds.get(nonERPProduct.Id) : null)));
                } else {
                    Boolean isActive = activeNonErpProductsIds.containsKey(nonERPProduct.Id);
                    Boolean isInactive = inactiveNonErpProductsIds.containsKey(nonERPProduct.Id);
                    wrapper.dsProducts.add(new NonERPProductWrapper(nonERPProduct, isActive, isInactive, isActive ? activeNonErpProductsIds.get(nonERPProduct.Id) : (isInactive ? inactiveNonErpProductsIds.get(nonERPProduct.Id) : null)));
                }
            }

            // Sorting the Non ERP Products alphabetically (asc)
            wrapper.dsProducts.sort();
            wrapper.competitorProducts.sort();

            productFamilyWrapperList.add(wrapper);
        }

        // Sorting Product Families based on the Workflow Lines order
        productFamilyWrapperList.sort();

        return productFamilyWrapperList;

    }

    public class NonERPProductWrapper implements Comparable {
        @AuraEnabled public Non_ERP_Products__c product;
        @AuraEnabled public Boolean active;
        @AuraEnabled public Boolean inactive;
        @AuraEnabled public String productProfilingId;

        public NonERPProductWrapper(Non_ERP_Products__c product, Boolean active, Boolean inactive, String productProfilingId) {
            this.product = product;
            this.active = active;
            this.inactive = inactive;
            this.productProfilingId = productProfilingId;
        }

        public Integer compareTo(Object other) {
            NonERPProductWrapper otherWrapper = (NonERPProductWrapper) other;
            return this.product.Name.compareTo(otherWrapper.product.Name);
        }
    }

    public class ProductFamilyWrapper implements Comparable {
        @AuraEnabled public ProductFamily__c productFamily;
        @AuraEnabled public List<NonERPProductWrapper> competitorProducts;
        @AuraEnabled public List<NonERPProductWrapper> dsProducts;
        private Map<Id, Integer> orderMap; // Map to hold the order

        public ProductFamilyWrapper(Map<Id, Integer> orderMap, ProductFamily__c productFamily) {
            this.competitorProducts = new List<NonERPProductWrapper>();
            this.dsProducts = new List<NonERPProductWrapper>();
            this.orderMap = orderMap;
            this.productFamily = productFamily;
        }

        public ProductFamilyWrapper() {
            this.competitorProducts = new List<NonERPProductWrapper>();
            this.dsProducts = new List<NonERPProductWrapper>();
        }

        // Method to sort Product Families based on the order retrieved from the Workflow Lines
        public Integer compareTo(Object other) {
            Integer thisOrder = orderMap.containsKey(this.productFamily.Id) ? orderMap.get(this.productFamily.Id) : 99999999;
            Integer otherOrder = orderMap.containsKey(((ProductFamilyWrapper)other).productFamily.Id) ? orderMap.get(((ProductFamilyWrapper)other).productFamily.Id) : 99999999;
            if (thisOrder == otherOrder) return 0;
            if (thisOrder > otherOrder) return 1;
            return -1;
        }

    }
}