src/objects/Country__c.object
<CustomObject>
    <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Implants</fullName>
                    <label>Global DPG</label>
                </value>
                <value>
                    <fullName>All Ortho</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ATF</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
                <value>
                    <fullName>BHR</fullName>
                </value>
                <value>
                    <fullName>BHS</fullName>
                </value>
                <value>
                    <fullName>BIH</fullName>
                </value>
                <value>
                    <fullName>BLM</fullName>
                </value>
                <value>
                    <fullName>BLR</fullName>
                </value>
                <value>
                    <fullName>BLZ</fullName>
                </value>
                <value>
                    <fullName>BMU</fullName>
                </value>
                <value>
                    <fullName>BOL</fullName>
                </value>
                <value>
                    <fullName>BRA</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MarginGuidance__c.object
<CustomObject>
    <description>TFUS-000005243
A Margin guidance record defines the different layers of margin thresholds per combination of product and Territory area.</description>
    <fields>
        <fullName>AreaCode__c</fullName>
        <description>Should be equaled to Account DC_ETM_Code__c (First 3 characters)</description>
        <inlineHelpText>Area Code to be matched with the account&apos;s territory area code available on the account&apos;s ETM Code (First 3 characters)</inlineHelpText>
        <label>Area Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LowerGuidance__c</fullName>
        <label>Lower Guidance</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Margin Guidances</relationshipLabel>
        <relationshipName>Margin_Guidances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UpperGuidance__c</fullName>
        <label>Upper Guidance</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Margin Guidance</label>
    <nameField>
        <displayFormat>MG#{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Margin Guidances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LowerGuidance__c</fullName>
        <description>#5314 - Margin Guidance Calculation Process</description>
        <label>Lower Guidance (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MarginGuidance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Margin Guidance</label>
        <referenceTo>MarginGuidance__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <description>#5314 - Margin Guidance Calculation Process</description>
        <label>Margin</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SalesPrice__c</fullName>
        <description>Shows the sales price of the line item (each) - the discounted price</description>
        <formula>UnitPrice * (1- Discount_Percent__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Shows the sales price of the line item (each) - the discounted price</inlineHelpText>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalCost__c</fullName>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UpperGuidance__c</fullName>
        <description>#5314 - Margin Guidance Calculation Process</description>
        <label>Upper Guidance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <description>#5314 - Margin Guidance Calculation Process</description>
        <label>Weight</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WeightedLowerGuidance__c</fullName>
        <description>#5314 - Margin Guidance Calculation Process</description>
        <label>Weighted Lower Guidance</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WeightedUpperGuidance__c</fullName>
        <description>#5314 - Margin Guidance Calculation Process</description>
        <label>Weighted Upper Guidance</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>MarginGuidanceCalculation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TFUS-000005314
If checked, it will enable the calculation of margin guidance upon submitting an order for approval.</description>
        <inlineHelpText>if checked, it will enable the calculation of margin guidance upon submitting an order for approval.</inlineHelpText>
        <label>Margin Guidance Calculation ?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AssignMarginGuidanceHelper.cls
/**
 * @Author          Omar (ohanafi@salesforce.com)
 * @Description     Helper class to calculate margins and update order items.
 * @Test-Class      Test_AssignMarginGuidanceHelper
 *
 * @History
 * 15-02-2023   Omar     Created AssignMarginGuidanceHelper class
 * 17-04-2023   Omar     TFUS-000005556 - Added new logic for Canada (using the region code instead of area code)
 */

public with sharing class AssignMarginGuidanceHelper {

    // Custom exception for error handling
    private class AssignMarginGuidanceCustomException extends Exception {}

    /**
         * calculateMargin      Calculate margins and update order items based on a given order.
         * @author ohanafi@salesforce.com | 15-02-2023
         *
         * @param orderId - The ID of the order to calculate margins for.
         *
         */
    public static void calculateMargin(Id orderId) {
        // Get the order and its related line items
        system.debug('k0');
        Order order = [
                SELECT Id, Account.DC_ETM_Code__c, Account.Country__c, AccountId, Pricebook2.MarginGuidanceCalculation__c, (SELECT Id, Product2Id, Quantity, ListPrice, TotalPrice, SalesPrice__c, MarginGuidance__c, PricebookEntry.FloorPrice__c FROM OrderItems)
                FROM Order
                WHERE Id = :orderId
        ];

        if (!order?.Pricebook2?.MarginGuidanceCalculation__c && !order?.OrderItems.isEmpty()) {
            system.debug('k1');
            // SKIP if Pricebook2.MarginGuidanceCalculation__c = false or no order items
            return;
        }

        // Init the area code / product id set
        String areaRegionCode;
        Set<Id> productIdSet = new Set<Id>();

        // If the account's country is Canada, We look for the region code through territory management
        if(order?.Account?.Country__c == 'CA'){
            areaRegionCode = getRegionCodeFromOrder(order);
        } else { // Otherwise we get the area code directly from the etm code of the account
            areaRegionCode = order?.Account?.DC_ETM_Code__c != null ? order?.Account?.DC_ETM_Code__c.substring(0, 3) : '';
        }

        // Generating the area code / product id sets
        for (OrderItem eachOrderItem : order.OrderItems) {
            productIdSet.add(eachOrderItem.Product2Id);
        }

        // Getting the global margin guidance list
        List<MarginGuidance__c> marginGuidanceList = [
                SELECT Id, AreaCode__c, Product__c, Cost__c, Lowerguidance__c, UpperGuidance__c
                FROM MarginGuidance__c
                WHERE AreaCode__c = :areaRegionCode
                OR AreaCode__c = 'All'
                OR Product__c IN :productIdSet
        ];

        // Generating the Order Item / Margin Guidance Map
        Map<OrderItem, MarginGuidance__c> orderItemMarginGuidanceMap = generateOrderItemMarginGuidanceMap(areaRegionCode, order, marginGuidanceList);

        // Calculate the total price sum
        Decimal totalPriceSum = 0;
        for (OrderItem eachOrderItem : orderItemMarginGuidanceMap.keySet()) {
            totalPriceSum += eachOrderItem.TotalPrice;
        }

        // Calculating margins for the order items
        if(totalPriceSum > 0){
            updateOrderItems(orderItemMarginGuidanceMap, totalPriceSum);
        }

        // Update list of order items
        try {
            update new List<OrderItem>(orderItemMarginGuidanceMap.keySet());
        } catch (Exception e){
            DebugLog.addException(e, e.getMessage());
            throw new AssignMarginGuidanceCustomException(e.getMessage());
        }

    }

    /**
         * getRegionCodeFromOrder     Get the region code from an order based on ETM (For Canada orders).
         * @author ohanafi@salesforce.com | 17-04-2023
         *
         * @param
         *                  order - The Order record to generate the map for.
         *
         * @return          The region code
         *
         */
    private static String getRegionCodeFromOrder(Order order) {
        // Getting a list of all territories related to the account id
        List<ObjectTerritory2Association> objectTerritoryAssociations = [
                SELECT Territory2Id
                FROM ObjectTerritory2Association
                WHERE ObjectId = :order.AccountId
        ];

        Set<Id> territoryIdSet = new Set<Id>();

        for (ObjectTerritory2Association eachAssociation : objectTerritoryAssociations) {
            territoryIdSet.add(eachAssociation.Territory2Id);
        }

        // We get a list of all users based on the list of territories and the role Sales Rep (Impl)
        List<UserTerritory2Association> usersInTerritoryList = [
                SELECT Territory2.Name
                FROM UserTerritory2Association
                WHERE Territory2Id IN :territoryIdSet AND RoleInTerritory2 = 'Sales Rep (IMPL)'
        ];

        if (!usersInTerritoryList.isEmpty()) {
            String territoryName = usersInTerritoryList[0].Territory2.Name;

            // Find the index of the region code's starting position
            Integer start = !String.isEmpty(territoryName) ? territoryName.indexOf('RBM') : -1;

            if (start != -1) {
                // Extract the region code
                return territoryName.substring(start, start + 5);
            }
        }

        return null;
    }

    /**
         * updateOrderItems     Update order items with MarginGuidance fields.
         * @author ohanafi@salesforce.com | 17-02-2023
         *
         * @param           orderItemMarginGuidanceMap - A map of OrderItem records and their associated MarginGuidance__c records.
         *                  totalPriceSum - The sum of the TotalPrice fields of all OrderItem records.
         *
         */
    private static void updateOrderItems(Map<OrderItem, MarginGuidance__c> orderItemMarginGuidanceMap, Decimal totalPriceSum) {
        // Loop through each order line item
        for (OrderItem eachOrderItem : orderItemMarginGuidanceMap.keySet()) {
            // Get the margin guidance associated to the order item record
            MarginGuidance__c eachMarginGuidance = orderItemMarginGuidanceMap.get(eachOrderItem);

            // Update the order item fields
            eachOrderItem.Weight__c = eachOrderItem.ListPrice * eachOrderItem.Quantity / totalPriceSum;
//            eachOrderItem.Margin__c = (eachOrderItem.ListPrice - eachMarginGuidance.Cost__c) / eachOrderItem.ListPrice;
//            eachOrderItem.Margin__c = (eachOrderItem.TotalPrice - (eachMarginGuidance.Cost__c * eachOrderItem.Quantity)) / eachOrderItem.TotalPrice;
            eachOrderItem.Margin__c = (eachOrderItem.SalesPrice__c > 0) ? (eachOrderItem.SalesPrice__c - eachMarginGuidance.Cost__c) / eachOrderItem.SalesPrice__c :
                    -1 * (eachOrderItem.ListPrice - eachMarginGuidance.Cost__c) / eachOrderItem.ListPrice;
//            eachOrderItem.WeightedMargin__c = eachOrderItem.Margin__c * eachOrderItem.Weight__c;
            eachOrderItem.UpperGuidance__c = eachMarginGuidance.UpperGuidance__c;
            eachOrderItem.LowerGuidance__c = eachMarginGuidance.LowerGuidance__c;

            eachOrderItem.WeightedUpperGuidance__c = ((eachMarginGuidance.UpperGuidance__c / 100) * eachOrderItem.Weight__c);
            eachOrderItem.WeightedLowerGuidance__c = ((eachMarginGuidance.LowerGuidance__c / 100) * eachOrderItem.Weight__c);

            eachOrderItem.TotalCost__c = eachMarginGuidance.Cost__c * eachOrderItem.Quantity;
            eachOrderItem.Cost__c = eachMarginGuidance.Cost__c;
            /*if(! String.isBlank(String.Valueof(eachOrderItem.PricebookEntry.FloorPrice__c))){
            	eachOrderItem.TotalFloorPrice__c = eachOrderItem.PricebookEntry.FloorPrice__c * eachOrderItem.Quantity;
            	eachOrderItem.FloorPrice__c = eachOrderItem.PricebookEntry.FloorPrice__c;
            	eachOrderItem.TotalFloorPriceDeviation__c = (eachOrderItem.SalesPrice__c - eachOrderItem.PricebookEntry.FloorPrice__c) * eachOrderItem.Quantity;
            }*/

            // Associate margin guidance to the order item
            eachOrderItem.MarginGuidance__c = eachMarginGuidance.Id;
        }
    }

    /**
         * generateOrderItemMarginGuidanceMap     Generate a map of OrderItem records and their associated MarginGuidance__c records based on a given order and a list of MarginGuidance__c records.
         * @author ohanafi@salesforce.com | 16-02-2023
         *
         * @param
         *                  areaRegionCode - Area or Region code of the order's account.
         *                  order - The Order record to generate the map for.
         *                  marginGuidanceList - A list of MarginGuidance__c records to use for mapping.
         *
         * @return          A map of OrderItem records and their associated MarginGuidance__c records.
         *
         */
    private static Map<OrderItem, MarginGuidance__c> generateOrderItemMarginGuidanceMap(String areaRegionCode, Order order, List<MarginGuidance__c> marginGuidanceList) {
        // Init Order Item / Margin Guidance Map
        Map<OrderItem, MarginGuidance__c> orderItemMarginGuidanceMap = new Map<OrderItem, MarginGuidance__c>();

        for (OrderItem eachOrderItem : order.OrderItems) {
            Id itemProductId = eachOrderItem.Product2Id;

            for (MarginGuidance__c eachMarginGuidance : marginGuidanceList) {
                // We check if there's a margin guidance record with both matching area code and product id
                if (eachMarginGuidance.AreaCode__c == areaRegionCode && eachMarginGuidance.Product__c == itemProductId) {
                    orderItemMarginGuidanceMap.put(eachOrderItem, eachMarginGuidance);
                    break;

                    // Else we only check for the product id
                } else if (eachMarginGuidance.Product__c == itemProductId && eachMarginGuidance.AreaCode__c == 'All') {
                    orderItemMarginGuidanceMap.put(eachOrderItem, eachMarginGuidance);
                }
            }
        }

        return orderItemMarginGuidanceMap;
    }

}