src/objects/Country__c.object
<CustomObject>
    <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Implants</fullName>
                    <label>Global DPG</label>
                </value>
                <value>
                    <fullName>All Ortho</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ATF</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
                <value>
                    <fullName>BHR</fullName>
                </value>
                <value>
                    <fullName>BHS</fullName>
                </value>
                <value>
                    <fullName>BIH</fullName>
                </value>
                <value>
                    <fullName>BLM</fullName>
                </value>
                <value>
                    <fullName>BLR</fullName>
                </value>
                <value>
                    <fullName>BLZ</fullName>
                </value>
                <value>
                    <fullName>BMU</fullName>
                </value>
                <value>
                    <fullName>BOL</fullName>
                </value>
                <value>
                    <fullName>BRA</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GuidanceRenderer__mdt.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AD</fullName>
                    <default>true</default>
                    <label>AD</label>
                </value>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AF</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>AI</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>AN</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>AQ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AT</fullName>
                </value>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>AW</fullName>
                </value>
                <value>
                    <fullName>AX</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>BB</fullName>
                </value>
                <value>
                    <fullName>BD</fullName>
                </value>
                <value>
                    <fullName>BE</fullName>
                </value>
                <value>
                    <fullName>BF</fullName>
                </value>
                <value>
                    <fullName>BG</fullName>
                </value>
                <value>
                    <fullName>BH</fullName>
                </value>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BJ</fullName>
                </value>
                <value>
                    <fullName>BL</fullName>
                </value>
                <value>
                    <fullName>BM</fullName>
                </value>
                <value>
                    <fullName>BN</fullName>
                </value>
                <value>
                    <fullName>BO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Guidance_Content__c</fullName>
        <label>Guidance Content</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NextActivity__c</fullName>
        <label>NextActivity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Obtain Credit Card Information</fullName>
                    <default>true</default>
                    <label>Obtain Credit Card Information</label>
                </value>
                <value>
                    <fullName>Discovery, Goal Assessment</fullName>
                </value>
                <value>
                    <fullName>Case Selection &amp; Staff Roles</fullName>
                </value>
                <value>
                    <fullName>Records Training &amp; Finance</fullName>
                </value>
                <value>
                    <fullName>1st Case Submission,Workflow &amp; Mkt</fullName>
                </value>
                <value>
                    <fullName>1st Case Review/Approval</fullName>
                </value>
                <value>
                    <fullName>Team Training Ortho Benefits RDH</fullName>
                </value>
                <value>
                    <fullName>2nd Case Submission - External</fullName>
                </value>
                <value>
                    <fullName>2nd Case Review/Approval</fullName>
                </value>
                <value>
                    <fullName>3rd Case Submission</fullName>
                </value>
                <value>
                    <fullName>Team Meeting - Review Processes</fullName>
                </value>
                <value>
                    <fullName>3rd Case Review/Approval</fullName>
                </value>
                <value>
                    <fullName>Procedural Assessment</fullName>
                </value>
                <value>
                    <fullName>Reset Training</fullName>
                </value>
                <value>
                    <fullName>Who is your ideal aligner patient?</fullName>
                </value>
                <value>
                    <fullName>Clinical Education</fullName>
                </value>
                <value>
                    <fullName>Procedural Economics</fullName>
                </value>
                <value>
                    <fullName>Chairside Patient Education</fullName>
                </value>
                <value>
                    <fullName>Marketing Campaign</fullName>
                </value>
                <value>
                    <fullName>QBR (Low to Medium)</fullName>
                </value>
                <value>
                    <fullName>Business Assessment</fullName>
                </value>
                <value>
                    <fullName>Process Assessment</fullName>
                </value>
                <value>
                    <fullName>Patient Education</fullName>
                </value>
                <value>
                    <fullName>Economics</fullName>
                </value>
                <value>
                    <fullName>QBR (Medium to High L1)</fullName>
                </value>
                <value>
                    <fullName>Patient Acceptance</fullName>
                </value>
                <value>
                    <fullName>Clinical Development</fullName>
                </value>
                <value>
                    <fullName>Team Calibration</fullName>
                </value>
                <value>
                    <fullName>Marketing (M 2 H)</fullName>
                </value>
                <value>
                    <fullName>Peer 2 Peer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RecordTypeDeveloperName__c</fullName>
        <label>Record Type Developer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isTest__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isTest</label>
        <type>Checkbox</type>
    </fields>
    <label>GuidanceProcedureTracking</label>
    <pluralLabel>GuidancesProcedureTracker</pluralLabel>
</CustomObject>

src/objects/ProcedureTracker__c.object
<CustomObject>
    <description>Follow Up your Sales Lifecycle with step-by-step guided instructions. 
#1 Procedure Type: Clear Aligners - suresmile</description>
    <fields>
        <fullName>NextActivity__c</fullName>
        <formula>IF(NOT(ObtainCreditCardInformation__c), &quot;Obtain Credit Card Information&quot;, 
IF(NOT(DiscoveryGoalAssessment__c), &quot;Discovery, Goal Assessment&quot;, 
IF(NOT(CaseSelectionStaffRoles__c), &quot;Case Selection &amp; Staff Roles&quot;,
IF(NOT(RecordsTrainingFinance__c), &quot;Records Training &amp; Finance&quot;,
IF(NOT(X1stCaseSubmissionWorkflowMarketing__c), &quot;1st Case Submission,Workflow &amp; Mkt&quot;,
IF(NOT(X1stcasereviewapproval__c),&quot;1st Case Review/Approval&quot;,
IF(NOT(TeamTrainingOrthodonticBenefitsRDH__c), &quot;Team Training Ortho Benefits RDH&quot;,
IF(NOT(X2ndCaseSubmissionExternal__c), &quot;2nd Case Submission - External&quot;,
IF(NOT(X2ndCaseReviewApproval__c), &quot;2nd Case Review/Approval&quot;,
IF(NOT(X3rdcasesubmission__c), &quot;3rd Case Submission&quot;,
IF(NOT(TeamMeetingReviewProcesses__c),&quot;Team Meeting - Review Processes&quot;,
IF(NOT(X3rdCaseReviewApproval__c),&quot;3rd Case Review/Approval&quot;,
IF(NOT(ProceduralAssessment__c),&quot;Procedural Assessment&quot;,
IF(NOT(ResetTraining__c),&quot;Reset Training&quot;,
IF(NOT(Whoisyouridealalignerpatient__c),&quot;Who is your ideal aligner patient?&quot;,
IF(NOT(ClinicalEducation__c),&quot;Clinical Education&quot;,
IF(NOT(ProceduralEconomics__c),&quot;Procedural Economics&quot;,
IF(NOT(ChairsidePatientEducation__c),&quot;Chairside Patient Education&quot;,
IF(NOT(MarketingCampaign__c),&quot;Marketing Campaign&quot;,
IF(NOT(QBRLowtoMedium__c),&quot;QBR (Low to Medium)&quot;,
IF(NOT(BusinessAssessment__c),&quot;Business Assessment&quot;,
IF(NOT(ProcessAssessment__c),&quot;Process Assessment&quot;,
IF(NOT(PatientEducation__c),&quot;Patient Education&quot;,
IF(NOT(Economics__c),&quot;Economics&quot;,
IF(NOT(QBRMediumtoHighL1__c),&quot;QBR (Medium to High L1)&quot;,
IF(NOT(PatientAcceptance__c),&quot;Patient Acceptance&quot;,
IF(NOT(ClinicalDevelopment__c),&quot;Clinical Development&quot;,
IF(NOT(TeamCalibration__c),&quot;Team Calibration&quot;,
IF(NOT(MarketingM2H__c),&quot;Marketing (M 2 H)&quot;,
IF(NOT(Peer2Peer__c),&quot;Peer 2 Peer&quot;,
IF(NOT(QBRHighL1toHighL2__c),&quot;QBR (High L1 to High L2)&quot;,
&quot;&quot;)))))))))))))))))))))))))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Next Activity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PracticeAccount__c</fullName>
        <label>Practice Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Procedures</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Procedure Tracker</label>
    <nameField>
        <displayFormat>Track#{000}</displayFormat>
        <label>Record Nr</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Procedure Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GuidanceRendererController.cls
    public without sharing class GuidanceRendererController {
        @AuraEnabled
        public static string getGuidanceDetails(String parentId, String nextActivity){
            try {
                String guidance;
                ProcedureTracker__c currentProcedure = [Select Id, PracticeAccount__r.Country__c,NextActivity__c,RecordTypeId from ProcedureTracker__c Where Id =: parentId Limit 1];
                RecordType currentRecordType = [SELECT DeveloperName
                                            FROM RecordType
                                            WHERE SObjectType = 'ProcedureTracker__c' AND Id =: currentProcedure.RecordTypeId LIMIT 1];

                if(currentProcedure != null){
                    //get meta data with the next activity
                    List<GuidanceRenderer__mdt> guidances;

                    if(Test.IsRunningTest()){
                        guidances =  [
                                Select Id,Country__c, Guidance_Content__c, NextActivity__c
                                From GuidanceRenderer__mdt
                                Where  isTest__c = true
                        ];
                    } else {
                        guidances =  [
                                Select Id,Country__c, Guidance_Content__c, NextActivity__c
                                From GuidanceRenderer__mdt
                                Where  NextActivity__c=:nextActivity
                                AND RecordTypeDeveloperName__c =: currentRecordType.DeveloperName
                        ];
                    }

                    for(GuidanceRenderer__mdt eachGuidance : guidances){
                        if(String.isNotBlank(eachGuidance.Country__c)){
                            // We get the list of countries associated to the custom metadata, which is a semicolon seperated list
                            List<String> countryList = eachGuidance.Country__c.split(';');
                            if(!countryList.isEmpty()){
                                // We check if the practice account's country is included in the countries list
                                if(countryList.contains(currentProcedure.PracticeAccount__r.Country__c)){
                                    guidance = eachGuidance.Guidance_Content__c;
                                    break;
                                }
                            }
                        }
                    }

                }

                return guidance;

            } catch (Exception e) {
                throw new AuraHandledException(e.getMessage());
            }
        }
    }