src/objects/Country__c.object
<CustomObject>
    <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Implants</fullName>
                    <label>Global DPG</label>
                </value>
                <value>
                    <fullName>All Ortho</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ATF</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
                <value>
                    <fullName>BHR</fullName>
                </value>
                <value>
                    <fullName>BHS</fullName>
                </value>
                <value>
                    <fullName>BIH</fullName>
                </value>
                <value>
                    <fullName>BLM</fullName>
                </value>
                <value>
                    <fullName>BLR</fullName>
                </value>
                <value>
                    <fullName>BLZ</fullName>
                </value>
                <value>
                    <fullName>BMU</fullName>
                </value>
                <value>
                    <fullName>BOL</fullName>
                </value>
                <value>
                    <fullName>BRA</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>GET</fullName>
        <active>true</active>
        <businessProcess>GET</businessProcess>
        <label>X DO NOT USE 2t</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sets the manager of the Owner - used for Approval Processes</description>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SelectQuoteTemplate__c</fullName>
        <label>Select Quote Template</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>UserCountry__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Fiyat Teklifi</fullName>
                </value>
                <value>
                    <fullName>Fiyat Teklifi no VAT</fullName>
                </value>
                <value>
                    <fullName>Fiyat Teklifi Short</fullName>
                </value>
                <value>
                    <fullName>Proforma Kurumsal</fullName>
                </value>
                <value>
                    <fullName>Proforma Kurumsal no VAT</fullName>
                </value>
                <value>
                    <fullName>Quote Template: Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Quote Template: Andorra</label>
                </value>
                <value>
                    <fullName>Quote Template: Austria</fullName>
                </value>
                <value>
                    <fullName>Quote Template: Belgium</fullName>
                    <isActive>false</isActive>
                    <label>Quote Template: Belgium</label>
                </value>
                <value>
                    <fullName>Quote Template: Belgium (Dutch)</fullName>
                    <isActive>false</isActive>
                    <label>Quote Template: Belgium (Dutch)</label>
                </value>
                <value>
                    <fullName>Quote Template: Belgium (FR)</fullName>
                </value>
                <value>
                    <fullName>Quote Template: Belgium (French)</fullName>
                    <isActive>false</isActive>
                    <label>Quote Template: Belgium (French)</label>
                </value>
                <value>
                    <fullName>Quote Template: Belgium (NL)</fullName>
                </value>
                <value>
                    <fullName>Quote Template: España</fullName>
                </value>
                <value>
                    <fullName>Quote Template: España DSO</fullName>
                    <isActive>false</isActive>
                    <label>Quote Template: España DSO</label>
                </value>
                <value>
                    <fullName>Quote Template: España PrimeSolution</fullName>
                </value>
                <value>
                    <fullName>Quote Template: France</fullName>
                </value>
                <value>
                    <fullName>Quote Template: Germany</fullName>
                </value>
                <value>
                    <fullName>Quote Template: Luxembourg</fullName>
                </value>
                <value>
                    <fullName>Quote Template: Netherlands</fullName>
                </value>
                <value>
                    <fullName>Quote Template: Netherlands/Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Quote Template: Netherlands/Luxembourg</label>
                </value>
                <value>
                    <fullName>Quote Template: Portugal</fullName>
                </value>
                <value>
                    <fullName>Quote Template: Portugal DSO</fullName>
                    <isActive>false</isActive>
                    <label>Quote Template: Portugal DSO</label>
                </value>
                <value>
                    <fullName>Quote Template: UK</fullName>
                </value>
                <value>
                    <fullName>sözleşme</fullName>
                    <isActive>false</isActive>
                    <label>sözleşme</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X2nd_level_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sets the second level manager (Managers Manager) - used for Approval processes</description>
        <label>2nd level Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteCountrySetting__mdt.object
<CustomObject>
    <description>Stores the quotes configuration based on the country</description>
    <fields>
        <fullName>CountryCode__c</fullName>
        <description>The quote&apos;s Account country code.</description>
        <inlineHelpText>The quote&apos;s Account country code.</inlineHelpText>
        <label>Country Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AD</fullName>
                    <default>true</default>
                    <label>AD</label>
                </value>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AF</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>AI</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>AN</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>AQ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AT</fullName>
                </value>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>AW</fullName>
                </value>
                <value>
                    <fullName>AX</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>BB</fullName>
                </value>
                <value>
                    <fullName>BD</fullName>
                </value>
                <value>
                    <fullName>BE</fullName>
                </value>
                <value>
                    <fullName>BF</fullName>
                </value>
                <value>
                    <fullName>BG</fullName>
                </value>
                <value>
                    <fullName>BH</fullName>
                </value>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BJ</fullName>
                </value>
                <value>
                    <fullName>BL</fullName>
                </value>
                <value>
                    <fullName>BM</fullName>
                </value>
                <value>
                    <fullName>BN</fullName>
                </value>
                <value>
                    <fullName>BO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QuoteTemplate__c</fullName>
        <description>References the default Quote Template value</description>
        <inlineHelpText>References the default Quote Template value</inlineHelpText>
        <label>Quote Template</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Quote Template: Austria</fullName>
                </value>
                <value>
                    <fullName>Quote Template: Belgium</fullName>
                    <isActive>false</isActive>
                    <label>Quote Template: Belgium</label>
                </value>
                <value>
                    <fullName>Quote Template: Belgium (Dutch)</fullName>
                </value>
                <value>
                    <fullName>Quote Template: Belgium (French)</fullName>
                </value>
                <value>
                    <fullName>Quote Template: España</fullName>
                    <default>true</default>
                    <label>Quote Template: España</label>
                </value>
                <value>
                    <fullName>Quote Template: France</fullName>
                </value>
                <value>
                    <fullName>Quote Template: Germany</fullName>
                </value>
                <value>
                    <fullName>Quote Template: Luxembourg</fullName>
                </value>
                <value>
                    <fullName>Quote Template: Netherlands</fullName>
                </value>
                <value>
                    <fullName>Quote Template: Netherlands/Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Quote Template: Netherlands/Luxembourg</label>
                </value>
                <value>
                    <fullName>Quote Template: Portugal</fullName>
                </value>
                <value>
                    <fullName>Quote Template: UK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote Country Setting</label>
    <pluralLabel>Quote Country Settings</pluralLabel>
</CustomObject>

src/classes/QuoteTriggerHelper.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Houssam ADIB (Salesforce)
Description:    Quote Trigger Helper Class
Test class      Test_QuoteTriggerHandler

History
8-Sept-2022     Create new Class
----------------------------------------------------------------------------------------*/
public with sharing class QuoteTriggerHelper {


    /*------------------------------------------------------------
    Description:    Loop country setting records to find the quote correspondent template
    Inputs:         @param  quotes          New Quote records just inserted

    History:
    8-Sep-2022      Houssam     New Method
    ------------------------------------------------------------*/
    public static void setQuotePreDefinedValues(List<Quote> quotes)
    {
        Map<Id, Opportunity> opportunities = retrieveQuotesOpportunities(quotes);

        Map<Id, Opportunity> quoteOpportunityMap = populateQuoteOpportunityMap(quotes, opportunities);

        setPredefinedValues(quotes, quoteOpportunityMap);
    }


    /*------------------------------------------------------------
    Description:    Set the predefined values for the new quotes inserted
    Inputs:         @param  quotes                  New Quote records just inserted
                    @param  quoteOpportunityMap     Map mapping each quote to its opportunity

    History:
    8-Sep-2022      Houssam     New Method
    ------------------------------------------------------------*/
    public static void setPredefinedValues(List<Quote> quotes, Map<Id, Opportunity> quoteOpportunityMap)
    {
        List<QuoteCountrySetting__mdt> quoteSettings = [SELECT CountryCode__c, QuoteTemplate__c FROM QuoteCountrySetting__mdt];

        for (Quote newQuote : quotes)
        {
            String accountCountry = quoteOpportunityMap.get(newQuote.Id).Account.Country__c;
            setQuoteTemplate(newQuote, accountCountry, quoteSettings);
            setQuoteManagers(newQuote,quoteOpportunityMap.get(newQuote.Id));
        }
    }

    /*------------------------------------------------------------
    Description:    Set the predefined values for the new quotes inserted
    Inputs:         @param  newQuote        New Quote inserted
                    @param  opportunity     Quote opportunity

    History:
    19-Sep-2022      Houssam     New Method
    ------------------------------------------------------------*/
    public static void setQuoteManagers(Quote newQuote, Opportunity opportunity)
    {
        if(opportunity.Owner.ManagerId != null)
        {
            if(newQuote.Manager__c == null)
            {
                newQuote.Manager__c = opportunity.Owner.ManagerId;
            }
            if(newQuote.X2nd_level_Manager__c == null)
            {
                newQuote.X2nd_level_Manager__c = (opportunity.Owner.Manager.ManagerId != null ) ? opportunity.Owner.Manager.ManagerId : null;
            }
        }
    }

    /*------------------------------------------------------------
    Description:    Loop country setting records to find the quote correspondent template to set
    Inputs:         @param  quote                   New Quote record
                    @param  quoteCountrySettings    List of Quote Country Settings

    Outputs:        String     Quote Template. (SelectQuoteTemplate__c picklist value)
    History:
    8-Sep-2022      Houssam     New Method
    ------------------------------------------------------------*/
    public static void setQuoteTemplate(Quote newQuote, String accountCountryCode, List<QuoteCountrySetting__mdt> quoteCountrySettings)
    {
        for (QuoteCountrySetting__mdt countrySetting : quoteCountrySettings)
        {
            if(accountCountryCode == countrySetting.CountryCode__c)
            {
                newQuote.SelectQuoteTemplate__c = countrySetting.QuoteTemplate__c;
            }
        }
    }

    /*------------------------------------------------------------
    Description:    Populates a map of quote id to its opportunity record having Account.Country__c field value
    Inputs:         @param  quotes              List of new quotes records
                    @param  opportunities       List of Quotes opportunities retrieved from database

    Outputs:        Map<Id, Opportunity>        Mapping each Quote id to its opportunity record
    History:
    8-Sep-2022      Houssam     New Method
    ------------------------------------------------------------*/
    public static Map<Id, Opportunity> populateQuoteOpportunityMap(List<Quote> quotes, Map<Id, Opportunity> opportunities)
    {
        Map<Id, Opportunity> quoteOpportunityMap = new Map<Id, Opportunity>();
        for (Quote quote : quotes)
        {
            quoteOpportunityMap.put(quote.Id, opportunities.get(quote.OpportunityId));
        }
        return quoteOpportunityMap;
    }

    /*------------------------------------------------------------
    Description:    retrieve quotes opportunities to get their Account.Country__c field
    Inputs:         @param  quotes              List of new quotes records

    Outputs:        Map<Id, Opportunity>        Mapping Quote Id to its opportunity
    History:
    8-Sep-2022      Houssam     New Method
    ------------------------------------------------------------*/
    public static Map<Id, Opportunity> retrieveQuotesOpportunities(List<Quote> quotes)
    {
        Set<Id> opportunitiesIds = new Set<Id>();
        for (Quote quote : quotes)
        {
            opportunitiesIds.add(quote.OpportunityId);
        }
        return (new Map<Id, Opportunity>([SELECT Id, Account.Country__c,Opportunity.Owner.Manager.ManagerId FROM Opportunity WHERE Id IN :opportunitiesIds]));
    }
}