src/objects/Country__c.object
<CustomObject>
    <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Implants</fullName>
                    <label>Global DPG</label>
                </value>
                <value>
                    <fullName>All Ortho</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ATF</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
                <value>
                    <fullName>BHR</fullName>
                </value>
                <value>
                    <fullName>BHS</fullName>
                </value>
                <value>
                    <fullName>BIH</fullName>
                </value>
                <value>
                    <fullName>BLM</fullName>
                </value>
                <value>
                    <fullName>BLR</fullName>
                </value>
                <value>
                    <fullName>BLZ</fullName>
                </value>
                <value>
                    <fullName>BMU</fullName>
                </value>
                <value>
                    <fullName>BOL</fullName>
                </value>
                <value>
                    <fullName>BRA</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProcedureTracker__c.object
<CustomObject>
    <description>Follow Up your Sales Lifecycle with step-by-step guided instructions. 
#1 Procedure Type: Clear Aligners - suresmile</description>
    <fields>
        <fullName>ObtainCreditCardInformation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Obtain Credit Card Information</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PracticeAccount__c</fullName>
        <label>Practice Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Procedures</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Procedure Tracker</label>
    <nameField>
        <displayFormat>Track#{000}</displayFormat>
        <label>Record Nr</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Procedure Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_GuidanceRendererController.cls
/*-------------------------------------------------------------------------------------------------	
 * Author            : naoussar@salesforce.com
 * Description       : Test class of GuidanceRendererController
 * History	
 * 09-09-2022        : Created (#TFUS-000004603)
--------------------------------------------------------------------------------------------------*/
@isTest
public class Test_GuidanceRendererController {
    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.createUsers(1, '#System: System Administrator');
        TestDataFactory.createGlobalIntegrationSettings(userList);
        TestDataFactory.createDefaultOrgLevelBypassPB();
        List<Account> testAccount = TestDataFactory.returnAccounts(1, 'CIM_Account', userList[0].Id);
        insert testAccount;
        
        
    }
	@isTest
    public static void testGetGuidanceDetails(){
        
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) 
        {
            Account acc = [SELECT id,Country__c FROM Account LIMIT 1];
            acc.Country__c = 'US';
            update acc;
            ProcedureTracker__c testProcedureTracker = new ProcedureTracker__c(PracticeAccount__c = acc.Id,
                                                                               ObtainCreditCardInformation__c  = true);
            insert testProcedureTracker;
            
            Test.startTest();
                String contentOfGuidance = GuidanceRendererController.getGuidanceDetails(testProcedureTracker.Id,'Obtain Credit Card Information');
            Test.stopTest();
            System.assertNotEquals('',contentOfGuidance);
        }
        
                          
    }
}