src/objects/Country__c.object
<CustomObject>
    <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Implants</fullName>
                    <label>Global DPG</label>
                </value>
                <value>
                    <fullName>All Ortho</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ATF</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
                <value>
                    <fullName>BHR</fullName>
                </value>
                <value>
                    <fullName>BHS</fullName>
                </value>
                <value>
                    <fullName>BIH</fullName>
                </value>
                <value>
                    <fullName>BLM</fullName>
                </value>
                <value>
                    <fullName>BLR</fullName>
                </value>
                <value>
                    <fullName>BLZ</fullName>
                </value>
                <value>
                    <fullName>BMU</fullName>
                </value>
                <value>
                    <fullName>BOL</fullName>
                </value>
                <value>
                    <fullName>BRA</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/My_Calls_to_make__mdt.object
<CustomObject>
    <description>will hold the reports of the calls to make for each country to be used to managed the display of this links in the utility bar ( My calls to make ) based on the country of the user</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>List of countries related to the same report</description>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link_text__c</fullName>
        <description>text to be displayed on the link of redirection</description>
        <label>Link text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Id__c</fullName>
        <description>Id of the report to display</description>
        <label>Report Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>My Calls to make</label>
    <pluralLabel>My Calls to make</pluralLabel>
</CustomObject>

src/classes/InsideSalesMyCallsToMakeController.cls
/*-------------------------------------------------------------------------------------------------	
 * Author            : naoussar@salesforce.com
 * Description       : InsideSalesMyCallsToMakeController Apex controller of InsideSalesMyCallsToMake LWC
 * Test class        : Test_InsideSalesMyCallsToMakeController
 * History	
 * 25-07-2022        : Created (#TFUS-000004530)
--------------------------------------------------------------------------------------------------*/
public with sharing class InsideSalesMyCallsToMakeController {
    //get in param the country of the user and based on that check in MDT the other params 
    /*------------------------------------------------------------	
	Description: Look over the My_Calls_to_make__mdt and found the record related to the user country 
	Inputs: userCountry coming from the UI by retrieving current user country from the lwc 
    -------------------------------------------------------------*/	
    @AuraEnabled(cacheable=true)
    public static My_Calls_to_make__mdt getMyCallsToMakeReport(String userCountry){
    try {
        My_Calls_to_make__mdt mycallstoMakeResult;
        
        for (My_Calls_to_make__mdt mycallstoMake : [SELECT id, MasterLabel, Country__c, Link_text__c, Report_Id__c FROM My_Calls_to_make__mdt]){
            if (mycallstoMake.Country__c.contains(userCountry)) {
                mycallstoMakeResult = mycallstoMake;
                break;
            }
        }
        return mycallstoMakeResult;
    } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
    }
    }
}