src/objects/Country__c.object
<CustomObject>
    <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Implants</fullName>
                    <label>Global DPG</label>
                </value>
                <value>
                    <fullName>All Ortho</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ATF</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
                <value>
                    <fullName>BHR</fullName>
                </value>
                <value>
                    <fullName>BHS</fullName>
                </value>
                <value>
                    <fullName>BIH</fullName>
                </value>
                <value>
                    <fullName>BLM</fullName>
                </value>
                <value>
                    <fullName>BLR</fullName>
                </value>
                <value>
                    <fullName>BLZ</fullName>
                </value>
                <value>
                    <fullName>BMU</fullName>
                </value>
                <value>
                    <fullName>BOL</fullName>
                </value>
                <value>
                    <fullName>BRA</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Field_Sales_Project__c.object
<CustomObject>
    <description>Used by Sales Teams to collect Accounts into different Initiatives.
		These are all managed and created by the Field Sales Teams.</description>
    <fields>
        <fullName>AllowUsersToAddNewLeads__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow users to add new leads</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>3D Upgrade</fullName>
                </value>
                <value>
                    <fullName>ACB with ASA</fullName>
                </value>
                <value>
                    <fullName>AlginX</fullName>
                </value>
                <value>
                    <fullName>All Ceramics</fullName>
                </value>
                <value>
                    <fullName>All Other Endo</fullName>
                </value>
                <value>
                    <fullName>All Other - Niti Rotary Files</fullName>
                </value>
                <value>
                    <fullName>All Other – Obturation</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>ANKYLOS</fullName>
                </value>
                <value>
                    <fullName>Apex Locator</fullName>
                </value>
                <value>
                    <fullName>Aquasil</fullName>
                </value>
                <value>
                    <fullName>Aquasil Ultra Plus</fullName>
                </value>
                <value>
                    <fullName>ATIS</fullName>
                </value>
                <value>
                    <fullName>ATIS EV</fullName>
                </value>
                <value>
                    <fullName>ATIS TX</fullName>
                </value>
                <value>
                    <fullName>Atlantis</fullName>
                </value>
                <value>
                    <fullName>Atlantis Abutments</fullName>
                </value>
                <value>
                    <fullName>Automate</fullName>
                </value>
                <value>
                    <fullName>Axano</fullName>
                </value>
                <value>
                    <fullName>Azento Astra Tech</fullName>
                </value>
                <value>
                    <fullName>Azento EV</fullName>
                </value>
                <value>
                    <fullName>Azento XiVE</fullName>
                </value>
                <value>
                    <fullName>Bonding</fullName>
                </value>
                <value>
                    <fullName>Bone</fullName>
                </value>
                <value>
                    <fullName>Brackets</fullName>
                </value>
                <value>
                    <fullName>Calibra</fullName>
                </value>
                <value>
                    <fullName>Carbide Burs</fullName>
                </value>
                <value>
                    <fullName>Cavitron</fullName>
                </value>
                <value>
                    <fullName>Celtra</fullName>
                </value>
                <value>
                    <fullName>Celtra Duo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>UserCountry__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>3D Imaging</fullName>
                    <isActive>false</isActive>
                    <label>3D Imaging</label>
                </value>
                <value>
                    <fullName>ATLANTIS</fullName>
                    <isActive>false</isActive>
                    <label>ATLANTIS</label>
                </value>
                <value>
                    <fullName>CEREC Equipment</fullName>
                    <isActive>false</isActive>
                    <label>CEREC Equipment</label>
                </value>
                <value>
                    <fullName>Class II</fullName>
                </value>
                <value>
                    <fullName>Consumables</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Digital Group</fullName>
                </value>
                <value>
                    <fullName>Digital Services</fullName>
                </value>
                <value>
                    <fullName>Digital Solutions</fullName>
                    <isActive>false</isActive>
                    <label>Digital Solutions</label>
                </value>
                <value>
                    <fullName>Endentulous</fullName>
                    <isActive>false</isActive>
                    <label>Endentulous</label>
                </value>
                <value>
                    <fullName>Endodontics</fullName>
                </value>
                <value>
                    <fullName>Equipment</fullName>
                </value>
                <value>
                    <fullName>Equipment &amp; Imaging</fullName>
                </value>
                <value>
                    <fullName>Extra Oral Imaging</fullName>
                    <isActive>false</isActive>
                    <label>Extra Oral Imaging</label>
                </value>
                <value>
                    <fullName>Implants</fullName>
                </value>
                <value>
                    <fullName>InLab</fullName>
                    <isActive>false</isActive>
                    <label>InLab</label>
                </value>
                <value>
                    <fullName>Intra Oral Imaging</fullName>
                    <isActive>false</isActive>
                    <label>Intra Oral Imaging</label>
                </value>
                <value>
                    <fullName>Midwest Equipment</fullName>
                    <isActive>false</isActive>
                    <label>Midwest Equipment</label>
                </value>
                <value>
                    <fullName>Orthodontics</fullName>
                </value>
                <value>
                    <fullName>Preventive</fullName>
                    <isActive>false</isActive>
                    <label>Preventive</label>
                </value>
                <value>
                    <fullName>Procedures</fullName>
                    <isActive>false</isActive>
                    <label>Procedures</label>
                </value>
                <value>
                    <fullName>Prosthetics</fullName>
                </value>
                <value>
                    <fullName>Regenerative</fullName>
                    <isActive>false</isActive>
                    <label>Regenerative</label>
                </value>
                <value>
                    <fullName>Restorative</fullName>
                    <isActive>false</isActive>
                    <label>Restorative</label>
                </value>
                <value>
                    <fullName>Root To Crown</fullName>
                </value>
                <value>
                    <fullName>Single Unit Crown</fullName>
                </value>
                <value>
                    <fullName>Treatment Centers</fullName>
                    <isActive>false</isActive>
                    <label>Treatment Centers</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                    <isActive>false</isActive>
                    <label>In progress</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <inlineHelpText>This helps the naming of the Initiative</inlineHelpText>
        <label>Title</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Target List</label>
    <nameField>
        <label>Target List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Target Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LeadOpportunitySetting__mdt.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consumables</fullName>
                    <default>true</default>
                    <label>Consumables</label>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Digital Group</fullName>
                </value>
                <value>
                    <fullName>Endodontics</fullName>
                </value>
                <value>
                    <fullName>Equipment</fullName>
                </value>
                <value>
                    <fullName>Equipment &amp; Imaging</fullName>
                </value>
                <value>
                    <fullName>Implants</fullName>
                </value>
                <value>
                    <fullName>Orthodontics</fullName>
                </value>
                <value>
                    <fullName>Prosthetics</fullName>
                </value>
                <value>
                    <fullName>Class II</fullName>
                </value>
                <value>
                    <fullName>Single Unit Crown</fullName>
                </value>
                <value>
                    <fullName>Root To Crown</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Digital Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lead &amp; Opportunity Setting</label>
    <pluralLabel>Lead &amp; Opportunity Settings</pluralLabel>
</CustomObject>

src/classes/LeadController.cls
/*------------------------------------------------------------	
Author: 		Richard Trum (Glimt) 2019-11-28 	
Description:   	Class for handling CRUD calls related to the Lead__c and Field_Sales_Project__c objects
History:
23-07-2023   Houssam Adib        Sync the dealer filter with the lookup filter [TFUS-000006089]
01-01-2024   Houssam Adib        Refactor the code and change filter logic to use DistributorCategorisation__c rather than DistributorCategories__c
31-10-2024   Houssam Adib        Change the order of selected initiatives to order them by title [TFUS-000007049]
------------------------------------------------------------*/

public with sharing class LeadController {

    private final static Integer MAX_RESULTS = 5;
    private final static String DISTRIBUTOR = 'Distributor';

    @AuraEnabled
    public static List<Field_Sales_Project__c> getInitiatives(){

        List<Field_Sales_Project__c> inits = [  SELECT Id, Title__c, Category__c, Brand__c, Status__c
                                                FROM Field_Sales_Project__c
                                                WHERE (AllowUsersToAddNewLeads__c =: true AND Status__c=:'Active')
                                                ORDER BY Title__c];
        return inits;
    }

    @AuraEnabled
    public static List<LeadOpportunitySetting__mdt> getSalesLeadSettings(String category, String country){

        List<LeadOpportunitySetting__mdt> settings = [SELECT DeveloperName, Category__c, Country__c, ShowDistributor__c, IsTest__c FROM LeadOpportunitySetting__mdt WHERE (Category__c =:category AND Country__c =: country)];

        return settings;
    }

    @AuraEnabled(Cacheable=true)
    public static List<LookupSearchResult> search(String searchTerm, List<String> selectedIds, String category)
    {
        // Prepare query parameters
        searchTerm += '*';

        List<List<SObject>> searchResults = [
                FIND :searchTerm
                IN ALL FIELDS
                RETURNING
                        Account(Id, Name, ShippingCity
                                WHERE
                                Id NOT IN :selectedIds
                                AND
                                (
                                        OneAccount_Type__c = :DISTRIBUTOR
                                        AND
                                        DistributorCategorisation__c EXCLUDES (:category)
                                )
                        )

                LIMIT :MAX_RESULTS
        ];

        // Prepare results
        List<LookupSearchResult> results = new List<LookupSearchResult>();

        // Extract Accounts & convert them into LookupSearchResult
        String accountIcon = 'standard:account';
        Account[] accounts = (List<Account>) searchResults[0];

        for (Account account : accounts) {
            results.add(
                    new LookupSearchResult(
                            account.Id,
                            'Account',
                            accountIcon,
                            account.Name,
                            'Account • ' + account.ShippingCity
                    )
            );
        }

        // Optionally sort all results on title
        results.sort();

        return results;
    }
}