src/objects/Country__c.object
<CustomObject>
    <description>DEPLOYMENT - Internal object for tracking Country Information and SFDC Global Deployment Status</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Implants</fullName>
                    <label>Global DPG</label>
                </value>
                <value>
                    <fullName>All Ortho</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ATF</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
                <value>
                    <fullName>BHR</fullName>
                </value>
                <value>
                    <fullName>BHS</fullName>
                </value>
                <value>
                    <fullName>BIH</fullName>
                </value>
                <value>
                    <fullName>BLM</fullName>
                </value>
                <value>
                    <fullName>BLR</fullName>
                </value>
                <value>
                    <fullName>BLZ</fullName>
                </value>
                <value>
                    <fullName>BMU</fullName>
                </value>
                <value>
                    <fullName>BOL</fullName>
                </value>
                <value>
                    <fullName>BRA</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Preferred_dealer_item__c.Account__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Preferred_dealer_item__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distributor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distributor</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 OR 2 OR 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>01220000000ckje</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>01220000000ckja</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>equals</operation>
                <value>4PL Indonesia email delivery test</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Distributor)</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Direct_global_order</fullName>
        <active>true</active>
        <label>Direct global order</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Preferred_dealer_item__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealers</relationshipLabel>
        <relationshipName>Preferred_dealer_items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>ERP Distributor, Non-ERP Distributor, DNA Distributor</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>CIM Account</value>
            </filterItems>
            <filterItems>
                <field>Account.OneAccount_Type__c</field>
                <operation>equals</operation>
                <value>Distributor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealers (Dealer)</relationshipLabel>
        <relationshipName>Preferred_dealer_items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default_dealer__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Default dealer</label>
        <type>Checkbox</type>
    </fields>
    <label>Dealer</label>
    <nameField>
        <displayFormat>PDI{00000}</displayFormat>
        <label>Dealer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_OrderDealerSearchBoxCopy.cls
/**
 * @Author          Omar (ohanafi@salesforce.com)
 * @Description     Test class for OrderDealerSearchBoxCopy.
 *
 * @History
 * 28-11-2024   Omar     Created test class
 */

@isTest
public class Test_OrderDealerSearchBoxCopy {

    /**
    * Test method for getOrdersByAccountId
    */
    @testSetup
    private static void setupTestData() {

        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.returnUsers(1, '#System: System Administrator');
        insert userList;
        TestDataFactory.createGlobalIntegrationSettings(userList);
        TestDataFactory.createDefaultOrgLevelBypassPB();

        // Create test Accounts
        List<Account> testAccounts = TestDataFactory.returnAccounts(1, 'CIM_Account', userList[0].Id);
        testAccounts[0].Name = 'Test Account 1';
        testAccounts[0].Country__c = 'US';
        testAccounts[0].OneAccount_Type__c = 'Distributor';
        insert testAccounts;

        // Create test Product, Pricebook and Pricebook Entry
        List<Pricebook2> testPriceBooks = TestDataFactory.createPricebooks(1, 'Turkey PREP Pricebook');
        List<Product2> testProducts = TestDataFactory.createProducts(1);
        List<PricebookEntry> testPricebookEntries = TestDataFactory.createPricebookEntries(1, testPriceBooks, testProducts);

        // Create test Order
        List<Order> testOrders = TestDataFactory.returnOrders(1, 'Direct_global_order', new List<Account>{testAccounts[0]});
        testOrders[0].Name = 'Test Order 1';
        testOrders[0].EffectiveDate = Date.today();
        testOrders[0].Pricebook2Id = testPriceBooks[0].Id;
        insert testOrders;

        // Create test Order Item
        List<OrderItem> orderItems = TestDataFactory.returnOrderItems(1, testOrders, testPricebookEntries);
        insert orderItems;

        // Create Preferred Dealer Items for Account 1
        Preferred_dealer_item__c dealer1 = new Preferred_dealer_item__c(Account__c = testAccounts[0].Id, Dealer__c = testAccounts[0].Id, Default_dealer__c = true);
        insert dealer1;
    }

    /**
    * Test method for saveDealer
    */
    @isTest
    private static void testSaveDealer() {
        // Retrieve the test user
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        System.runAs(testUser) {
            // Fetch test data
            Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account 1' LIMIT 1];
            Order order1 = [SELECT Id FROM Order WHERE Name = 'Test Order 1' LIMIT 1];

            Test.startTest();
            // Invoke saveDealer method
            List<Preferred_dealer_item__c> result = OrderDealerSearchBoxCopy.saveDealer(new List<Account>{testAccount}, order1.Id);
            Test.stopTest();

            // Assertions
            System.assertEquals(1, result.size(), 'Expected one Preferred Dealer item.');
        }
    }

    /**
    * Test method for CheckPermission
    */
    @isTest
    private static void testCheckPermission() {
        // Retrieve the test user
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        System.runAs(testUser) {
            Test.startTest();
            Boolean hasPermission = OrderDealerSearchBoxCopy.CheckPermission();
            Test.stopTest();

            // Assertions
            System.assertNotEquals(null, hasPermission, 'Permission check should return a value.');
        }
    }

    /**
    * Test method for getAllPdeList
    */
    @isTest
    private static void testGetAllPdeList() {
        // Retrieve the test user
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        System.runAs(testUser) {
            Order order1 = [SELECT Id FROM Order WHERE Name = 'Test Order 1' LIMIT 1];

            Test.startTest();
            List<Preferred_dealer_item__c> pdeList = OrderDealerSearchBoxCopy.getAllPdeList(order1.Id);
            Test.stopTest();

            // Assertions
            System.assertEquals(1, pdeList.size(), 'Expected 1 preferred dealer item associated with the Order.');
        }
    }

    /**
    * Test method for getUpdateFromOrder
    */
    @isTest
    private static void testGetUpdateFromOrder() {
        // Retrieve the test user
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        System.runAs(testUser) {
            Order order1 = [SELECT Id FROM Order WHERE Name = 'Test Order 1' LIMIT 1];

            Test.startTest();
            Order result = OrderDealerSearchBoxCopy.getUpdateFromOrder(order1.Id);
            Test.stopTest();

            // Assertions
            System.assertNotEquals(null, result, 'Result should not be null');
            System.assertEquals(order1.Id, result.Id, 'Order Id should match');
        }
    }

    /**
    * Test method for fetchLookUpValues
    */
    @isTest
    private static void testFetchLookUpValues() {
        // Retrieve the test user
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        System.runAs(testUser) {
            Order order1 = [SELECT Id FROM Order WHERE Name = 'Test Order 1' LIMIT 1];

            Test.startTest();
            OrderDealerSearchBoxCopy.AccountDataTableWrapper wrapper =
                    OrderDealerSearchBoxCopy.fetchLookUpValues(1, 10, 'Test', order1.Id);
            Test.stopTest();

            // Assertions
            System.assertNotEquals(null, wrapper, 'Wrapper should not be null.');
            System.assert(wrapper.accountList.size() > 0, 'Expected accounts in the returned wrapper.');
        }
    }

    /**
    * Test method for updateDealerInfoToOrder
    */
    @isTest
    private static void testUpdateDealerInfoToOrder() {
        // Retrieve the test user
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        System.runAs(testUser) {
            Preferred_dealer_item__c dealer = [SELECT Id FROM Preferred_dealer_item__c LIMIT 1];
            Order order = [SELECT Id, Name FROM Order LIMIT 1];

            Test.startTest();
            Order updatedOrder = OrderDealerSearchBoxCopy.updateDealerInfoToOrder(dealer.Id, order);
            Test.stopTest();

            // Assertions
            System.assertNotEquals(null, updatedOrder.Distributor__c, 'Distributor should be updated.');
        }
    }

    /**
    * Test method for updateOrder
    */
    @isTest
    private static void testUpdateOrder() {
        // Retrieve the test user
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        System.runAs(testUser) {
            Order order = [SELECT Id FROM Order LIMIT 1];
            order.Status = 'Activated';

            Test.startTest();
            Order updatedOrder = OrderDealerSearchBoxCopy.updateOrder(order);
            Test.stopTest();

            // Assertions
            System.assertEquals('Activated', updatedOrder.Status, 'Order status should be updated.');
        }
    }

    /**
    * Test method for Initialize
    */
    @isTest
    private static void testInitialize() {
        // Retrieve the test user
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1' LIMIT 1];

        System.runAs(testUser) {
            Order order = [SELECT Id FROM Order LIMIT 1];

            Test.startTest();
            Order initializedOrder = OrderDealerSearchBoxCopy.Initialize(order.Id);
            Test.stopTest();

            // Assertions
            System.assertNotEquals(null, initializedOrder, 'Initialized Order should not be null.');
        }
    }
}