src/objects/CventEvents__Attendee__c.object
<CustomObject>
    <description>Represents the attendee of an event.</description>
    <fields>
        <fullName>CventEvents__Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Number</label>
        <referenceTo>CventEvents__Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CventEvents__AttendeeTemp__c.object
<CustomObject>
    <description>Auxiliary object used for storing a fusion of contact and event participation information retrieved from Cvent.</description>
    <label>Attendee Temp Record</label>
    <nameField>
        <displayFormat>AT-{00000000}</displayFormat>
        <label>Attendee Temp Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendee Temp Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CventEvents__Event__c.object
<CustomObject>
    <description>Represents the event defined in Cvent.</description>
    <label>Cvent Event</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cvent Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AttendeeWrapper.cls
/*-------------------------------------------------------------------------------------------------------
Description:    Wrapper to help the communication between LWC & Controller
History
2023-03-13      Houssam ADIB        Create New Wrapper
----------------------------------------------------------------------------------------*/
public class AttendeeWrapper {

    @AuraEnabled
    public CventEvents__Event__c            event           { get; set; }
    @AuraEnabled
    public CventEvents__AttendeeTemp__c     tempAttendee    { get; set; }
    @AuraEnabled
    public CventEvents__Attendee__c         attendee        { get; set; }
    @AuraEnabled
    public Lead                             lead            { get; set; }
    @AuraEnabled
    public Contact                          contact         { get; set; }
    @AuraEnabled
    public Boolean                          matched         { get; set; }

}