src/objects/CventEvents__Attendee__c.object
<CustomObject>
    <description>Represents the attendee of an event.</description>
    <fields>
        <fullName>CventEvents__AttendeeStub__c</fullName>
        <externalId>true</externalId>
        <label>Attendee Stub</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CventEvents__Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Number</label>
        <referenceTo>CventEvents__Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CventEvents__Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Visited</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Denied Approval</fullName>
                </value>
                <value>
                    <fullName>Invitation Not Sent</fullName>
                </value>
                <value>
                    <fullName>Invitation Pending</fullName>
                </value>
                <value>
                    <fullName>Nomination Pending</fullName>
                </value>
                <value>
                    <fullName>Nomination Approved</fullName>
                </value>
                <value>
                    <fullName>Nomination Denied</fullName>
                </value>
                <value>
                    <fullName>Nomination Cancelled</fullName>
                </value>
                <value>
                    <fullName>Substituted</fullName>
                </value>
                <value>
                    <fullName>Registration Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CventEvents__AttendeeTemp__c.object
<CustomObject>
    <description>Auxiliary object used for storing a fusion of contact and event participation information retrieved from Cvent.</description>
    <fields>
        <fullName>CventEvents__pkg_AttendeeStatus__c</fullName>
        <label>Attendee Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CventEvents__pkg_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CventEvents__pkg_EventStub__c</fullName>
        <externalId>true</externalId>
        <label>Event Stub</label>
        <length>36</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Attendee Temp Record</label>
    <nameField>
        <displayFormat>AT-{00000000}</displayFormat>
        <label>Attendee Temp Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendee Temp Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CventEvents__Event__c.object
<CustomObject>
    <description>Represents the event defined in Cvent.</description>
    <fields>
        <fullName>CventEvents__pkg_EventStub__c</fullName>
        <externalId>true</externalId>
        <label>Event Stub</label>
        <length>36</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cvent Event</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cvent Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>AttendeeStub__c</fullName>
        <description>Cvent Application Attendee Stub</description>
        <externalId>true</externalId>
        <label>Attendee Stub</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/AttendeeTempTriggerHelperTest.cls
@IsTest
public with sharing class AttendeeTempTriggerHelperTest {

    @TestSetup
    private static void setup(){
        TestDataFactory.createBypassCustomSetting();
    }

    @isTest
    private static void testConvertedEventReceivedNewUpdatesInTemp(){
        TestDataFactory.assignPermissionSet(UserInfo.getUserId(),'Global_Campaigns_CVENT_Campaigns');
        System.runAs(new User(Id=UserInfo.getUserId()))
        {
            //Given
            String eventCode = 'P7N2MG8Y827';
            CventEvents__Event__c event = TestDataFactory.createCventEvent(eventCode, true);
            CventEvents__AttendeeTemp__c temp = TestDataFactory.createAttendeeTemp('AttendeeStubId', event.CventEvents__pkg_EventStub__c, true);

            quickCreateCampaignFromCventController.ResultWrapper resultOne;
            quickCreateCampaignFromCventController.ResultWrapper resultTwo;
            quickCreateCampaignFromCventController.ResultWrapper resultThree;

            resultOne = quickCreateCampaignFromCventController.createCampaignFromCvent(eventCode,'',false);
            resultTwo = quickCreateCampaignFromCventController.convertTempAttendeesToLeads(eventCode);
            resultThree = quickCreateCampaignFromCventController.createNewAttendeesFromLeads(resultTwo.attendeeWrappers);

            // When
            Test.startTest();
            TriggerHandler.clearBypass('AttendeeTempTriggerHandler');
            temp.CventEvents__pkg_AttendeeStatus__c = 'Accepted';
            temp.CventEvents__pkg_Email__c = 'newemail@gmail.com';
            update temp;
            Test.stopTest();

            Lead lead = [SELECT Id, Email FROM Lead WHERE AttendeeStub__c = 'AttendeeStubId'];
            CventEvents__Attendee__c attendee = [SELECT Id, CventEvents__Status__c FROM CventEvents__Attendee__c WHERE CventEvents__AttendeeStub__c = 'AttendeeStubId'];
            //Then
            System.assertEquals('newemail@gmail.com', lead?.Email, 'Lead Email Not Synced');
            System.assertEquals('Accepted', attendee?.CventEvents__Status__c, 'Attendee Status Not Synced');
        }
    }
}