src/objects/CventEvents__Event__c.object
<CustomObject>
    <description>Represents the event defined in Cvent.</description>
    <label>Cvent Event</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cvent Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DebugLog__c.object
<CustomObject>
    <description>Object with debug log records. Used by ApexClass DebugLog to extend the default system debug standard features of Salesforce.</description>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Debug Log</label>
    <nameField>
        <displayFormat>Log # {0000}</displayFormat>
        <label>Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DynamicMapping__mdt.object
<CustomObject>
    <description>It provides a way to map the fields of one object to another, allowing for the seamless transfer of data between the two objects</description>
    <fields>
        <fullName>isNew__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Determines whether a record has just been created and it hasn&apos;t yet been validated in Apex. Once the validation will run, this field will be unchecked and the field isValid will get a value.</description>
        <inlineHelpText>System field. This shouldn&apos;t be modified.</inlineHelpText>
        <label>isNew</label>
        <type>Checkbox</type>
    </fields>
    <label>Dynamic Mapping</label>
    <pluralLabel>Dynamic Mappings</pluralLabel>
</CustomObject>

src/classes/MappingManagementTest.cls
@IsTest
public without sharing class MappingManagementTest {

    @TestSetup
    private static void setup(){
        TestDataFactory.assignPermissionSet(UserInfo.getUserId(),'Global_Campaigns_CVENT_Campaigns');
    }
    @IsTest
    public static void testRetrieveSourceData() {
        System.runAs(new User(Id=UserInfo.getUserId()))
        {
            // Given
            String eventCode = 'P7N2MG8Y827';
            CventEvents__Event__c event = TestDataFactory.createCventEvent(eventCode, true);

            // When
            Test.startTest();
            quickCreateCampaignFromCventController.ResultWrapper result = quickCreateCampaignFromCventController.createCampaignFromCvent(eventCode,'',false);
            Test.stopTest();

            // Then
            System.assertEquals(null, result.error, 'Conversion has errors');
        }
    }

    @IsTest
    public static void testlaunchValidationAsynchronous() {
        System.runAs(new User(Id=UserInfo.getUserId()))
        {
            // When We launch mappings validation
            Test.startTest();
            {
                MappingManagement.launchValidationAsynchronous(CventManagement.SOURCE_OBJECT_TEMP, CventManagement.TARGET_OBJECT_LEAD);
                MappingManagement.tickTargetFieldAsInvalid('Status', 'Error Msg',
                        CventManagement.SOURCE_OBJECT_TEMP, CventManagement.TARGET_OBJECT_LEAD);
            }
            Test.stopTest();

            // Then
            List<DynamicMapping__mdt> newMappings = [SELECT Id FROM DynamicMapping__mdt WHERE isNew__c = TRUE];
            if(newMappings.size() > 0)
            {
                Boolean isDeploymentTriggered = false;
                List<DebugLog__c> deploymentLogs = [SELECT Id,Message__c,Comments__c FROM DebugLog__c];
                for(DebugLog__c log : deploymentLogs)
                {
                    if(log.Message__c == 'Launched Metadata Deployment Job.')
                    {
                        isDeploymentTriggered = true;
                    }
                }
                System.assert(isDeploymentTriggered, 'No deployment enqueued to validate new mappings');
            }
        }
    }

    @IsTest
    static void testValidateMapping()
    {
        System.runAs(new User(Id=UserInfo.getUserId()))
        {
            // Given
            List<DynamicMapping__mdt> mappings = MappingManagement.getMapping(
                    CventManagement.SOURCE_OBJECT_TEMP,
                    CventManagement.TARGET_OBJECT_LEAD,
                    true);

            // When
            Test.startTest();
            MappingManagement.validateMapping(CventManagement.SOURCE_OBJECT_TEMP, CventManagement.TARGET_OBJECT_LEAD, mappings);
            Test.stopTest();

            // Then
            List<DynamicMapping__mdt> newMappings = [SELECT Id FROM DynamicMapping__mdt WHERE isNew__c = TRUE];
            if(newMappings.size() > 0)
            {
                Boolean isDeploymentTriggered = false;
                List<DebugLog__c> deploymentLogs = [SELECT Id,Message__c,Comments__c FROM DebugLog__c];
                for(DebugLog__c log : deploymentLogs)
                {
                    if(log.Message__c == 'Launched Metadata Deployment Job.')
                    {
                        isDeploymentTriggered = true;
                    }
                }
                System.assert(isDeploymentTriggered, 'No deployment enqueued to validate new mappings');
            }
        }
    }

}