src/objects/DebugLog__c.object
<CustomObject>
    <description>Object with debug log records. Used by ApexClass DebugLog to extend the default system debug standard features of Salesforce.</description>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Info</fullName>
                    <color>#33FFFF</color>
                    <label>Info</label>
                </value>
                <value>
                    <fullName>Error</fullName>
                    <color>#FF9966</color>
                    <label>Error</label>
                </value>
                <value>
                    <fullName>Fatal</fullName>
                    <color>#CC6600</color>
                    <label>Fatal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Debug Log</label>
    <nameField>
        <displayFormat>Log # {0000}</displayFormat>
        <label>Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NotificationEventTest.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Houssam ADIB (Salesforce)
Description:    Test Class Covering: NotificationTrigger, NotificationTriggerHandler, NotificationEventPublisher

History
01-01-2024      Create new test class
----------------------------------------------------------------------------------------*/
@IsTest
public with sharing class NotificationEventTest
{
    @TestSetup
    private static void setup(){
        TestDataFactory.createBypassCustomSetting();
    }

    @isTest
    public static void testNotificationPublisher()
    {
        // Given PE trigger is active
        Test.startTest();
        // When
        NotificationEventPublisher.publishNotification(NotificationEventPublisher.CVENT_CONTEXT
                ,NotificationEventPublisher.CVENT_TYPE
                ,'Validations'
                ,'This is a notification message to inform that validations has Started..');
        Test.stopTest();
        // Then Assert if debug log is created
        List<DebugLog__c> debugLogs = [SELECT Id FROM DebugLog__c WHERE Severity__c = 'ERROR'];
        System.assertEquals(debugLogs.size(),0,'Error logs logged of type Error');
    }

    @isTest
    public static void testNotificationPublisherWithAdditionalInfos()
    {
        // Given PE trigger is active
        Test.startTest();
        // When
        NotificationEventPublisher.publishNotification( NotificationEventPublisher.EXCEPTION_CONTEXT,   NotificationEventPublisher.EXCEPTION_TYPE,
                'Error','getMembersCount',       'additionalInfo');

        Test.stopTest();
        // Then Assert if debug log is created
        List<DebugLog__c> debugLogs = [SELECT Id FROM DebugLog__c WHERE Severity__c = 'ERROR'];
        System.assertNotEquals(debugLogs.size(),0,'No error logs logged of type Error');
    }
}