src/objects/DebugLog__c.object
<CustomObject>
    <description>Object with debug log records. Used by ApexClass DebugLog to extend the default system debug standard features of Salesforce.</description>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Debug Log</label>
    <nameField>
        <displayFormat>Log # {0000}</displayFormat>
        <label>Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Notification__e.object
<CustomObject>
    <fields>
        <fullName>AdditionalInfo__c</fullName>
        <description>Additional JSON-formatted information.</description>
        <label>Additional Info</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Context__c</fullName>
        <description>Indicates the context or source of the message.</description>
        <label>Context</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Text field to specify the type of message</description>
        <label>Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Notification</label>
    <pluralLabel>Notifications</pluralLabel>
</CustomObject>

src/classes/NotificationTriggerHelper.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Houssam ADIB (Salesforce)
Description:    Platform Event Trigger Helper
Test class      NotificationEventTest

History
01-01-2024      Create new class
----------------------------------------------------------------------------------------*/
public with sharing class NotificationTriggerHelper {

    /**
     * This methods logs an exception instantly if the type field is 'Exception',
     * even if the transaction rollbacks on the failing process.
     * @param newNotificationList List of new Platform event notifications
     * @author hadib@salesforce.com - 01-01-2024
     */
    public static void logExceptionInstantly(List<Notification__e> newNotificationList)
    {
        List<DebugLog__c> debugLogs = new List<DebugLog__c>();
        for(Notification__e notification : newNotificationList)
        {
            if(notification.Type__c == NotificationEventPublisher.EXCEPTION_TYPE)
            {
                debugLogs.add(DebugLog.returnError(notification.Context__c, notification.Type__c, notification.Message__c, notification.AdditionalInfo__c));
            }
        }

        if(!debugLogs.isEmpty())
        {
            Database.insert(debugLogs,false);
        }
    }
}