src/objects/Field_Sales_Project_Members__c.object
<CustomObject>
    <description>Used to track targets for sales for specified initiatives based on target lists, regional initiatives, or customer interactions.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>3D Upgrade</fullName>
                </value>
                <value>
                    <fullName>ACB with ASA</fullName>
                </value>
                <value>
                    <fullName>AH Plus</fullName>
                </value>
                <value>
                    <fullName>AH Plus Bioceramic Sealer</fullName>
                </value>
                <value>
                    <fullName>AH Temp</fullName>
                </value>
                <value>
                    <fullName>AlginX</fullName>
                </value>
                <value>
                    <fullName>All Ceramics</fullName>
                </value>
                <value>
                    <fullName>All Other Endo</fullName>
                </value>
                <value>
                    <fullName>All Other - Niti Rotary Files</fullName>
                </value>
                <value>
                    <fullName>All Other – Obturation</fullName>
                </value>
                <value>
                    <fullName>Anaestadent</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>ANKYLOS</fullName>
                </value>
                <value>
                    <fullName>Apex Locator</fullName>
                </value>
                <value>
                    <fullName>Aquasil</fullName>
                </value>
                <value>
                    <fullName>Aquasil Ultra Plus</fullName>
                </value>
                <value>
                    <fullName>ATIS</fullName>
                </value>
                <value>
                    <fullName>ATIS EV</fullName>
                </value>
                <value>
                    <fullName>ATIS TX</fullName>
                </value>
                <value>
                    <fullName>Atlantis</fullName>
                </value>
                <value>
                    <fullName>Atlantis Abutments</fullName>
                </value>
                <value>
                    <fullName>Atlantis Suprastructures</fullName>
                </value>
                <value>
                    <fullName>Automate</fullName>
                </value>
                <value>
                    <fullName>Axano</fullName>
                </value>
                <value>
                    <fullName>Axeos</fullName>
                </value>
                <value>
                    <fullName>Azento Astra Tech</fullName>
                </value>
                <value>
                    <fullName>Azento EV</fullName>
                </value>
                <value>
                    <fullName>Azento XiVE</fullName>
                </value>
                <value>
                    <fullName>Bioceramic</fullName>
                </value>
                <value>
                    <fullName>Bioceramic Sealer</fullName>
                    <isActive>false</isActive>
                    <label>Bioceramic Sealer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Lead</label>
    <nameField>
        <displayFormat>Ld-{0000000}</displayFormat>
        <label>LD ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_FlowGenericMethods.cls
/*------------------------------------------------------------	
	Author: 		Richard Trum (Glimt) 2019-12-04	
	Description:   	Test class related to the class Flow_GenericMethods
	------------------------------------------------------------*/ 
@IsTest
private class Test_FlowGenericMethods {

    @TestSetup
    static void makeData(){
        User user1 = DC_UT_DataUtils.createSfUser('TestUser', 'Lightning Sales Rep');    
    }
    
    @IsTest
    private static void objectAccessTest(){
    User user1 = [SELECT Id FROM User WHERE Username LIKE 'TestUser%' LIMIT 1];
    
    Test.startTest();
    		List<String> input = new List<String>();
    		input.add('Order');
    		List<Boolean> result = Flow_GenericMethods.checkObjectAccess(input);
    		
    		System.assertEquals(result[0], true);
    
    Test.stopTest(); 
        
    }
    
    @IsTest
    private static void recordAccessTest(){
    User user1 = [SELECT Id FROM User WHERE Username LIKE 'TestUser%' LIMIT 1];
    List<Account> acc = TestDataFactory.createAccounts(1, 'CIM_Account', user1.Id);
        
    Test.startTest();
    		List<Id> input = new List<Id>();
    		input.add(acc[0].Id);
    		List<String> result = Flow_CheckRecordAccess.checkRecordAccess(input);
    		
    		System.assertNotEquals(result[0], null);
    
    Test.stopTest(); 
        
    }
    
    @IsTest
    private static void getDependentPLTest(){
        List<String> inputList = new List<String>();
        inputList.add('Field_Sales_Project_Members__c');
        inputList.add('Brand__c');
        
        List<List<String>> input = new List<List<String>>();
        
        input.add(inputList);
       
        Test.startTest();
        	Flow_getDependentPicklistValues.checkParentValues(input);
        Test.stopTest();
    }

}