src/objects/Non_ERP_Products__c.object
<CustomObject>
    <label>Non-ERP Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non-ERP Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product_Profiling__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products Profiling</relationshipLabel>
        <relationshipName>Products_Profiling</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DEPUniqueKey__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>(String) record.Account__c + (String) record.Contact__c + (String) record.Non_Erp_Product_ID__c;</description>
        <externalId>true</externalId>
        <inlineHelpText>(String) record.Account__c + (String) record.Contact__c + (String) record.Non_Erp_Product_ID__c;</inlineHelpText>
        <label>DEP Unique Key</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Integrated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To identify if a record was created by integration.</description>
        <inlineHelpText>To identify if a record was created by integration.</inlineHelpText>
        <label>Integrated ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Non-ERP Product</label>
        <referenceTo>Non_ERP_Products__c</referenceTo>
        <relationshipLabel>Products Profiling</relationshipLabel>
        <relationshipName>Products_Profiling</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Product Profiling</label>
    <nameField>
        <displayFormat>PP{000000000}</displayFormat>
        <label>Profiling Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Profiling</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_ProductProfilingTrigger.cls
/*-------------------------------------------------------------------------------------------------
 * Author            : ohanafi@salesforce.com
 * Description       : Product Profiling trigger test class
 * History
 * 01-03-2024         Created Test_ProductProfilingTrigger class (TFUS-000006225)
--------------------------------------------------------------------------------------------------*/

@isTest(seeAllData=false)
public with sharing class Test_ProductProfilingTrigger {
    /*-------------------------------------------------------------------------------------------------------
    Company: Salesforce
    Description: Setup one user for the test class
    History :
    --------------------------------------------------------------------------------------------------------*/
    @testSetup
    private static void setup() {
        TestDataFactory.createBypassCustomSetting();
        List<User> userList = TestDataFactory.createUsers(1, 'Lightning Sales Rep');
        TestDataFactory.createGlobalIntegrationSettings(userList);
        TestDataFactory.createDefaultOrgLevelBypassPB();
    }

    @isTest
    public static void testAssignUniqueKeyIdentifier() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];

        System.runAs(testUser){
            // Create test data
            List<Account> testAccount = TestDataFactory.returnAccounts(1, 'CIM_Account', testUser.Id);
            insert testAccount;

            Non_ERP_Products__c nonERPProduct = new Non_ERP_Products__c(Name = 'Test Product');
            insert nonERPProduct;

            Product_Profiling__c testPPRecord = new Product_Profiling__c(
                    Account__c = testAccount[0].Id,
                    Product_Name__c = nonERPProduct.Id
            );
            insert testPPRecord;

            // Retrieve the record after assignment
            testPPRecord = [SELECT DEPUniqueKey__c FROM Product_Profiling__c WHERE Id = :testPPRecord.Id];

            // Assert the result
            System.assertEquals(
                    testPPRecord.DEPUniqueKey__c,
                    String.valueOf(testAccount[0].Id).substring(0, 15) + String.valueOf(nonERPProduct.Id).substring(0, 15)
            );
        }

    }

    @isTest
    public static void testPreventDeletion() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];

        System.runAs(testUser){
            // Create test data
            List<Account> testAccount = TestDataFactory.returnAccounts(1, 'CIM_Account', testUser.Id);
            insert testAccount;

            Non_ERP_Products__c nonERPProduct = new Non_ERP_Products__c(Name = 'Test Product');
            insert nonERPProduct;

            Product_Profiling__c testPPRecord = new Product_Profiling__c(
                    Account__c = testAccount[0].Id,
                    Product_Name__c = nonERPProduct.Id,
                    Integrated__c = true
            );
            insert testPPRecord;

            Boolean deletionPrevented = false;

            Test.startTest();
            try {
                // Attempt to delete the record
                delete testPPRecord;
            } catch (DmlException e) {
                String expectedErrorMessage = 'You are not authorised to delete this Product Profiling Record, please contact your administrator.';
                System.assertEquals(expectedErrorMessage, e.getDmlMessage(0), 'Error message should match');
                deletionPrevented = true;
            }
            Test.stopTest();

            // Verify that the record is still present after deletion attempt
            testPPRecord = [SELECT Id FROM Product_Profiling__c WHERE Id = :testPPRecord.Id LIMIT 1];
            System.assertNotEquals(null, testPPRecord, 'Record should not have been deleted');

            // Assert that deletion was prevented
            System.assertEquals(true, deletionPrevented, 'Deletion should have been prevented');
        }
    }

}