src/objects/OpenOrderLine__c.object
<CustomObject>
    <description>Standalone object. Populated by integration.
Object Owners : Chris Payne, Claus Wenkel, Jörg Walter, Yauheni Frenkel</description>
    <label>Open Order Line</label>
    <nameField>
        <displayFormat>OOL{0000000000}</displayFormat>
        <label>OpenOrderLine Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <recordTypes>
        <fullName>Free_Good_Order</fullName>
        <active>true</active>
        <label>Free Good Order</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PricingMicroServiceCallOut__mdt.object
<CustomObject>
    <fields>
        <fullName>Client_ID__c</fullName>
        <label>Client ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GetOrderDetailsLogicAppsURL__c</fullName>
        <label>Get Order Details Logic Apps URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scope__c</fullName>
        <label>Scope</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secret_Id__c</fullName>
        <label>Secret Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TokenURL__c</fullName>
        <label>Token URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Logic Apps Call Out</label>
    <pluralLabel>Logic Apps Call Outs</pluralLabel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>User_Country__c</fullName>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_Code_full</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src/globalValueSets/Country_Code_full.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>BEX</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>Croatia</fullName>
    </customValue>
    <customValue>
        <fullName>Cyprus</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor Markets</fullName>
    </customValue>
    <customValue>
        <fullName>Egypt</fullName>
    </customValue>
    <customValue>
        <fullName>Estonia</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Greece</fullName>
    </customValue>
    <customValue>
        <fullName>Holland</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>HQ: DE</fullName>
    </customValue>
    <customValue>
        <fullName>HQ: NL</fullName>
    </customValue>
    <customValue>
        <fullName>HQ: SE</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesia</fullName>
    </customValue>
    <customValue>
        <fullName>Israel</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <masterLabel>Country Code (full)</masterLabel>
</GlobalValueSet>

src/classes/GetOrderStatusCallOutTest.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Roberto Narbona
Description:    GetOrderStatusCallOut Class
--------------------------------------------------------------------------------------------------------*/

@isTest(seeAllData=false)
public with sharing class GetOrderStatusCallOutTest {
    /*-------------------------------------------------------------------------------------------------------
    
    Description: Setup one user for the test class
    History :
    --------------------------------------------------------------------------------------------------------*/
    @testSetup
    private static void setup() {
        List<User> userList = TestDataFactory.createUsers(1, '#System: System Administrator');
        System.runas(userList.get(0)) {
            
        }
        TestDataFactory.createBypassCustomSetting();
        List<User> userIntegrationList = TestDataFactory.insertIntegrationUsers(1, 'System Administrator');
        TestDataFactory.createGlobalIntegrationSettings(userIntegrationList);
    }

    @isTest
    private static void testSetup() {
        Test.startTest();
        List<User> testUserList = [SELECT Id FROM User WHERE Alias = 'test1'];
        Test.stopTest();
        
        System.assertEquals(1, testUserList.size(), 'Expected one user');
    }

    @isTest
    private static void testGetCountryCode() {
        User testUser = [SELECT Id,User_Country__c FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            Test.startTest();
                String country = GetOrderStatusCallOut.getCountryCode();
                system.debug(country);
            Test.stopTest();
        }
    }
    @isTest 
    private static void testGetOrderNumber() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            List<Account> accounts = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
            List<OpenOrderLine__c> openOrderLines = TestDataFactory.createOpenOrderLines(1, accounts);
            Test.startTest();
                String country = GetOrderStatusCallOut.getOrderNumber(openOrderLines[0].Id, 'OpenOrderLine__c');
            Test.stopTest();
        }
    }

    @isTest 
    private static void testGetOrderNumber2() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
        List<Account> accounts = TestDataFactory.createAccounts(1, 'Non_ERP_Account', testUser.Id);
        List<Order> orders = TestDataFactory.createOrders(1, 'Free_Good_Order', accounts);
        Test.startTest();
            String country = GetOrderStatusCallOut.getOrderNumber(orders[0].Id, 'Order');
        Test.stopTest();
        }
    }

    
    @isTest 
    private static void testGetTokenId() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            PricingMicroServiceCallOut__mdt calloutDetail = [SELECT Client_ID__c, GetOrderDetailsLogicAppsURL__c, Scope__c, Secret_Id__c, TokenURL__c FROM PricingMicroServiceCallOut__mdt Limit 1];
            Test.startTest();
                String token = GetOrderStatusCallOut.getTokenId(calloutDetail);
            Test.stopTest();
        }
    }
    @isTest 
    private static void testGetOrderStatusCallOut() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {
            Test.startTest();
                Map<String, Object> callBack = GetOrderStatusCallOut.getOrderStatusCallOut('US', '55');
            Test.stopTest();
        }
    }
}