src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>GET</fullName>
        <active>true</active>
        <businessProcess>GET</businessProcess>
        <label>X DO NOT USE 2t</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lightning_Pipeline_Opportunity</fullName>
        <active>true</active>
        <businessProcess>Lightning Sales</businessProcess>
        <description>Lightning Pipeline Opportunity</description>
        <label>Lightning Pipeline Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product_bundle__c.object
<CustomObject>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Product bundle</relationshipLabel>
        <relationshipName>Product_bundle</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product bundle</label>
    <nameField>
        <label>Product bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product bundle</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QuoteProductBundle__c.object
<CustomObject>
    <description>TFUS-000004537 
Junction object to tie Quotes and Bundles/Promotions/Offers together. Used for Bundle and promotion selling - guided selling and structured pricing around promotions</description>
    <fields>
        <fullName>ProductBundle__c</fullName>
        <label>Product Bundle</label>
        <referenceTo>Product_bundle__c</referenceTo>
        <relationshipName>Quote_Product_Bundles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipName>Quote_Product_Bundles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line Bundle</label>
    <nameField>
        <displayFormat>QLB-{0000}</displayFormat>
        <label>Quote Line Bundle #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Bundles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AddBundlesTest.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Roberto Narbona
Description:    Test classes for AddBundles Class
--------------------------------------------------------------------------------------------------------*/

@isTest(seeAllData=false)
public with sharing class AddBundlesTest {
    @testSetup
    private static void setup() {
        List<User> userList = TestDataFactory.createUsers(1, '#System: System Administrator');
        System.runas(userList.get(0)) {
            
        }
        TestDataFactory.createBypassCustomSetting();
        List<User> userIntegrationList = TestDataFactory.insertIntegrationUsers(1, 'System Administrator');
        TestDataFactory.createGlobalIntegrationSettings(userIntegrationList);
    }

    @isTest
    private static void testSetup() {
        Test.startTest();
        List<User> testUserList = [SELECT Id FROM User WHERE Alias = 'test1'];
        Test.stopTest();
        
        System.assertEquals(1, testUserList.size(), 'Expected one user');
    }

    @isTest 
    private static void getPricebookBundles() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {

            List<Pricebook2> pricebook = TestDataFactory.createPricebooks(1,'test PB');
            List<Product_bundle__c> bundles = TestDataFactory.returnBundles(1);
            bundles[0].Price_Book__c = pricebook[0].Id;
            insert bundles;
            
            Test.startTest();
            List<Product_bundle__c> bundlesOnPricebook = AddBundles.getPricebookBundles(pricebook[0].Id);
            Test.stopTest();
            System.assertEquals(1, bundlesOnPricebook.size(), 'We expect one bundle');
        }
    }

    @isTest 
    private static void getPriceBooks() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {

            List<Pricebook2> pricebook = TestDataFactory.createPricebooks(1,'test PB');
            
            Test.startTest();
            List<Pricebook2> pricebookChoices = AddBundles.getPriceBooks();
            Test.stopTest();
            System.assertEquals(1, pricebookChoices.size(), 'We expect one pricebook choice');
        }
    }

    @isTest 
    private static void insertQuoteBundles() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {

            List<Pricebook2> pricebook = TestDataFactory.createPricebooks(1,'test PB');
            List<Product_bundle__c> bundles = TestDataFactory.returnBundles(1);
            bundles[0].Price_Book__c = pricebook[0].Id;
            insert bundles;
            List<Account> acc = TestDataFactory.createAccounts(1, 'Non_ERP_Account' ,testUser.Id);
            List<Opportunity> opp = TestDataFactory.returnOpportunities(1, 'Lightning_Pipeline_Opportunity', testUser.Id);
            opp[0].AccountId = acc[0].Id;
            insert opp;
            List<Quote> quote = TestDataFactory.returnQuotes(1);
            quote[0].OpportunityId = opp[0].Id;
            insert quote;
            List<QuoteProductBundle__c> quoteProductBundle = TestDataFactory.returnQuoteProductBundle(1);
            quoteProductBundle[0].Quote__c = quote[0].Id;
            quoteProductBundle[0].ProductBundle__c = bundles[0].Id;
            
            Test.startTest();
            Boolean bundlesOnPricebook = AddBundles.insertQuoteBundles(quoteProductBundle);
            Test.stopTest();
            System.assertEquals(true, bundlesOnPricebook, 'product quote bundles inserted');
        }
    }

    @isTest 
    private static void updateRecord() {
        User testUser = [SELECT Id FROM User WHERE Alias = 'test1'];
        System.runAs(testUser) {

            List<Pricebook2> pricebook = TestDataFactory.createPricebooks(1,'test PB');
            List<Product_bundle__c> bundles = TestDataFactory.returnBundles(1);
            bundles[0].Price_Book__c = pricebook[0].Id;
            insert bundles;
            List<Account> acc = TestDataFactory.createAccounts(1, 'Non_ERP_Account' ,testUser.Id);
            List<Opportunity> opp = TestDataFactory.returnOpportunities(1, 'Lightning_Pipeline_Opportunity', testUser.Id);
            opp[0].AccountId = acc[0].Id;
            insert opp;
            List<Quote> quote = TestDataFactory.returnQuotes(1);
            quote[0].OpportunityId = opp[0].Id;
            insert quote;
            
            
            Test.startTest();
            Boolean bundlesOnPricebook = AddBundles.updateRecord(quote[0].Id, pricebook[0].Id);
            Test.stopTest();
            System.assertEquals(false, bundlesOnPricebook, 'quote has been updated');
        }
    }

}