src/objects/ProcedureTracker__c.object
<CustomObject>
    <description>Follow Up your Sales Lifecycle with step-by-step guided instructions. 
#1 Procedure Type: Clear Aligners - suresmile</description>
    <fields>
        <fullName>PracticeAccount__c</fullName>
        <label>Practice Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Procedures</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProcedureType__c</fullName>
        <label>Procedure Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Clear Aligners</fullName>
                    <default>true</default>
                    <label>Clear Aligners</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Procedure Tracker</label>
    <nameField>
        <displayFormat>Track#{000}</displayFormat>
        <label>Record Nr</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Procedure Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProcedureTrackerTriggerHelper.cls
/*-------------------------------------------------------------------------------------------------------
Author:         Miguel Coimbra (Salesforce) 2022-05-20
Description:    ProcedureTracker  Trigger Helper Class
Test class      Test_ProcedureTrackerTriggerHelper
History
----------------------------------------------------------------------------------------*/
public with sharing class ProcedureTrackerTriggerHelper {
    
    public static void checkUniqueness(List<ProcedureTracker__c> newProcedureTrackerList) {
        // The Procedure Tracker must be unique (Type + Account)
        Set<Id>     accountIds      = new Set<Id>();
        Map<Id, ProcedureTracker__c> procedureProfilingPerAcc = new Map<Id, ProcedureTracker__c>();
        for(ProcedureTracker__c pt: newProcedureTrackerList){
        	accountIds.add(pt.PracticeAccount__c);
    	}
        // Get all existing procedure trackers of the relevant accounts. 
        List<ProcedureTracker__c> existingProceduretrackers = [SELECT id, PracticeAccount__c, ProcedureType__c FROM ProcedureTracker__c WHERE PracticeAccount__c IN: accountIds];
        if(existingProceduretrackers.isEmpty()){
            return; 
        }
        
        // build a set of unique strings composed by the unique partner of AccountID + ProcedureType
        Set<String> uniqueAccountIdAndProceduretype = new Set<String>() ; 
        for(ProcedureTracker__c pt: existingProceduretrackers){
            uniqueAccountIdAndProceduretype.add(pt.PracticeAccount__c + '' + pt.ProcedureType__c);
        }

        // fire an error if the procedure tracker that is about to be created already exists (account+type)
        for(ProcedureTracker__c pt: newProcedureTrackerList){
            if (uniqueAccountIdAndProceduretype.contains(pt.PracticeAccount__c + '' + pt.ProcedureType__c)){
                pt.addError(Label.One_Procedure_Tracker_Per_Account_and_Type);
            }
        }
    }
}