src/objects/Product_Profiling__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products Profiling</relationshipLabel>
        <relationshipName>Products_Profiling</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Products Profiling</relationshipLabel>
        <relationshipName>Products_Profiling</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DEPUniqueKey__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>(String) record.Account__c + (String) record.Contact__c + (String) record.Non_Erp_Product_ID__c;</description>
        <externalId>true</externalId>
        <inlineHelpText>(String) record.Account__c + (String) record.Contact__c + (String) record.Non_Erp_Product_ID__c;</inlineHelpText>
        <label>DEP Unique Key</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>DoNotDelete__c</fullName>
        <formula>AND(
    Integrated__c,
    NOT(
        OR(
            $Profile.Name = &quot;System Administrator&quot;,
            $Profile.Name = &quot;#System: System Administrator&quot;
        )
    )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Do Not Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Integrated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To identify if a record was created by integration.</description>
        <inlineHelpText>To identify if a record was created by integration.</inlineHelpText>
        <label>Integrated ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Non-ERP Product</label>
        <referenceTo>Non_ERP_Products__c</referenceTo>
        <relationshipLabel>Products Profiling</relationshipLabel>
        <relationshipName>Products_Profiling</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Product Profiling</label>
    <nameField>
        <displayFormat>PP{000000000}</displayFormat>
        <label>Profiling Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Profiling</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProductProfilingTriggerHelper.cls
/*-------------------------------------------------------------------------------------------------	
 * Author            : ohanafi@salesforce.com
 * Description       : Product Profiling trigger helper
 * Test class        : Test_ProductProfilingTriggerHelper
 * History	
 * 02-02-2024         Created ProductProfilingTriggerHelper class (TFUS-000006225)
 * 19-06-2024 		  Miguel Coimbra	Hotfix: Removed filter condition on  "&& !record.Integrated__c" to allow us to edit non-erp product records and assign the right unique key
--------------------------------------------------------------------------------------------------*/
public with sharing class ProductProfilingTriggerHelper {

    /**
     * assignUniqueKeyIdentifier Method that assigns a unique key identifier to the Product Profiling records
     * @author ohanafi@salesforce.com | 02-02-2024
     *
     * @param oldProductProfilingMap   Map of old product profiling records
     * @param newProductProfilingList   List of new product profiling records
     *
     */
    public static void assignUniqueKeyIdentifier(Map<Id, Product_Profiling__c> oldProductProfilingMap, List<Product_Profiling__c> newProductProfilingList){
        // Check if the old map is empty to determine if the records are being inserted
        Boolean isInsert = oldProductProfilingMap == null || oldProductProfilingMap.isEmpty();

        for (Product_Profiling__c record : newProductProfilingList) {
            // Check if the record is new or any relevant fields have changed
            if (
                    (record.Account__c != null && record.Product_Name__c != null) &&
                            (isInsert
                                    || (oldProductProfilingMap != null &&
                                        (record.Account__c != oldProductProfilingMap.get(record.Id).Account__c ||
                                        record.Contact__c != oldProductProfilingMap.get(record.Id).Contact__c ||
                                        record.Product_Name__c != oldProductProfilingMap.get(record.Id).Product_Name__c)
                                    )
                            )
            ) {

                // Calculate the unique key identifier based on the account, contact and
                String uniqueKeyIdentifier = calculateUniqueKeyIdentifier(record);
                record.DEPUniqueKey__c = uniqueKeyIdentifier;
            }
        }
    }

    /**
     * calculateUniqueKeyIdentifier Method that calculates the unique key identifier.
     * @author ohanafi@salesforce.com | 02-02-2024
     *
     * @param record The Product Profiling record
     * @return The unique key identifier
     */
    private static String calculateUniqueKeyIdentifier(Product_Profiling__c record) {
        String uniqueKeyIdentifier;

        String product15digitId = record.Product_Name__c;
        Id product18digitId = Id.valueOf(product15digitId); // Convert 15-digit Id to 18-digit Id

        if (String.isBlank(record.Contact__c)) {
            uniqueKeyIdentifier = String.valueOf(record.Account__c) + String.valueOf(product18digitId);
        } else {
            uniqueKeyIdentifier = String.valueOf(record.Account__c) +
                    String.valueOf(record.Contact__c) +
                    String.valueOf(product18digitId);
        }

        return uniqueKeyIdentifier;
    }

    /**
     * preventDeletion Prevent the deletion of the records that are automatically created
     * @author ohanafi@salesforce.com | 28-02-2024
     *
     * @param productProfilingList   List of product profiling records
     *
     */
    public static void preventDeletion(List<Product_Profiling__c> productProfilingList){
        for(Product_Profiling__c record : productProfilingList){
            if(record.DoNotDelete__c) {
                record.addError('You are not authorised to delete this Product Profiling Record, please contact your administrator.');
            }
        }
    }
}