src/objects/Product_Profiling__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products Profiling</relationshipLabel>
        <relationshipName>Products_Profiling</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Products Profiling</relationshipLabel>
        <relationshipName>Products_Profiling</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DEPUniqueKey__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>(String) record.Account__c + (String) record.Contact__c + (String) record.Non_Erp_Product_ID__c;</description>
        <externalId>true</externalId>
        <inlineHelpText>(String) record.Account__c + (String) record.Contact__c + (String) record.Non_Erp_Product_ID__c;</inlineHelpText>
        <label>DEP Unique Key</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Non_Erp_Product_ID__c</fullName>
        <formula>Product_Name__r.Id</formula>
        <label>Non Erp Product ID</label>
        <type>Text</type>
    </fields>
    <label>Product Profiling</label>
    <nameField>
        <displayFormat>PP{000000000}</displayFormat>
        <label>Profiling Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Profiling</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchCalculatePPUniqueKey.cls
/**
 * Created by ohanafi on 25/1/2024.
 */
public class BatchCalculatePPUniqueKey implements Database.Batchable<sObject> {

    // Query to retrieve all Product Profiling records
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator('SELECT Id, Account__c, Contact__c, Non_Erp_Product_ID__c, DEPUniqueKey__c FROM Product_Profiling__c');
    }

    // Calculate and set the unique key identifier
    public void execute(Database.BatchableContext BC, List<Product_Profiling__c> scope) {
        for(Product_Profiling__c record : scope) {
            // Calculate the unique key identifier based on account, contact, and Non_Erp_Product_ID__c
            String uniqueKeyIdentifier;
            if (String.isBlank(record.Contact__c)) { // We use the 15-digit ID
                uniqueKeyIdentifier = String.valueOf(record.Account__c).substring(0, 15) + String.valueOf(record.Non_Erp_Product_ID__c).substring(0, 15);
            } else {
                uniqueKeyIdentifier = String.valueOf(record.Account__c).substring(0, 15) +
                        String.valueOf(record.Contact__c).substring(0, 15) +
                        String.valueOf(record.Non_Erp_Product_ID__c).substring(0, 15);
            }
            record.DEPUniqueKey__c = uniqueKeyIdentifier;
        }
        update scope;
    }

    public void finish(Database.BatchableContext BC) {
    }
}