src/objects/User.object
<CustomObject>
    <fields>
        <fullName>User_Country__c</fullName>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_Code_full</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src/globalValueSets/Country_Code_full.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>BEX</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>Croatia</fullName>
    </customValue>
    <customValue>
        <fullName>Cyprus</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor Markets</fullName>
    </customValue>
    <customValue>
        <fullName>Egypt</fullName>
    </customValue>
    <customValue>
        <fullName>Estonia</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Greece</fullName>
    </customValue>
    <customValue>
        <fullName>Holland</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>HQ: DE</fullName>
    </customValue>
    <customValue>
        <fullName>HQ: NL</fullName>
    </customValue>
    <customValue>
        <fullName>HQ: SE</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesia</fullName>
    </customValue>
    <customValue>
        <fullName>Israel</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <masterLabel>Country Code (full)</masterLabel>
</GlobalValueSet>

src/classes/Test_NewContractController.cls
/*-------------------------------------------------------------------------------------------------	
Author: 	naoussar@salesforce.com (Salesforce) 2022094 
History	
20220910   created (TFUS-000004611) 
--------------------------------------------------------------------------------------------------*/
@isTest
public class Test_NewContractController {
	@testSetup
    private static void testSetup() {
        List<User> userList = TestDataFactory.createUsers(1, 'Lightning Sales Rep');
        TestDataFactory.createBypassCustomSetting();
        List<User> userIntegrationList = TestDataFactory.insertIntegrationUsers(1, 'System Administrator');
        TestDataFactory.createGlobalIntegrationSettings(userIntegrationList);
        List<Account> testAccountList = TestDataFactory.createAccounts(1, 'CIM_Account', userList[0].Id);
        testAccountList[0].OneAccount_Type__c = 'Competitor';
        update testAccountList;
    }
    
    
    @isTest
    private static void testEligibilityOfCreation() {
        Boolean isEligible;
        User testUser = [SELECT Id, User_Country__c FROM User where Alias='test1' LIMIT 1];
        Account acc = [SELECT Id FROM Account limit 1]; 
        testUser.User_Country__c = 'Germany';
        update testUser;
        System.runAs(testUser){
            isEligible = NewContractController.isUserEligibleForCustomContractCreation(acc.Id);
        }
        System.assertEquals(true,isEligible,'User is eligible for custom creation of contracts');
        
    }
}